### ISSUE TITLE
Datasets 18 data visualization @arcuellar88

### ISSUE THREAD

**Issue by arcuellar88** [Laboratoria/curricula-js#100]
Hola @MariPlaza,

No tengo tanto tiempo como pensaba inicialmente para este proyecto. Te propongo dividirnos esta tarea. Tengo entendido que queremos tener 5 datasets adicionales.

Yo puedo encargarme de dos y los entrego el próximo lunes 7 de Agosto.

1) Indicadores de género utilizando la herramienta que hice para el BID: https://github.com/arcuellar88/gender-indicator
2) Base de datos de retail (e-commerce)

Para cada dataset propongo crear los siguientes metadatos: 
1. Nombre
2. Descripción
3. Diccionario
4. Esquema (en caso de tener más de una tabla)
5. Formato (texto, excel, etc.) 
6. Fuente
7. Licencia de uso

Como parte de las entrega del proyecto final propongo que se incluya una sección de metadatos donde se agreguen las transformaciones que hicieron en Tableu (por ejemplo si agregaron columnas) y los datos generales de los datos cómo: 

- número de filas (registros) y columnas
- Perfil de datos para cada columna (algo general), por ejemplo para la columna año de penetración de internet: rango desde el 2010 hasta el 2015)

Si alcanzo a crear otro dataset te aviso.

Saludos,

Alejandro

**Comment by MariPlaza** [comment]
Chevere Alejandro. Yo voy a aprovechar de ver el de música que propusiste y un set de data de Gap Minder que tiene fertilidad y desarrollo. La otra data puede ser la que inicialmente se había pensado de comercio de la región que ya está lista. 

Me parece bien los campos y comentarios que mencionas. 

Saludos y gracias.

**Comment by arcuellar88** [comment]
Hola @MariPlaza ,

Estaba trabajando en el dataset de Gender indicator pero los indicadores están en inglés. Esto es un problema? La única fuente que tiene los indicadores en español es el BID, pero los indicadores de GAP (masculino vs femenino) no son muy interesantes para analizar. 

Saludos,
