### ISSUE TITLE
Formato de curso 10-functional (asciidoc)

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#102]
@milmazz, @an1tae:

Me parece muy interesante el formato y las herramientas que están usando. Creo que debemos extraer varias convenciones para aplicar a otros cursos. Pero al mismo tiempo, por lo menos por ahora, creo que no nos deberíamos preocupar por los detalles de presentación (conversión a HTML), si no en las convenciones que estamos desarrollando para la curricula en general… En el corto plazo, cosas como tablas de contenido, html, linters, … las dejaría fuera.

Les cuento que en este momento se está diseñando un parser que analiza el markdown de los cursos de este repo y crea un JSON que después vamos a usar en nuestro LMS para la experiencia de nuestras alumnas. El parser se basa en una serie de convenciones que estoy en proceso de documentar (y desarrollar). Me gustaría que tengamos una llamada la semana que viene para darles más detalles sobre todo esto y ver cómo podemos acordar un "formato" que aproveche algunas de las cosas que están haciendo y al mismo tiempo no se "cruce" con el parser. Les parece el miércoles que viene tipo 10am?

Gracias (otra vez 😉)

**Comment by milmazz** [comment]
@lupomontero Perfecto!, sabíamos que en algún punto debíamos dejar de lado el formato `asciidoc` para darle paso a Markdown pues es lo que tienen ahora como estándar. Esperamos reunirnos contigo para tener claro el formato que esperan para el desarrollo que van a realizar y así proceder con las modificaciones necesarias.

Tanto a @an1tae como a mi nos conviene reunirnos entre las 12:00 hasta las 14:00 del miércoles, espero no tengas inconveniente en ajustar la hora.

**Comment by lupomontero** [comment]
Genial! Los he invitado (via evento de calendario) a una "llamada" por hangouts el miércoles de 12 a 14h (hora de Lima).

**Comment by milmazz** [comment]
@lupomontero Todas las lecciones que estaban en formato asciidoc ya se pasaron a Markdown. Por lo tanto, creo que este _issue_ ya lo podemos dar por terminado :)

**Comment by lupomontero** [comment]
Cierro este issue, gracias.

En este momento estamos en proceso de documentar y aplicar una serie de convenciones de formato y estructura. Así que una vez que terminemos con los PRs abiertos, nosotros nos encargamos de darle un repaso sin quitarte más tiempo en estos temas puramente de estilo y formato. Gracias otra vez!
