### ISSUE TITLE
Implementar producto (clon de pinterest + librería dom) para 08-deep-dive

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#105]

**Comment by ivandevp** [comment]
En este repositorio se está creando el plugin, ahorita está subida una versión funcional pero nada optimizada en [este repositorio](https://github.com/Laboratoria/pinterestify). Iré actualizando ese repo conforme vaya optimizándolo. Ya da una idea de la estructura del curso, paso a la implementación del mismo.

**Comment by ivandevp** [comment]
Se cierra este issue, en caso de algún improvement o bug se abrirá un issue o PR específico.
