### ISSUE TITLE
Desarrollo contenido `01-basic-programming-in-javascript`

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#109]
- [x] edit opening @chamo
- [x] pulir el lecture @chamo
- [x] pulir el opening @chamo
- [x] crear video de `arrays` (array dinosaurios pg 44 JS for Kids) @MichelleSV 
- [x] crear video de imprimir en la consola información del array de objetos de estudiantes @MichelleSV 
- [x] crear video de `objects` @MichelleSV 
- [x] crear video de tips para  `Tarjeta de Credito` @MichelleSV 
- [x] crear solucionario del ejercicio`Ceasar Cipher` @MichelleSV 
- [x] crear solucionario del ejercicio`Tarjeta de credito` @MichelleSV
- [x] crear solucionario del ejercicio `Cajero automático` @MichelleSV 
- [x] crear lectura de `git` @MichelleSV
- [x] crear lectura de `comand-line` @MichelleSV + @RuthSalvador 
- [x] crear video solucionario del ejercicio `Reverse` @developerVilchez 
- [x] crear video solucionario del ejercicio `Search` @developerVilchez 
- [x] crear video solucionario del ejercicio `Array to Object` @developerVilchez 
- [x] crear quiz 1 @RuthSalvador 
- [x] crear quiz 2 @RuthSalvador 
- [x] crear solucionario del ejercicio `Sum` @MichelleSV 
- [x] crear solucionario del ejercicio `Scorekeeper ` @MichelleSV 
- [x] crear solucionario del ejercicio `Sort` @MichelleSV 
- [x] crear solucionario del ejercicio `Comparison` @MichelleSV 
- [x] crear solucionario del ejercicio `Remove Duplicates` @MichelleSV 
- [x] crear video de tips para  `Ceasar Cipher` @MichelleSV 
- [x] crear autoevaluación @chamo

**Comment by chamodev** [comment]
@RuthSalvador @MichelleSV @developerVilchez: he creado un nuevo branch [`02-interactive-site`](https://github.com/Laboratoria/curricula-js/tree/02-interactive-site/02-interactive-site) para trabajar en este curso de forma independiente al `01-intro` (antes teníamos `intro-js` para ambos cursos).

**Comment by ivandevp** [comment]
@chamodev este issue ya está completo para cerrarlo?

**Comment by chamodev** [comment]
Sí! tareas completadas. Cierro el issue.

Gracias a todxs por el excelente trabajo :)
