### ISSUE TITLE
Elegir y documentar guías de estilos (style guides)

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#11]
Por ahora hay una nota en el `README.md` de este repo que lista (sugiere) dos guías de estilos:

* [AirBnB](https://github.com/airbnb/javascript) para el front-end
* [Hapi](https://hapijs.com/styleguide) para todo lo que sea Node.js

El motivo por el cual se han incluido dos guías diferentes es que `Node.js` todavía no tiene soporte para algunos features de ES6 que la guía de estilos de AirBnB da por hecho. Además, nos obliga a no encerrarnos en único estilo y tener la flexibilidad y adaptabilidad para funcionar en diferentes entornos.

Por otro lado, veo que @ivandevp ya había creado un [repo con una guía de estilos](https://github.com/Laboratoria/js-style-guide), así que sería chévere tener una conversación por acá entre tod@s, decidir como equipo, y después asignarle la tarea a alguien para que lo documente.

Como parte de selección de las guías de estilo, también toca elegir un _linter_ y una _configuración_ o _plugin_ para poder automatizar el proceso. Como punto de partida, propongo usar [`eslint`](http://eslint.org/) que tiene plugins y configuraciones para las guías sugeridas (AirBnB y Hapi).

cc/ @chamodev @ivandevp @giancorzo @lizzie136 @rodrwan @indie-rok

**Comment by ivandevp** [comment]
Quedamos como primera propuesta usar la guía de estilos de [AirBnB](https://github.com/airbnb/javascript) para >= ES2015 y [Google Style Guide](https://google.github.io/styleguide/javascriptguide.xml) para  < ES2015.
