### ISSUE TITLE
Ejercicio Procedural 2 de 4 de Paradigmas de Programacion

### ISSUE THREAD

**Issue by berenisser** [Laboratoria/curricula-js#110]
Problemas con los nombre de funcion isPrime y la varible isPrime, se debe cambiar el nombre de la variable para que no hay confusion al momento de correr las pruebas.

Tambien hay problemas con todos los tests, en la consola corren las funciones pero no en la terminal

**Comment by lupomontero** [comment]
@berenisser: gracias por reportar este _issue_ 🎉 

1. Para aclarar la confusión con los nombres de la variable `isPrime` y la función `isPrime()` he modificado un poco los requisitos del ejercicio para que se entienda mejor la intención. Acá puedes ver los [cambios](https://github.com/Laboratoria/learnyouparadigms/blob/42ccf91532e7535c60f495b60de81a09a6d54c07/exercises/procedural_programming/problem.md#requisitos). Para actualizar `learnyouparadigms` a la última versión puedes ejecutar este comando: `npm install -g Laboratoria/learnyouparadigms`.

2. Con respecto al problema de los tests, podrías darme un poco más info? Algún mensaje de error?

Gracias otra vez por el feedback!
