### ISSUE TITLE
Problemas con los test del ejercicio 'procedural.js' de  Paradigmas de Programación 

### ISSUE THREAD

**Issue by amalakamala** [Laboratoria/curricula-js#111]
- A pesar que la solución pasa en la consola del navegador no pasa los test. En uno de ellos aparece:

"5) isPrime(num) debería retornar true para 2, 3, 5, 13, 89:
     TypeError: Submission.isPrime is not a function"
Y debería ser "2, 3, 5, 13, 17,19"

- Las variable posee el mismo nombre que la función.

```var arr = [];

function isPrime(num){
	for(var j = 2; j < num; j++){
    	if(num % j  == 0){
  		return false;
  		}
    }    
    return j;     
}

function getPrimes(start, end){
  for (var i = start; i < end; i++) {
    var isprime = true;    

    if (isPrime(i)){
      arr.push(i);       
    }
  }
  return arr;
}```

**Comment by giancorzo** [comment]
#110 Estos dos issues están relacionados.

**Comment by lupomontero** [comment]
@amalakamala: gracias por reportar este _issue_ 🎉 

1. El error `TypeError: Submission.isPrime is not a function` parece indicar que la función `isPrime` no ha sido _exportada_ en el archivo `procedural.js`

2. Con respecto a los valores de las pruebas unitarias de `isPrime`, el enunciado del test simplemente dice que debería retornar `true` para los valores `2`, `3`, `5`, `13` y `89`, lo cual es correcto. No está verificando todos los primos hasta `89`, sino que la función retorna lo esperado para esos inputs.

3. Para aclarar la confusión con los nombres de la variable `isPrime` y la función `isPrime()` he modificado un poco los requisitos del ejercicio para que se entienda mejor la intención. Acá puedes ver los [cambios](https://github.com/Laboratoria/learnyouparadigms/blob/42ccf91532e7535c60f495b60de81a09a6d54c07/exercises/procedural_programming/problem.md#requisitos). Para actualizar `learnyouparadigms` a la última versión puedes ejecutar este comando: `npm install -g Laboratoria/learnyouparadigms`.

Gracias por el feedback!
