### ISSUE TITLE
Mejora en el manejo de Assets 

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/curricula-js#114]
La currícula cada vez se está poniendo más gorda y es por culpa de los diferentes assets que estamos incluyendo en nuestro repositorio (videos, imágenes, ppts, excels, etc).

Por lo que abro este issue para poder discutir algunos mecanismos para manejar assets.

Nosotros actualmente tenemos google cloud platform donde podemos crear buckets para almacenar contenido estático. Tenemos 5GB free (actualmente la curricula completa pesa 1.5GB) y 1GB free de transferencia, pasados estos límites el costo es de 0.026 centavos y 0.11 dólares x GB de transferencia.

Me gustaria saber si tienen alguna otra opción free o no free que podamos usar antes de decidir por una.
También acepto ideas de como manejar la distribución de los assets (todo lo enviamos a una misma persona que lo suba al CDN o cada quien sube y cual sería la convención para la estructuración del contenido.

**Comment by giancorzo** [comment]
Hola @MariPlaza @arcuellar88,

Chicos estuve revisando su curso y veo que tenemos muchos ppts, como sabrán los ppts son elementos difificil de compartir en línea y los cuales son díficiles de versionar por lo que les queria proponer lo siguiente:

1. Quisiera transformar todos sus PPTS a Google presentation dado que laboratoria tiene todos los materiales tipo PPT en ese formato.
2. Les puedo crear una carpeta compartida donde puedan guardar las presentation ahi.

Sobre sus videos en MP4 creo que podemos subirlos a nuestra cuenta de Wistia y vincularlos desde ahi.

Me cuentan que opinan

**Comment by MariPlaza** [comment]
Hola @giancorzo gracias por el ofrecimiento. Justo ayer estuve revisando el contenido con Carolina y me comentó que cambiaron un poco el enfoque del uso de GitHub y que todo el contenido que este acá estará disponible para las alumnas directamente.  Cuando comenzamos era exclusivamente para el desarrollo interno del curso. 

En efecto este curso, que posee más contenido teórico y mucho menos código que el tradicional de Laboratoria, requiere de material visual (cómo las presentaciones) para explicar el detalle.

Lo que acorde con Caro ayer es que ella va a revisar de nuevo el contenido, para mover lo que sea exclusivamente para el profesor a las carpetas de Google Drive, y que luego que esté revisado el contenido, yo voy a grabar la voz de los scripts sobre las presentaciones para transformarlo en un video. Cómo los videos (incluidos los que ya están y lo que se grabaran sobre las presentaciones) necesitan pasar por edición, podemos moverlos a Wistia una vez que sean los finales. 

Acordamos también que incluiriamos el link de los videos a los scripts (.md) para que así les quede a las alumnas la referencia en un sólo sitio. Como te comentó es trabajo in progress, porfa danos 3 semanas que es lo que queda aproximadamente de desarrollo del curso y debe quedar todo listo. 

Si tienes algún comentario avísame. Gracias!

**Comment by lupomontero** [comment]
En cualquier proyecto con control del versiones distribuido (`git` en nuestro caso) que involucre cualquier tipo de archivo que no sea texto plano, siempre aparecen este tipo de problemas. El repo crece de forma descontrolada y se hace difícil la colaboración sobre esos archivos - no podemos comentar por línea, ver diferencias (`diff`), ....

La gran ventaja de `git` es que cada versión de cada archivo queda en la historia, y cada clon tiene la historia completa, pero cuando añadimos archivos binarios, esta característica juega en nuestra contra.

Para minimizar el impacto de archivos binarios en el repo propongo lo siguiente:

1. **Evitar siempre que podamos el uso de archivos binarios**. Por ejemplo, tratar de escribir contenido de _presentaciones_ (slides) en formato markdown dentro del repo. Después, a la hora de la ejecución (cuando se dicta el curso), se pueden generar slides a partir del markdown.

2. **Videos no deben ser parte del repo**. Los videos deben subirse a YouTube, Wistia o similar y desde el repo simplemente [vincularlos usando una imagen y un link](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos). Si no tienes como subir los videos a una cuenta de YouTube o similar, lo mejor sería enviarle los videos por wetransfer o similar al coordinador del curso para subirlo donde proceda.

3. Cuando tengamos archivos binarios que sean fundamentales para el funcionamiento del repo, y que no podemos alojar de forma externa, **usemos `git-lfs` (Git Large File Storage)**.

   [![Git Large File Storage - How to Work with Big Files](http://img.youtube.com/vi/uLR1RNqJ1Mw/0.jpg)](http://www.youtube.com/watch?v=uLR1RNqJ1Mw)

   https://git-lfs.github.com/

Si tienen dudas no duden en preguntar.

cc/ @ivandevp @chamodev @merunga @milmazz @brecabal @MariPlaza @arcuellar88 @lizzie136

**Comment by giancorzo** [comment]
@lupomontero Documentaré esta información en nuestro wiki para que quede para la posteridad

**Comment by ivandevp** [comment]
Hola! Me gustaría retomar este tema, sobretodo para definir una convención del manejo de imágenes (archivos no necesariamente muy grandes) que se usan en algunos de los contenidos que estamos desarrollando. Las medidas que he podido ver que se utilizan son:

* Hostear las imágenes en algún servicio pero el detalle con esto es que te genera un enlace temporal.

* Otra es crear un issue y poner las imágenes ahí para que Github genere un CDN, pero no es una solución muy cool que digamos.

¿Alguna otra idea?

cc/ @chamodev  @lupomontero @giancorzo @merunga @arcuellar88

**Comment by merunga** [comment]
Hola @ivandevp 
Te cuento que lo que yo hice en el curso de react es simplemente crear una carpeta [static](https://github.com/Laboratoria/curricula-js/tree/master/11-react/L07-oop/static) dentro de la estructura de archivos y ahi subi las imagenes, en este caso `lifecycle.jpg`.

Por la naturaleza de git eso te genera un link fijo para ese archivo en ese commit: https://github.com/Laboratoria/curricula-js/raw/b6d68844bca94e063620ed49a72a776b1146a48a/11-react/L07-oop/static/lifecycle.jpg

El link lo obtienes desde el history del archivo en github:
![image](https://user-images.githubusercontent.com/211721/30883615-5496490e-a2d2-11e7-9762-595e0a480cb0.png)

El mayor problema que tiene este enfoque es que, como no puedes obtener el hash del commit hasta que efectivamente hayas hecho el commit, a priori no puedes saber cual va a ser el link

El mayor beneficio es que tus imagenes viven junto con tus markdowns.

Quizas se aplique a tu caso

**Comment by ivandevp** [comment]
Gracias @merunga! Lo implementaré para ver que tal, te comento como va con ese approach.

**Comment by lupomontero** [comment]
Qué opinan sobre añadir las imágenes como _attachments_  en un comentario de un issue (el que sea, no importa). Esto sube la imagen al CDN de GitHub y te da una URL permanente. No hay necesidad de _enviar_ el comentario, lo único que interesa es que el archivo quede subido.

Ejemplo acá: https://youtu.be/dfzAYn3dSnk

Qué les parece este solución? Yo la vengo usando ya un tiempo...

**Comment by lupomontero** [comment]
Se cierra este issue por inactividad.
