### ISSUE TITLE
Nuevos permisos de contribución

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/curricula-js#115]
@lupomontero ha cambiado la forma de contribución al repositorio, este issue es para hablar sobre el tema y posteriormente documentarlo en el contributing.md

@lupomontero cuando puedas por favor detalle el nuevo proceso de contribución.

**Comment by lupomontero** [comment]
Acabo de actualizar [`CONTRIBUTING.md`](https://github.com/Laboratoria/curricula-js/blob/master/CONTRIBUTING.md). En los próximos días, según avancen las conversaciones, se irán añadiendo más detalles en el wiki.
