### ISSUE TITLE
Crear mejor documentación de la curricula JS

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/curricula-js#116]
Hay mucha información que esta flotando en los distintos issues de github, con @lupomontero conversamos que es nuestra oportunidad de darle vida a nuestro wiki donde pongamos ya las decisiones finales respecto a varias cosas que hemos ido discutiendo como por ejemplo 

1. cómo empezar a trabajar en la curricula
2. permisos de contribución
3. cómo manejar los assets
4. cual es proceso que deben seguir antes de hacer un pull request, etc.

Aqui el punto de partida de la wiki, como siempre son bienvenidos a colaborar con contenido

https://github.com/Laboratoria/curricula-js/wiki

**Comment by lupomontero** [comment]
Cierro este issue en favor de ir abriendo issues más concretos sobre la guía para creadores que tenemos el [wiki](https://github.com/Laboratoria/curricula-js/wiki)
