### ISSUE TITLE
Curso React - Script de sesiones de Q&A y Code / Team Review

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curricula-js#117]

**Comment by merunga** [comment]
@lupomontero de donde puedo sacar los score cards de las experiencias anteriores?

**Comment by lupomontero** [comment]
@merunga: este issue quedó un poco olvidado 😢 

Lo cierro por ahora, que no es prioridad, y ya vemos los detalles cuando repasemos el contenido de React y Redux para `v2x`. Ok?
