### ISSUE TITLE
Usar Gitbook para mostrar el contenido

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/curricula-js#12]
Podemos usar gitbooks para mostrar el contenido de cada curso de una manera más bonita que directamente en el github.

Podemos importar el contenido del repo hacia gitbooks y además podemos crear organizaciones para tener todos los books (cursos) en un solo lugar

Aqui algunos links importantes:

[https://www.gitbook.com/](https://www.gitbook.com/)
[https://www.gitbook.com/blog/features/import-github](https://www.gitbook.com/blog/features/import-github)
[https://www.gitbook.com/blog/features/organizations](https://www.gitbook.com/blog/features/organizations)

**Comment by ivandevp** [comment]
Podemos tomar como referencia lo que hace Frontend Masters en su Gitbook [Front-End Handbook](https://www.gitbook.com/book/frontendmasters/front-end-handbook/details).

**Comment by giancorzo** [comment]
Cierro este issue porque gitbook ya es un standard como repositorio backup
