### ISSUE TITLE
03-interactive-site: Desarrollar contenido para 01-making-your-site-interactive

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#121]
- [x] opening 
- [x] dom
- [x] bom
- [x] modificando el dom
- [x] eventos
- [x] refactorizar el orden las carpetas para el parser @ivandevp 
- [x] crear el solucionario de `animación` y subir al repo privado de soluciones @indie-rok 
- [x] ejercicios guiados: falta agregar el enunciado del ejercicio de animación en el DOM @indie-rok 
- [x] 2 videos del DOM @developerVilchez / @indie-rok: code review & feedback
- [x] video solucionario de `aerolinea` @AmaliaRiveraC 
- [x] video solucionario de `buscaminas` @karlanavam
- [x] quiz 1 en formato parser @memecast 
- [x] lecture dom, bom @indie-rok 
- [x] subir solucionario de `ahorcado` al repo privado de soluciones @aocsa 
- [x] subir solucionario de `laberinto` al repo privado de soluciones @aocsa 
- [x] subir solucionario de `aerolinea` al repo privado de soluciones @AmaliaRiveraC 
- [x] subir solucionario de `buscaminas` al repo privado de soluciones @karlanavam
- [x] quiz 2 en formato parser @memecast  
- [x] self-assessment @ivandevp @alejandrarv 
- [x] closing @indie-rok 
- [x] lectura de data attributes @AnaSalazar  
- [x] video de tabs  @memecast
- [x] video de menú de hamburguesa @intidev
- [x] video de drop down menu @shirley-suarez
- [x] mini zoo para ejercicios guiados (enunciado + solución en el repo) @RuthSalvador 
- [x] captcha (enunciado + solución en el repo) @michellesegv 
- [x] ejercicio guiado ahorcado (enunciado + solución en el repo) @indie-rok 
- [x] ejercicios guiados (enunciado): 1. Freelancer interactivo 2. Nuestras coders interactivo @ivandevp
- [x] retos de código (enunciado): 1. Trello (versionado) 2. Twitter interactivo @ivandevp 
- [x] solucionario de freelancer interactivo, nuestras coders interactivo, trello y twitter en repo de soluciones @ivandevp

**Comment by chamodev** [comment]
@indie-rok: he creado un segundo milestone (iteración 2) para el 31 de Agosto. Apuntemos a tener 100% del contenido desarrollado para ese momento. Thks!

**Comment by chamodev** [comment]
@indie-rok : he creado un nuevo branch [`02-interactive-site`](https://github.com/Laboratoria/curricula-js/tree/02-interactive-site/02-interactive-site) para trabajar en este curso de forma independiente al `01-intro` (antes teníamos `intro-js` para ambos cursos).

**Comment by chamodev** [comment]
@indie-rok: @ivandevp ha sugerido agregar una serie de videos, ejercicios guiados y retos de código sobre DOM que están más relacionados a desarrollo de UIs para webs. Es parte del material que ya enseñamos y que ha demostrado ser útil en esta unidad. Creo que complementan muy bien con lo que ya tenemos que es material más orientado a lógica. Conversemos en más detalle los cambios para que estés 100% onboard. 

He actualizado el checklist arriba para reflejar las cosas que están pendientes por desarrollar y he asignado unos responsables tentativos.

**Comment by ivandevp** [comment]
Hola! Se ha actualizado el branch `03-interactive` con cambios de estructura para que sea parseado correctamente por el **LMS**. Ténganlo en cuenta al momento de lanzar sus PRs :)

**Comment by lupomontero** [comment]
@chamodev, @indie-rok: este issue está asignado al proyecto [01-intro](https://github.com/Laboratoria/curricula-js/projects/4) y al milestone [02-building-an-interactive-site - 2da iteración](https://github.com/Laboratoria/curricula-js/milestone/21). No debería asignarse al proyecto [03-interactive](https://github.com/Laboratoria/curricula-js/projects/9) por un lado y por otro crearse un nuevo milestone para el handoff del curso `03-interactive-site` y cerrar el milestone [02-building-an-interactive-site - 2da iteración](https://github.com/Laboratoria/curricula-js/milestone/21)?

**Comment by chamodev** [comment]
Gracias @lupomontero.

He ajustado el proyecto y el milestone (https://github.com/Laboratoria/curricula-js/milestone/23)

Due Date: **Oct 11** ⚠️

**Comment by ivandevp** [comment]
Se cierra este issue debido a que todas las tareas fueron completadas 💪 

Gracias a todos por sus contribuciones!!! 👏 🎉
