### ISSUE TITLE
Desarrollar contenido 03-interactive-site/02-ux-design

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#122]
- [x] opening
- [x] UX Design vs. UI Design
- [x] Navegation
- [x] Sketching
- [x] quiz 1
- [x] lecture (expandir las instrucciones, agregando preguntas y dando más detalle para los profes)
- [x] ejercicios guiados (expandir las instrucciones, agregando preguntas y dando más detalle para los profes)
- [x] agregar links de material al repo privado
- [x] retos (agregar el link con el producto final del curso + detallar el enunciado + contexto en los indicadores del dashboard y la naturaleza multi-sede y multi-cohort de Laboratoria + criterios de evaluación)
- [x] subir el solucionario del reto al repo privado + guía de corrección
- [x] quiz 2
- [ ] self-assessment @chamo enviar el link
- [x] closing
- [x] solucionarios de ejercicios guiados en el repo privado

**Comment by lalogf** [comment]
- [ ] Reforzar qué es UX y cuál es el equipo desarrollo / incluir videos LD (Lección 1 Intro UXD 1)
- [ ] Intentar hacer preguntas más específicas en el opening. 
- [ ] Preguntas luego del video ux / ui
- [ ] Escribir lección de navegación
- [ ] Detallar el enunciado del caso del data dashboard
- [ ] Agregar agenda al solucionario + presentación de las soluciones

**Comment by chamodev** [comment]
@lalogf: he creado un segundo milestone (iteración 2) para el 31 de Agosto. Apuntemos a tener 100% del contenido desarrollado para ese momento. Thks!

**Comment by chamodev** [comment]
@lalogf: he creado un nuevo branch [`02-interactive-site`](https://github.com/Laboratoria/curricula-js/tree/02-interactive-site/02-interactive-site) para trabajar en este curso de forma independiente al `01-intro` (antes teníamos `intro-js` para ambos cursos).

**Comment by chamodev** [comment]
@lalogf:

He ajustado el proyecto y el milestone (https://github.com/Laboratoria/curricula-js/milestone/24) para este issue. El compromiso con Ops es hacer el hand-off antes de **Oct 11** ⚠️

Porfa avísame si necesitas ayuda.

**Comment by ivandevp** [comment]
Se cierra este issue, queda listo para el hand-off! 💪 

Gracias @lalogf!
