### ISSUE TITLE
Desarollar contenido para `03-data-dashboard`

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#123]
- [x] UX dashboard
- [x] UI dashboard
- [x] Dev dashboard
- [x] Enunciado

**Comment by lupomontero** [comment]
@chamodev: este issue está asignado el milestone [02-building-an-interactive-site - Handoff Ops Team](https://github.com/Laboratoria/curricula-js/milestone/20). Deberíamos de crear un milestone nuevo para el handoff de `03-interactive-site` y mover este issue (y los que sean necesarios) ahí?

**Comment by ivandevp** [comment]
Cierro este PR, se crearán otros específicos para cerrar la solución del producto.
