### ISSUE TITLE
Revisar narrativa de lectura sobre currying en curso 10-functional

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#134]
Ver comentarios en https://github.com/Laboratoria/curricula-js/pull/107#pullrequestreview-57236093

Como referencia para esta lectura (quizás un poco tarde) incluyo link a un video que me encanta de explicación de currying en JavaScript:

https://www.youtube.com/watch?v=iZLP4qOwY8I

cc/ @milmazz

**Comment by milmazz** [comment]
@lupomontero He creado un PR atendiendo las sugerencias dadas. Cualquier comentario como siempre es bienvenido.

BTW, excelentes videos los de _Fun Fun Function_, no lo conocía, gracias por compartir.

**Comment by lupomontero** [comment]
Cerrado en https://github.com/Laboratoria/curricula-js/pull/136
