### ISSUE TITLE
Wrong return en curso 01-Intro lección 03-control-flow ejercicio 03-conditionals-and-loops

### ISSUE THREAD

**Issue by AmaliaRiveraC** [Laboratoria/curricula-js#169]
En el apartado de condicionales, en "sentencia de if .. else " el ejemplo tiene un pequeño error en el return que regresa "Hola Michelle" cuando debería de regresar "Hola Ana", considerando que length de Ana es 3.

**Comment by AmaliaRiveraC** [comment]
Se solicito pull request

**Comment by chamodev** [comment]
¡Excelente @AmaliaRiveraC! El PR lo mandaste a master. Mejor mánda el cambio al branch 101-intro` porfa :)

**Comment by chamodev** [comment]
Listo. Aprobado el PR con este cambio.
