### ISSUE TITLE
Error ejemplo if, curso 01-Intro, lección 03-control-flow, ejercicio 05-functions

### ISSUE THREAD

**Issue by AmaliaRiveraC** [Laboratoria/curricula-js#173]
En la última parte de la lectura: "Utilizando múltiples return en lugar de if...else" en el ejemplo que da, la descripción dice que "las puntuaciones entre 3 y 7 son de plata" pero este segundo if en la función no incluye el 7:  'if (score < 7) { return "Silver" }' y este mismo ejemplo viene como pregunta en el quiz-1.

**Comment by AmaliaRiveraC** [comment]
Se solicitó pull request

**Comment by chamodev** [comment]
PR https://github.com/Laboratoria/curricula-js/pull/176 aprobado.
