### ISSUE TITLE
Link roto curso 01-Intro, lección 03-control-flow, ejercicio 09-code-challanges

### ISSUE THREAD

**Issue by AmaliaRiveraC** [Laboratoria/curricula-js#185]
Link roto de los retos de repl.it: el código de error es 

> We encountered an internal error. Our engineers were notified and we will have a fix for this soon

**Comment by chamodev** [comment]
Gracias @AmaliaRiveraC.

@diegovelezg: porfa nos puedes dar una mano con esto?

**Comment by chamodev** [comment]
A mi me funciona el link...

@danielasarzosa: ¿pueden revisar si tenemos este problema en alguna otra sede?

**Comment by chamodev** [comment]
@danielasarzosa y @diegovelezg: resuelto este tema. El link roto estaba en `master`. Sin embargo, en `01-intro` y en `gitbookPreadmisión` está OK.
