### ISSUE TITLE
11-react: detallar "producto/proyecto" del curso

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#193]
Ahora que ya hay una idea clara del contenido que se va a cubrir nos falta empezar a detallar el producto que las chicas deben construir durante el curso (a parte de los ejercicios).

Por ahora la descripción que tenemos es:

> SPA de cero usando `React`/`Redux`/`Webpack`/`Babel` y desplegado en GitHub pages. Sin rutas, sin remoto, sin persistencia.

**Comment by merunga** [comment]
@lupomontero a ver que te parece

- Single page app
- Sin rutas
- Sin persistencia
- Sin conexiones remotas
- Construido con webpack y babel
- Despeglado en Github pages
- Utilizando React y Redux
- Con por lo menos 10 componentes que especifiquen todas sus props, 3 reducers no atomicos (JSON) y 3 actions

Posibles ejemplos:
- [todomvc](https://github.com/reactjs/redux/tree/master/examples/todomvc)
PROS: Un clasico
CONS: Quizas un poco simple de mas

- [tetris](https://github.com/slugo/redux-tetris)
PROS: Super interactivo
CONS: No hay mucho contenido afianzar los conocimientos sobre React

- [pokedex](https://github.com/davidchang/redux-pokedex)
PROS: Caso similar a la vida real
CONS: Muy simple

- [solitario 1](https://github.com/gcedo/react-solitaire) o [solitario 2](https://github.com/pl12133/react-solitaire)
PROS: Bien interactivos con muchos componentes
CONS: Uso de librerias externas

**Comment by lupomontero** [comment]
@merunga: la especificación me parece bien. He actualizado el readme con una descripción basada en este issue. Con respecto a los ejemplos o productos modelo, cómo lo plantearías exactamente? Usaríamos simplemente una descripción del producto o les daríamos productos de ejemplo ya hechos en los que basar nuevas propuestas?

**Comment by merunga** [comment]
@lupomontero creo q deberiamos elegir uno de esos ejemplos (u otro q decidamos), forkearlo y refactorizarlo (si es necesario) y lo entregariamos como inspiración, ademas de la especificacion. Que dices?

**Comment by lupomontero** [comment]
@merunga: Me parece bien. Yo elegiría una "variación" del Todo MVC para forkear/refactorizar ASAP y tenerlo como implementación modelo. Por otro lado, sí me parece chévere que las chicas puedan elegir entre varias "opciones" o incluso proponer la suya.

**Comment by merunga** [comment]
@lupomontero yo habia pensado que estos proyectos se presenten como inspiracion, pero que todos los trabajos deberían ser originales o inspirados en otros con variaciones.
Faltaria definir las dinamicas de trabajo en grupo, 2-3 personas es lo q hablamos la ultima vez.

**Comment by lupomontero** [comment]
La descripción general del producto acá:
https://github.com/Laboratoria/curricula-js/tree/11-react/11-react#producto

Más detalles en los textos del workshop _Kickstart_:

* https://github.com/Laboratoria/curricula-js/blob/11-react/11-react/02-workshop/00-opening/README.md
* https://github.com/Laboratoria/curricula-js/blob/11-react/11-react/02-workshop/01-teams/README.md
* https://github.com/Laboratoria/curricula-js/tree/11-react/11-react/02-workshop/02-product
* https://github.com/Laboratoria/curricula-js/tree/11-react/11-react/02-workshop/03-tasks

Cierro el issue por ahora pero se agradecen sugerencias, comentarios, fixes...
