### ISSUE TITLE
Ops Team feedback: `programación básica`

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#200]
Aquí podemos ir recopilando el feedback del equipo de operaciones sobre el curso: [`02a-basic-programming`](https://github.com/Laboratoria/curricula-js/tree/02-interactive-site/02a-basic-programming)

Cambios a realizar:

- [x] crear contenido de las lecciones de HSE @alejandrarv 
- [x] crear contenido de la lección de `Sprint Demo` @alejandrarv 
- [x] definir estructura/flow final para la unidad `welcome` @alejandrarv 
- [x] Quiz 1: pregunta 19 faltante
- [x] agregar ejercicio de reservas con `prompt` y `alert` @aocsa 
- [x] subir cambios de HSE, Sprint Demo y Welcome a repo @chamo 
- [x] solo restrospectiva en el lesson final @chamo
- [x] crear y linkear las encuestas de fin de sprint (end-of-sprint + teamwork) @alejandrarv
- [x] actualizar self-assessments @alejandrarv (@chamo dar acceso de edición)
- [x] agregar una tabla de comandos más comunes de git @RuthSalvador 
- [x] hacer cambios para que el "parser" pueda subir el contenido al nuevo LMS @chamo
- [x] nombres largos
- [x] subir quiz 1 @RuthSalvador 
- [x] subir requiz @RuthSalvador 
- [x] agregar requerimientos de README.md, pseudocódigo y diagrama de flujo a productos finales
- [x] @michellesegv ultimo cambio en lectura de cli
- [x] subir rúbrica de corrección de retos finales (TCV y CC)
- [x] traducir los retos de código de Replit a español y tenerlos en formato del nuevo LMS ver: #227 (pendiente: cambios de alex y ortografía de Joe)

**Comment by nerdale** [comment]
Hola Team,
En el **Quiz 1: Programación básica en JavaScript** la pregunta número 19, sale como última opción **Opción 4** y no tiene respuesta correcta.
Las demás opciones están todas bien y sale todo en la lección, salvo lo de auto-aprendizaje que deben averiguarlos por si solas.

**Comment by nerdale** [comment]
De nada @chamodev ! En el **Re-Quiz: Programación básica en JavaScript** la pregunta número 15 está incompleta y no tiene respuesta correcta, las demás preguntas todas ok y concordantes con la lección.

**Comment by RuthSalvador** [comment]
Hola! Muchas gracias :) les comento que he completado esas preguntas con el tema de `cli`. Agradecería mucho que las puedan ver:
pregunta nro19 del quiz y nro 15 del requiz.

**Comment by RuthSalvador** [comment]
Hola! Muchas gracias @chamodev y @nerdale :) les comento que he completado esas preguntas con el tema de `cli`. Agradecería mucho que las puedan ver:
pregunta nro19 del quiz y nro 15 del requiz.

**Comment by nerdale** [comment]
@RuthSalvador Revisé ambos quizzes, están ok :)

**Comment by FabianBravoA** [comment]
Dejaré este issue también acá, me equivoqué al dejarlo fuera como issue independiente :

https://github.com/Laboratoria/curricula-js/issues/209

**Comment by chamodev** [comment]
@Laboratoria/education-team: todas las tareas han sido completadas 🎉  🎉 . Queda cerrado el issue. En breve recibirán una invitación al nuevo Capitán (LMS) para que vean el producto final 😄
