### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by jaiment** [Laboratoria/curricula-js#202]
En los temas de seguridad creo que es importante ver JSON Web Token.

- https://jwt.io/
- https://medium.com/vandium-software/5-easy-steps-to-understanding-json-web-tokens-jwt-1164c0adfcec

Saludos!

**Comment by sebastianmorenoe** [comment]
Muy imprortante, sobre todo si las apps que están haciendo van a ser de tipo SPA y si en algún futuro las chicas van a ver algo de backend para entender como funciona la autenticación stateless y de que manera se realizan las consultas a la API de manera segura.

Además de los beneficios de utilizar JWT para aplicaciones en la nube que necesitan escalar de forma horizontal y no pueden almacenar un estado.

Habría que evaluar si podría ser una introducción en este curso y tal vez profundizarlo en un curso de backend o fullstack.

**Comment by AnaSalazar** [comment]
@lupomontero Algún comentario sobre esto, lo podemos dar por cerrado???

**Comment by lupomontero** [comment]
Gracias a todxs por los comentarios y disculpen por la demora en contestar... :see_no_evil: 

Por el momento, este tema se cubre un poquito (muy por encima) en este proyecto: https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/05-bq-node

Quizás se animen a revisar el proyecto y sugerir algo en particular. Siempre estamos abiertos a contribuciones :wink: 

Cierro este issue por _inactividad_ pero no duden en abrir uno nuevo para continuar la conversación pero esta vez en concreto sobre el proyecto mencionado.
