### ISSUE TITLE
Contenido de terminal - Otros sistemas operativos

### ISSUE THREAD

**Issue by FabianBravoA** [Laboratoria/curricula-js#209]
[curricula-js/02a-basic-programming/01-basic-programming](https://github.com/Laboratoria/curricula-js/tree/02-interactive-site/02a-basic-programming/01-basic-programming)

Solo tiene windows, debería tener también los comandos para sistemas operativos "unix-like" como MacOS y Ubuntu.

**Comment by lupomontero** [comment]
Hola @FabianBravoA, gracias por el feedback 👍

Totalmente de acuerdo. De hecho, lo ideal sería que las chicas trabajen en un entorno _unix-like_ por defecto, no?

@ivandevp, @chamodev, @MichelleSV: Qué opinan?

**Comment by chamodev** [comment]
Yo estoy de acuerdo. 

Solo que necesitamos acordar si (y cómo) vamos a brindarles el entorno antes del primer día de clases. Creo que los lead teachers y las TMs en cada sede deben coordinar eso. En cualquier caso, @michellesegv: ¿puedes porfa agregar como lectura complementaria el contenido para otros OS? Así no tengan el entorno, debería quedar el material como parte de nuestro contenido.

cc: @FabianBravoA @joalbertg @aocsa @indie-rok

**Comment by ivandevp** [comment]
@FabianBravoA: @michellesegv agregará una lectura sobre el mismo tema para entornos _unix-like_. 

@lupomontero todas comenzarán a usar comandos de terminal de entornos _unix-like_ a partir de que vean `git` aun así se encuentren en Windows, ya que tendrán `Git Bash` que emula dichos comandos.

cc/ @chamodev

**Comment by lupomontero** [comment]
Listo, entonces queda pendiente que @michellesegv añada la lectura correspondiente ;-)

Cerramos este issue?

cc/ @chamodev @ivandevp

**Comment by michellesegv** [comment]
Hola @FabianBravoA , muchas gracias por tu comentario. Acabo de añadir a la lección los comandos para los OS Linux y Mac OS X.

**Comment by chamodev** [comment]
¡Gracias @michellesegv y @FabianBravoA! 

Cerramos este issue entonces con el PR aprobado :)

Si tenemos más comentarios lo podemos hacer en: https://github.com/Laboratoria/curricula-js/issues/200
