### ISSUE TITLE
Propuesta - Presentaciones en latex

### ISSUE THREAD

**Issue by FabianBravoA** [Laboratoria/curricula-js#210]
Para poder presentar las clases a las alumnas, lo mejor son las presentaciones. Ahora bien, PowerPoint tiene el problema de que es muy complicado colaborar usando sus archivos y GIT, además de que pegar código es prácticamente imposible, a menos que sea en forma de imagen, impidiendo el copiar y pegar si es que se comparte con las alumnas el material.
Propongo hacer las presentaciones con Latex, un procesador de texto WYMIWYG (http://acronyms.thefreedictionary.com/WYMIWYG) que se tiene que compilar para obtener el documento/presentación. La principal ventaja es que usa texto plano (archivos .tex) y que permite agregar código fuente de manera fácil y con colores personalizados.

Propuesta : https://github.com/FabianBravoA/curricula-js/commit/80c78075a4e2563c00c3af5b44bd6fd553215c96

**Comment by chamodev** [comment]
¡Gracias @FabianBravoA! Me parece bien interesante. Creo que el reto sería alrededor del proceso de actualización de ese contenido. Es decir, cuando se genera un cambio en el repo, ¿cómo garantizamos que se refleje en los slides? 

@lupomontero: ¿qué opinas? ¿alguna consideración del parser con esto? 

cc: @ivandevp @Laboratoria/education-team

**Comment by lupomontero** [comment]
Hola @FabianBravoA, gracias por la sugerencia 👍 

Por el momento las presentaciones de slides las maneja cada "instructor" o "creador" como más le acomode. Existe una propuesta hace tiempo para añadir soporte para slides generados a partir de Markdown, que es el formato base que estamos obligando a todxs a aprender 😉 

LaTeX es una tecnología muy potente y madura (precede a la web) pero en mi experiencia nunca ha tenido mucha aceptación y podría añadir un nivel de complejidad que puede asustar a los non-devs.

Yo propondría que por ahora las presentaciones se creen fuera del repo, cada unx usando la herramienta que prefiera, y después se pueden incluir los slides como imágenes y/o pdf descargable. Más adelante, si aparecen nuevos requests por este feature, podemos decidir una convención/implementación para manejar láminas/slides, desde la creación hasta el LMS.

Thoughts?

cc/ @chamodev @ivandevp

**Comment by aocsa** [comment]
Hola Equipo,

También antes considere la posibilidad de usar latex. Por experiencia ensenhando latex si se puede hacer difícil de usar para alguien no-dev. La opción de mark-down me para la mas viable. 

Sito este tipo de característica de rstudio por ejemplo:

[slides rstudio](http://rmarkdown.rstudio.com/lesson-11.html)
[ios_slides rstudio](http://rmarkdown.rstudio.com/ioslides_presentation_format.html
)
Escribes en markdown (y todas sus posibilidades incluyendo formulas matemáticas al estilo latex y códigos en playground) y tienes la posibilidad de exportar tu trabajo en PDF o en HTML con ioslides o  reveal.js.  

[Reveal.js demo](http://lab.hakim.se/reveal-js/#/7/1
)

Saludos

**Comment by lupomontero** [comment]
Cierro este issue ya que no es aplicable en el corto plazo.
