### ISSUE TITLE
Bienvenida a nuevos colaboradores

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#22]
Hola tod@s,

Abro este issue para presentarles a los nuevos "colaboradores externos" (👽) a quienes estamos invitando al repo. Por ahora he añadido a:

* @merunga (Mariano Crowe 🇦🇷 ): va a estar desarrollando el curso de intro a react
* @nandodrw (Fernando Catacora 🇵🇪 ): vamos a explorar posibilidades de colaboración; hay que identificar un curso que le pueda interesar y que necesitemos cubrir
* @eporroa (Erik Porroa 🇵🇪 ): lo mismo que @nandodrw
* @dochoaj (Daniel Ochoa John 🇨🇱 ): lo mismo que @nandodrw

Podrían contarnos un poquito (a todo el equipo) sobre ustedes: experiencia, expertise, intereses, ...? Así podremos ir conociéndonos y ver en qué temas o cursos se podrían involucrar.

Como verán, este repo es "work in progress" ⚠️ , así que tengan en cuenta que todavía no es una propuesta totalmente formada, sino un boceto que entre todos iremos transformando en nuestra malla curricular 🤓 

En este momento, nuestra prioridad es desarrollar contenido para nuestro programa de Educación Continua. Como punto de partida, les recomiendo leer lo siguiente:

* https://github.com/Laboratoria/curricula-js/blob/master/README.md
* https://github.com/Laboratoria/curricula-js/blob/master/CONTRIBUTING.md
* https://github.com/Laboratoria/curricula-js/issues/3

En las próximas horas/días estaremos añadiendo propuestas de cursos donde necesitamos ayuda. Los mantengo informados por acá :octocat: 

Bienvenidos!! 🎉 🎈 

L

cc/ @chamodev @ivandevp @CaroLaboratoria

**Comment by chamodev** [comment]
Bienvenido @arcuellar88!!!

Alejandro estará trabajando de la mano de @MariPlaza en el curso de visualización de datos y en lo que podría ser el track de data analytics.

 @arcuellar88: para familiarizarte con este lee lo siguiente:

- https://github.com/Laboratoria/curricula-js/blob/master/README.md
- https://github.com/Laboratoria/curricula-js/blob/master/CONTRIBUTING.md
- #3

Gracias!
R

**Comment by lupomontero** [comment]
Bienvenido @arcuellar88 🎉

**Comment by arcuellar88** [comment]
Gracias @chamodev y @lupomontero! 

Hola todos,

Soy Alejandro Rodriguez y trabajo como consultor de Inteligencia de Negocios. Después de trabajar y estudiar durante 4 años en varios países he decidido volver a Colombia y estoy buscando proyectos con un alto impacto social. 
Conocí a una practicante de Laboratoria cuando trabajé en el Banco Interamericano de Desarrollo en Washington y me gustó mucho el proyecto. Espero poder aportar todo mi conocimiento al track de data analytics!

Gracias por la bienvenida. 

Alejandro

**Comment by kjsanc** [comment]
Hola a todos,

Mi nombre es Kevin Sánchez, cuento con estudios superiores y experiencia en proyectos tanto del sector público como del sector privado, nacionales y extranjeros. Me he desempeñado como jefe del área de sistemas de una aerolínea local, participando en el desarrollo y la implementación de soluciones biométricas, dispositivos POS, aplicaciones y servicios web, empleando principalmente tecnologías open source.

Actualmente trabajo de manera independiente y estoy planeando incursionar en otras áreas de la ingeniería, como por ejemplo la Mecatrónica, llevando a cabo mi propio emprendimiento.
Me siento entusiasmado de poder colaborar en  proyectos de responsabilidad social, especialmente en la capacitación de los recursos humanos, porque los considero uno de los pilares del desarrollo regional.

Muchas Gracias.

**Comment by lupomontero** [comment]
Cerramos este issue por ahora como parte de _house keeping_. Futurxs colaboradorxs se irán presentando en nuevos _issues.
