### ISSUE TITLE
Code-Challenges para : `02a-basic-programming/01-basic-programming` 

### ISSUE THREAD

**Issue by developerVilchez** [Laboratoria/curricula-js#227]
Según la reunión de hoy queda la distribución de ejercicios de replit para su traducción, resolución y desarrollo de pruebas unitarias para la implementación en el lms del bootcamp.

COLABORADORES:
@chamodev: Crear la carpeta raíz ejercicios.
- [x] Crear carpeta raíz para code-challenges.

@aocsa : Lista de ejercicios replit (Enunciado español -  solución -  unit test) 
- [x] 01-computeAverageLengthOfWords
- [x] 02-addArrayProperty 
- [x] 03-getNthElement
- [x] 04-removeStringValuesLongerThan
- [x] 05-convertDoubleSpaceToSingle
- [x] 06-areValidCredentials
- [x] 07-getElementOfArrayProperty
- [x] 08-findPairForSum
- [x] 09-greetCustomer
- [x] 10-filterOddElements
- [x] 11-findShortestWordAmongMixedElements
- [x] 12-findSmallestnumberAmongMixedElements
- [x] 13-getLongestWordOfMixedElements
- [x] 14-getLargestNumberAmongMixedElements
- [x] 15-computeSumOfAllElements

 @joalbertg  Lista de ejercicios replit (Enunciado español -  solución -  unit test) 
- [x] 16-Array to Object[Part 1]
- [x] 17-Array to Object[Part 2]
- [x] 18-Array to Object[Part 3]
- [x] 19-Object to Array [Part 1]
- [x] 20-Object to Array [Part 2]
- [x] 21-Object to Array [Part 3]
- [x] 22-computeSumBetween
- [x] 23-getLongestOfThreeWords
- [x] 24-findShortestOfThreeWords
- [x] 25-calculateBillTotal
- [x] 26-convertScoreToGrade
- [x] 27-getProductOfAllElementsAtProperty
- [x] 28-getProductOfAllElementsAtProperty
- [x] 29-addObjectProperty
- [x] 30-addFullNameProperty

Así mismo, indico el link en donde se encuentra la estructura de carpetas para un ejercicio. Recordar que esta es la estructura necesaria para implementarlo en el lms

[link ejemplo - estructura de carpetas](https://github.com/Laboratoria/curricula-js/tree/10-functional/10-functional/01-state/02-practice/01-discount)

- Archivo Readme  --> Enunciado del ejercicio
- Carpeta boilerplate --> Archivo .js con el código base a utilizar
- Carpeta  solution -->  Archivo.js con la solución del ejercicio
- Carpeta test --->  Archivo .js con las pruebas unitarias

Me avisan por este medio para ir actualizando los check list.
Gracias!!

**Comment by chamodev** [comment]
gracias @developerVilchez!!

**Comment by developerVilchez** [comment]
@joalbertg , @aocsa  estoy agregando la numeración de los ejercicios que son los mismos que se indicarán  en la estructura de carpetas para su correcto despliegue en el lms.
@joalbertg  no te olvides de coordinar con @aocsa  de los puntos a tener en cuenta en la estructura de carpetas y refactorización según el feedback de @lupomontero.

Me avisan por este medio para ir actualizando los check list.
Gracias!!

**Comment by aocsa** [comment]
Pienso que  seria bueno que @lupomontero valide estos ejercicios generando los contenidos en el nuevo lms para continuar con seguridad la carga de los ademas ejercicios.

Saludos

**Comment by chamodev** [comment]
tareas completadas! cierro el issue :)

Gracias a todxs!
