### ISSUE TITLE
Propuesta para curso JS Deep Dive

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#23]
Por el momento el programa de Educación Continua empieza con un curso que hemos llamado temporalmente **JS Deep Dive**, que estamos de alguna forma heredando de la ejecución de EC en Lima ahorita.

Viendo el flujo de la malla en general se me ocurre que parte de lo que ahorita se está cubriendo debería haberse cubierto ya en el bootcamp, por lo menos en el nuevo modelo. En el mundo real, ahora tenemos chicas que no vieron prácticamente nada de JS en el bootcamp.

Teniendo esto en cuenta, y sabiendo que @jpcode está con ganas y pronto tiempo, les propongo que le demos una repensada. De hecho me gustaría pedirle a @jpcode que piense qué podría encajar mejor al principio de EC, y que haga una propuesta de curso para transformar o reemplazar el "placeholder" de _JS Deep Dive_. Creo que es quien está en mejor posición para hacerlo ya que tiene la experiencia de haber hecho la primera iteración en vivo! @jpcode te animas a hacer una propuesta? Si es así, el primer paso sería crear un branch (o hacer un fork), crear una copia de [la plantilla](https://github.com/Laboratoria/curricula-js/tree/master/00-template), llenarla, salvarla en un directorio con nombre `08-deep-dive` y mandar un PR. De ahí vamos rebotando ideas.

Thoughts?

cc/ @chamodev @ivandevp

**Comment by lupomontero** [comment]
@jpcode alguna novedad con respecto a esta propuesta?

**Comment by brecabal** [comment]
Hola soy Belén Recabal @brecabal , profesora de bootcamp Chile , y me gustaría poder aportar en este curso, dado que conozco de cerca el nivel de las alumnas y la malla que desarrrollamos.
@lupomontero @ivandevp estoy dispuesta a participar del diseño de este curso, espero los pasos a seguir . Saludos :)

**Comment by lupomontero** [comment]
hola @jpcode, gracias por la propuesta 💪 

... pero me temo que como no tuvimos respuesta en un mes, y necesitábamos resolver este tema, se buscaron alternativas... 😟  Así que conversamos con @brecabal (de Laboratoria en Chile), quien ha mostrado interés (🎉) , para que hiciera una propuesta. Belén está preparando una propuesta para la semana que viene y ya tiene tiempo asignado para chambear en esto.

De todas formas se agrade el feedback 😃 

cc/ @CaroLaboratoria

**Comment by jpcode** [comment]
Hola @lupomontero , genial. Igual estaré dando feedback a la medida posible.

**Comment by lupomontero** [comment]
Cierro este issue en favor de ir abriendo issues más concretos dentro del contexto del [proyecto 08-deep-dive](https://github.com/Laboratoria/curricula-js/projects/6) ahora que el curso ya está siendo desarrollado 😸
