### ISSUE TITLE
Mapa de conceptos, tecnologías y herramientas

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#25]
Necesitamos desarrollar una primera versión de nuestro _mapa_ de conceptos, tecnologías y herramientas. Es esencial que compartamos un mapa mental de las diferentes piezas del puzzle, que en nuestro caso no necesariamente coinciden con la ruta lineal de cursos de los programas del bootcamp y EC.

Cómo referencia, en este blog post hay un buen par de ejemplos, un mapa de front-end y otro de back-end:

https://blog.hellojs.org/web-development-how-to-start-in-2017-b2357febe8ba

**Comment by ivandevp** [comment]
Sería bueno tal vez considerar temas como:

- Patrones de diseño
- Seguridad
- Performance

**Comment by lupomontero** [comment]
* He separado Álgebra, Estadística y Geometría como sugirió @indie-rok
* He añadido Realtime y WebOps como sugirió @chamodev 
* He añadido Patrones de diseño, Seguridad y Performance como sugirió @ivandevp 
* He añadido el mapa en el [`README.md`](https://github.com/Laboratoria/curricula-js/blob/master/README.md) principal del repo

![mapa de topicos](https://user-images.githubusercontent.com/110297/27301108-c25bf836-54f7-11e7-9ce0-3346ff435926.png)

**Comment by lupomontero** [comment]
La primera iteración del mapa se considera completa. No duden en crear nuevos issues para cualquier sugerencia comentario.
