### ISSUE TITLE
Curso: `Creando tu propia red social` - Estructura

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#252]
A continuación se detalla la estructura para el desarrollo de este curso:

`00-web-layouts`:

* Responsive Web Design
  * Layout & Grid System
  * Media Queries
* Framework CSS
  * Bootstrap (enfocado)
  * Materialize (otra alternativa)
  * Componentes (necesidad de jQuery)
* jQuery
  * Selectores
  * DOM

`01-improve-usability`:

* UX
  * Heurística
  * ...

* Widgets & Plugins
  * Uploadcare, Filestack y/u otro
  * Plugin de jQuery - (búsqueda autocompletable y/u otro)

* Optimización de experiencia de usuario
  * Lazy loading
  * Infinite scrolling

* Firebase (guiado)
  * API
  * Autenticación
  * Base de datos

cc/ @chamodev @lalogf

**Comment by lalogf** [comment]
Los contenidos de UX son: 
 - Usabilidad
 - Visual Design 101

**Comment by giancorzo** [comment]
Estuve conversando con @ivandevp sobre este issue y quizá les puede servir el ejercicio que hice hace un tiempo para la gente que postula a Laboratoria.  Se que ellas tienen que inventar su propia red social pero quizá alguno de los lineamientos técnicos les pueden servir.

https://docs.google.com/presentation/d/1A45l80FL9Tcgonh8Ba6SbfyPyL-zCXzZwPNUzcps5ts/edit#slide=id.g1dad1e6d37_0_0

**Comment by brecabal** [comment]
Hola @ivandevp con respecto al orden de la unidad 01, queremos proponer el siguiente orden:
Layout -Grid System
Media Queries
Responsive Web design
Creemos que es mejor que primero manejen Grid y luego puedan entender como ayudan las medias queries a ajustar los distintos tamaños, para al final crear una responsive web design.

**Comment by ivandevp** [comment]
Genial @brecabal! Gracias por el feedback, lo voy a arreglar en la [descripción del curso](https://github.com/Laboratoria/curricula-js/tree/04-social-network/04-social-network).

**Comment by RuthSalvador** [comment]
Hola!! @ivandevp con respecto a la prioridad en el caso de los Frameworks CSS, si bien es cierto Materialize está más detallado y se siente que es más "sencillo", creo que deberíamos enfocarnos en Bootstrap como primera alternativa porque es lo que más se usa. Y sería Materialize como segunda opción.
Grac

**Comment by RuthSalvador** [comment]
Hola @ivandevp creo que deberíamos tener un taller y/o mención de Git, en el caso de los branch y las colaboraciones, sería bueno que sea al inicio del sprint. 
En Lima les enseñamos gh-pages para que muestren sus proyectos, sin embargo el tema de branch no se ha visto mucho. Con mención me refiero a darle los links de buena información sobre git.

**Comment by brecabal** [comment]
1- Con respecto al uso de frameworks, lo que hicimos el bootcamp pasado fue enseñar bootstrap como primero, pero fue abierta la elección de su framework favorito, al final la idea es enseñar cómo usar un framework, más que, qué framework usar.

2- Con respecto a Git a mi me parece super, me gustaría incluirlo, pero por temas de tiempo y cantidad de materia del Sprint 3, siempre para las alumnas es más confuso, se estresan con git, creo que sería super si como primer tema en la especialización comenzaramos con eso y no ahora porque se estresan aprendiendo muchas cosas nuevas en tan poco tiempo.


cc/ @ivandevp @RuthSalvador

**Comment by nerdale** [comment]
Hola! @ivandevp @RuthSalvador 
Lo que dice @brecabal sobre el uso de frameworks en el bootcamp anterior nos funcionó demasiado bien, tomamos como base Bootstrap que es uno de los más utilizados en el mercado actualmente, pero eso dio pie a que las chicas también se les hiciera muy natural y rápido aprender a manejar cualquier framework como materialize, foundation y cualquier otro que se les presentara.
Aprovecho de dejar una inquietud, ¿no sería interesante agregar algo de flexbox también?

**Comment by FabianBravoA** [comment]
Holo @ivandevp ,
La parte bonus está sub-dimensionada, he usado esas tecnologías y para un programador con experiencia ya es como 1 día de internarse en firebase en general. Para las alumnas recomiendo que al menos sea una semana y por lo tanto esto debería quedarse para especialización u otro sprint.
El hacerlo en menos de una hora solo generará confusión en mi opinión. Y ya el sprint está cargado de materia como para hacerlo más complejo.
Quizá es en este punto que de "bonus" pasemos GIT un poco más complejo (branching por ejemplo y para qué sirve)

**Comment by FabianBravoA** [comment]
Holo @ivandevp ,
También sobre carga perezosa y listas infinitas, ¿cuál es la idea? ¿hay alguna biblioteca que están pensando en enseñar? porque en términos de programación pura, de alguien que sabe son del orden de días que toma programar de buena forma estas técnicas. Enseñar el cómo funcionan puede que sea más acotado, pero de todas formas puede que tome bastante tiempo el que las alumnas las dominen al nivel de que sean capaces de programarlo por su cuenta.
Esto lo digo porque me ha tocado programar ambas técnicas varias veces en varios lenguajes de programación y plataformas (tengo experiencia en videojuegos principalmente).

**Comment by ivandevp** [comment]
Gracias por sus comentarios @RuthSalvador @brecabal @nerdale @FabianBravoA!

1. Ya cambié el enfoque en los frameworks CSS en base a su sugerencia fundamentada. (:arrow_up:)

2. Respecto a Firebase, está orientado al producto, la funcionalidad que se espera algunas estudiantes puedan aplicar, es la de autenticación, base de datos y en el mejor de los casos storage. La intención es hacerlo guiado, sin necesidad de una clase, solo como un self-learning que sería bueno lo puedan aplicar en su producto final.

3. Respecto a las técnicas de lazy loading e infinite scrolling, la intención es que al ya estar algo familiarizadas con jQuery, vean que tienen **plugins** que le pueden ayudar a mejor la experiencia en sus web apps. De tal forma que terminen aplicando algo como esto:

- https://github.com/eisbehr-/jquery.lazy
- O algunos de estos: https://www.sitepoint.com/jquery-infinite-scrolling-demos/

4. Respecto a profundizar en GIT, aun tengo dudas si debería ser parte del common core, debido a la cantidad de temas y que ambos perfiles están juntos. ¿Tienen más fundamentos?

En conclusión, para dejar claro el enfoque de este 4to curso, la idea es que en el 3ro ya vieron muchos conceptos, en este curso la intención es que vean un poco más de herramientas y que teniendo en cuenta los conceptos aprendidos, pueden hacer cosas interesantes sin necesariamente entender todo lo que codean (de paso, que vayan teniendo más ideas para su portafolio :smiley:).

**Comment by RuthSalvador** [comment]
hola @ivandevp quisiera saber si van a agregar flexbox en este sprint

**Comment by AnaSalazar** [comment]
Este issue se cierra ya que se ha finalizado esta unidad y ninguna de las sedes está usando este contenido actualmente.

Para las futuras mejoras e iteraciones de este contenido se crearán nuevos issues en su debido momento.
