### ISSUE TITLE
Ops Team Feedback: 03-interactive-site/00-html-css

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#268]
- [x] quiz 1 (@shirley-suarez)
- [x] quiz 2 (@shirley-suarez)
- [x] Fix numeración del README
- [x] **IDEA**: pasar algunos ejercicios guiados al seminario (aprobado, solución en el feedback)
- [x] self-assessment @alejandrarv @chamo
- [x] solucionarios subidos al repo de solutions @ivandevp

**Comment by bosqueinvierno** [comment]
Hola Team,
Leímos el **Requiz** de **HTML y CSS** con **@MarciaMillanao**, y notamos que existen algunos problemas con las preguntas 16 y 17.

La pregunta 16 está mal redactada, donde dice **"Según el siguiente código, ¿cuál sería el resultado en el navegador?"** debería decir algo como **"Según la siguiente imagen, ¿cuál sería el código que corresponde?"**. Además, el código de las respuestas es específico solo a un elemento de la imagen y quizás se podría añadir algo más de información (contexto) para que no sea tan confuso para las alumnas.

La pregunta 17 necesita más información (contexto) en el código en el que se basa la pregunta, ya que se muestra un solo elemento pero en la respuesta que se supone que es la correcta (opción 2) hace alusión a otros elementos, sin especificar si son en bloque o inline, si están al lado, arriba o debajo del elemento del ejemplo. Además, la respuesta que se supone que es correcta no lo está, ya que por ejemplo, asumiendo que hay otros dos elementos a su lado (siendo inline los tres elementos), el elemento con el margin-left negativo se superpone a los otros hacia la izquierda y no los mueve. Si los elementos anteriores están en bloque, no los afecta y el elemento que posee el margin se mueve hacia la izquierda él solo.
Dependiendo de como queramos reconstruir esa pregunta, la respuesta correcta sería la opción 1 (que solo el elemento se mueve 5px a la izquierda).

**Comment by RuthSalvador** [comment]
Hola @chamodev, 
@Gabx04 y yo hemos visto algunos detalles, en el caso de los quizzes:

QUIZ: 
**Preg 2** en la lectura no se especifica esto.
**Preg 3** La respuesta no es correcta, la única correcta es la alterativa 3
**Preg 5** La lectura no menciona nada acerca de la alternativa 2, la cual es parte de las rptas correctas
**Preg 13** se debe corregir el link por `main.css`, no están bien indentadas
**Preg 16** las alternativas no están bien indentadas, los colores deben estar en nombre no es hexagesimal, `id=ping`, debería ser `id=pink`

REQUIZ:
**Preg 15** hay un error en la alternativa 1, no existe center como propiedad de position
**Preg 16** no están bien indentadas, mejorar  redacción
**Preg 17** igual que la opinión de arriba, mejorar  redacción y sería la rpta 1

Gracias :)

**Comment by ivandevp** [comment]
**Feedback:**

- [ ] Adaptar seminarios y ejercicios entre lecturas de `self-learning` @ivandevp
- [ ] Autoevaluaciones en el LMS @alejandrarv 
- [ ] Cambiar tablero de ejercicio de Pinterest @ivandevp
- [ ] Box model, cambiar imagen que explica el borde @IntiDev 
- [ ] Tipografías, agregar tutorial de Google Fonts @IntiDev

**Comment by chamodev** [comment]
Hola team: he asociado este issue con el milestone: https://github.com/Laboratoria/curricula-js/milestone/22. Due date: **Oct 6** ⚠️

**Comment by ivandevp** [comment]
Pendientes para desplegar contenido en LMS:

- [ ] Agregar ejercicio de `float` para seminario @ivandevp
- [ ] Agregar link de autoevaluación de Chile @alejandrarv @ivandevp
- [ ] Agregar contenido de HSE @alejandrarv

**Comment by ivandevp** [comment]
Se cierra este issue ya que todas las tareas fueron completadas, cualquier acotación particular crear un issue o mandar un PR 😃 

cc/ @Laboratoria/education-team
