### ISSUE TITLE
Propuesta de estructura para productos de clase

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#287]
Hola! A partir del segundo sprint, se comienza a usar `HTML`, `CSS` y `JS` en conjunto, por lo cual se trabaja con una estructura de productos que incluye diversas carpetas y archivos. Hemos optado por tener un estándar pero que nos gustaría recibir feedback y entre todos llegar a un acuerdo para mantenerlo a través de las clases en todas las sedes. 

El estándar usado hasta el momento es:

```text
nombre-producto
├── assets/
│   ├── fonts/
│   |   └── font.ttf      # ejemplo de fuente
│   ├── icons/
│   |   └── icon.ico      # ejemplo de ícono
│   ├── images/
│   |   └── image.png     # ejemplo de imagen
├── css/
│  └── common.css         # estilos comunes (aplica en productos de más de una vista)
│  └── main.css           # estilos del index.html
│   ├── vendors/
│   |   └── bootstrap.css # ejemplo de CSS externo (aplica en caso de no usar CDNs)
├── js/
│  └── app.js             # archivo JS principal
│   ├── vendors/
│   |   └── jquery.js     # ejemplo de librería JS externa (aplica en caso de no usar CDNs)
├── views/
│  └── home.html          # nombre de otro html (aplica en productos de más de una vista)
└── index.html
```

> Debemos de obviar que tenemos claro que en un producto real (en sus trabajos), no usarían una estructura así, pero para fines didácticos en su inmersión al desarrollo web, sería bueno mantener un estándar 😃 

@Laboratoria/education-team @Laboratoria/developers @Laboratoria/instructores-bootcamp

**Comment by ivandevp** [comment]
@lupomontero algún comentario sobre esto para hacer alguna iteración en los siguientes cohorts?

**Comment by lupomontero** [comment]
@ivandevp, perdona que nunca tuvimos tiempo de ver esto... :cold_sweat: 

Habiendo pasado más de un año, ... me tomo la libertad de cerrar el issue por inactividad.
