### ISSUE TITLE
09-paradigms: migrar ejercicios coi a formato LMS

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#293]
En la primera iteración del curso `09-paradigms` se usaron ejercicios en formato [workshopper](https://github.com/workshopper/workshopper) y ahora tenemos que _migrar_ estos ejercicios a este repo, como parte de la currícula, para que así puedan manejarse adentro del LMS.

La tarea en este issue es _migrar_ los 9 ejercicios de [Composition Over Inheritance](https://github.com/Laboratoria/coi):

- [x] Higher Order Functions
- [x] Map
- [x] Filter
- [x] Reduce
- [x] Funciones flecha (arrow functions)
- [x] Closures
- [x] Object factories
- [x] Object.assign()
- [x] Composición de objetos

Los ejercicios deben _migrarse_ a la carpeta [09-paradigms/06-composition/05-exercises](https://github.com/Laboratoria/curricula-js/tree/09-paradigms/09-paradigms/06-composition/05-exercises) en la rama `09-paradigms`, donde ya se han creado carpetas para cada ejercicio.

Cada ejercicio del workshopper tiene un enunciado (`problem.md`), un _boilerplate_, _tests_ y una _solución_. Esta estructura se mantiene muy parecida en los ejercicios para LMS. El `problem.md` pasa a ser `README.md`, el boilerplate y solución tienen el mismo nombre de archivo, los tests están en un archivo con el mismo nombre pero `.spec.js`... Por [ejemplo](https://github.com/Laboratoria/curricula-js/tree/09-paradigms/09-paradigms/02-paradigms/11-fp-exercise/01-notes):

```
.
├── README.md
├── boilerplate
│   └── notes.js
├── solution
│   └── notes.js
└── test
    └── notes.spec.js
```

Una vez migrados los tests deberíamos poder ejecutarlos con el siguiente comando:

```sh
./node_modules/.bin/mocha 09-paradigms/06-composition/05-exercises/**/*.spec.js
```

**Comment by lupomontero** [comment]
Hola @carlosroec, te he añadido como colaborador en el repo para poder asignarte ese issue. En cuanto aceptes la invitación lo asigno.

Gracias!

**Comment by giancorzo** [comment]
Hola @carlosroec,

**Comment by giancorzo** [comment]
Hola @carlosroec @lupomontero 

Asumo que estás algo complicado con esto, proceso a asignarme el issue. En caso ya esté trabajando sobre esto avísame.

**Comment by lupomontero** [comment]
@giancorzo: dale!

@carlosroec: si puedes colaborar con esto coordina con @giancorzo, porfa.

Gracias a los dos!

**Comment by lupomontero** [comment]
Cerrado en https://github.com/Laboratoria/curricula-js/pull/379
