### ISSUE TITLE
Ops Team Feedback: 03-interactive-site/01-making-your-site-interactive y 03-interactive-site/02-ux-design

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#316]
Pendientes:

- [x] Video de DOM @developerVilchez 
- [x] Ejercicio guiado de captcha @michellesegv 
- [x] self-assessment de México @ivandevp
- [x] Actualización de `README.md` principal de las unidades @ivandevp
- [x] refactorización de soluciones

**Comment by FabianBravoA** [comment]
https://github.com/Laboratoria/curricula-js/tree/03-interactive/03-interactive-site/01-making-your-site-interactive/03-dom-manipulation

Creo que debería especificarse o explicarse mejor el setInterval, no queda claro qué recibe como argumentos, ni que estará en un loop para siempre ni cómo detenerlo, etc. En la lectura queda como algo sacado del sombrero, cuando lo estarán usando en varias instancias.

**Comment by FabianBravoA** [comment]
https://github.com/Laboratoria/curricula-js/tree/03-interactive/03-interactive-site/01-making-your-site-interactive/09-guided-exercises

Ejercicio 1 : No parece de esta unidad, o al menos no está enfocado en la combinación de HTML/Javascript. @nerdale sugiere que un ejercicio mejor enfocado sería el Gato, que si permite el uso intensivo de las herramientas aprendidas en la unidad.

**Comment by ivandevp** [comment]
Muchas gracias por tus comentarios @FabianBravoA. Creen que podrían mandar un PR haciendo una mejor explicación o separando el concepto de `setInterval` en todo caso @FabianBravoA y mientras @nerdale podrías mandar un PR sugiriendo el enunciado del ejercicio en todo caso? Y la solución lo coordinamos por interno?

**Comment by nerdale** [comment]
@ivandevp ningún problema en desarrollar el enunciado del ejercicio gato tic tac toe. Por interno coordinamos la solución.

**Comment by ivandevp** [comment]
**Feedback Ops Team:**

- Mejoras en redacción y mejoras en UX @indie-rok @alejandrarv 
- Cambios de estimación de tiempo @AmaliaRiveraC @LucileBaratier 
- Talleres de HSE @alejandrarv 
- Tiempos de contenido no técnico @alejandrarv 
- Cambios de autores de casos prácticos @ivandevp @AnaSalazar 
- Medir tiempos reales de ejecución @alejandrarv @LucileBaratier @valentinasmith
- Corrección de estándar en lectura de eventos @michellesegv 
- Videos de limpieza de código @karlanavam @AmaliaRiveraC @shirley-suarez @memecast @IntiDev @ivandevp
- Propuesta de rúbricas @brecabal 
- Ejercicio de El Laberinto @RuthSalvador

**Comment by RuthSalvador** [comment]
https://github.com/Laboratoria/curricula-js/tree/03-interactive/03-interactive-site/01-making-your-site-interactive/10-code-challenges

Hola!! hemos visto el solucionario y observando el producto final(data-dashboard), creemos que con trello y twitter van a estar listas para desarrollarlo, sugiero que el reto del Laberinto sea opcional como el de Workshopper de la 1ra unidad.

**Comment by valesmithb** [comment]
Sí! Nos parece perfecto!

**Comment by indie-rok** [comment]
Hola.
Ya tuvimos la charla con el equipo de México y votamos por quitarlo :)

Saludos

**Comment by ivandevp** [comment]
@indie-rok quitarlo o ponerlo como bonus?

**Comment by indie-rok** [comment]
Perdón, quitarlo de obligatorio y ponerlo como bonus como sugiere @RuthSalvador 

Gracias!

**Comment by ivandevp** [comment]
Se procede a cerrar este issue ya que se hicieron los cambios en base a las mejoras propuestas en el feedback del hand-off. Solo 2 issues quedaron pendientes como mejoras y están especificados en los issues #365 y #366.

Gracias a todos por sus contribuciones! 🎉 👏 💪 

cc/ @Laboratoria/education-team @Laboratoria/instructores-bootcamp
