### ISSUE TITLE
02-basic-programming: limpiar estilo de markdown de acuerdo a linter

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#324]
## 00-welcome

- [x] 00-opening
- [x] 01-about-laboratoria
- [x] 02-sprint-demo
- [x] 03-learning-at-laboratoria
- [x] 04-sprint-1-kickoff

## 01-basic-programming

- [x] 00-opening
- [x] 01-command-line
- [x] 02-git
- [x] 03-recap-intro
- [x] 04-arrays
- [x] 05-objects
- [x] 06-properties-and-methods
- [x] 07-arrays-and-objects
- [x] 08-practical-cases
- [x] 09-quiz
- [x] 10-seminar
- [x] 11-soft-skills-1
- [x] 12-guided-exercises
- [x] 13-code-challenges
- [x] 14-bonus-code-challenges
- [x] 15-solutions-code-challenges
- [x] 16-requiz
- [x] 17-self-assessment
- [x] 18-closing

## 02-final-products

- [x] 01-final-products
- [x] 02-code-review
- [x] 03-soft-skills-2
- [x] 04-soft-skills-3
- [x] 05-solutions-final-products
- [x] 06-survey
- [x] 07-retrospective

**Comment by lupomontero** [comment]
Hola @MaiaRojas y @RuthMeryCardenas! Gracias por los avances hasta ahora 👍 

He aceptado el pull request, y he añadido un [commit](https://github.com/Laboratoria/curricula-js/commit/f3777118bdf1479f27d31f07e16151dbf9e72b9c) con un par de cambios sobre sus cambios, así que asegúrense de jalar cambios de acá antes de continuar en su fork 😉 

💪 🚀

**Comment by MaiaRojas** [comment]
@AnaSalazar  sería chevere. Asi yo también lo actualizo. Por mi no hay problema. 👍

**Comment by AnaSalazar** [comment]
Listo, se cierra este issue. 
Ya se han resuelto todos los pendientes de limpieza de estilo de markdown de acuerdo a linter

cc/ @MaiaRojas @RuthMeryCardenas
