### ISSUE TITLE
Eliminar parts que representan self-assessment (lms ya tiene el feature de self assessment)

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/curricula-js#335]
Actualmente existen algunos cursos que tienen **parts** con el nombre de self assessment probablemente porque antes el LMS no lo contemplaba programáticamente.

Un ejejmplo lo puede encontrar en este ruta:

Basic programming / 01-basic-programming / 17 - self assessment

Esta parte debe ser eliminada del curso porque ahora el LMS ya maneja el self assessment por código.

**Comment by ivandevp** [comment]
@giancorzo este feature ya está en producción?

**Comment by giancorzo** [comment]
Si ya está en produccción. Puedes revisar el issue https://github.com/Laboratoria/lms.laboratoria.la/issues/52

**Comment by lupomontero** [comment]
Cierro este issue por ahora. Dejo dos pull requests con los cambios necesarios para dejar esto cerrado:

* https://github.com/Laboratoria/curricula-js/pull/505
* https://github.com/Laboratoria/curricula-js/pull/506
