### ISSUE TITLE
Añadir concepto de algoritmo a curso de Introducción a la programación

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#34]
Ver:

https://github.com/Laboratoria/curricula-js/pull/20#issuecomment-307188948
https://github.com/Laboratoria/curricula-js/pull/20#issuecomment-307198426

**Comment by ivandevp** [comment]
@chamodev Podemos tomar como referencia lo que hace Khan Academy en su [curso de algoritmos](https://es.khanacademy.org/computing/computer-science/algorithms#intro-to-algorithms).

Me comentas si necesitas apoyo.

**Comment by chamodev** [comment]
He dejado un comentario en nuestra conversación sobre este tema:
https://github.com/Laboratoria/curricula-js/pull/20#issuecomment-307188948
