### ISSUE TITLE
09-paradigms:06 Modularidad

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/curricula-js#350]
El video de la siguiente sección   06 :Modularidad se repite en la seccion 05:Programación por procedimientos.

https://lms.laboratoria.la/cohorts/lim-2017-10-ec-js-paradigms/courses/paradigms/01-paradigms/06-modules

**Comment by giancorzo** [comment]
Hola @MaiaRojas 

De acuerdo con lo que conversé con @lupomontero este es un error de la edición del video, hay que ver la manera de volver a solicitar una reedición (y quizá aprovechar un mecanismo para hacerlo inhouse)

**Comment by lupomontero** [comment]
Actualizado!
