### ISSUE TITLE
Guía de GIT

### ISSUE THREAD

**Issue by FabianBravoA** [Laboratoria/curricula-js#351]
Estoy confeccionando una guía de GIT/Github paso a paso. La idea es que tengan una referencia en caso de que necesiten ayuda con esta herramienta poderosa pero compleja.

El link para que revisen como va : 
https://fabianbravoa.gitbooks.io/manual-git/content/

**Comment by giancorzo** [comment]
Buena iniciativa @FabianBravoA 

Como soporte de mis clases de git siempre les daba esta guía de git que es muy sencilla de leer y usar. Tiene traducción a todos los idiomas y quizá te pueda servir como referencia

http://rogerdudler.github.io/git-guide/

**Comment by ivandevp** [comment]
@karlanavam sería bueno que comentes la iniciativa que ustedes han tenido en México para no duplicar esfuerzos 😃

**Comment by karlanavam** [comment]
Hola @FabianBravoA, acá en México hice un tutorial gráfico que ayuda a comprender este proceso de una manera simplificada y con un poco de humor, a la par uso mi cuenta para dar un ejemplo de cómo debe ser dicho proceso.
La intención es brindarles otra herramienta de apoyo.
Se los comparto para que vean cómo va quedando, hasta ahora sólo tengo contemplado lo que ellas saben hasta el sprint 1, pero la idea es seguir el proceso en el tutorial.

[tutorial-github.pdf](https://github.com/Laboratoria/curricula-js/files/1419412/tutorial-github.pdf)

**Comment by FabianBravoA** [comment]
Está genial esa guía, como inicio o recuerdo rápido, para el comienzo del bootcamp. La idea de la guía que estoy confeccionando es que sea más completa, para que tengan de referencia a lo largo del bootcamp. Alguien que la entienda completamente estará a un nivel intermedio o incluso avanzado de uso de git.
Esto porque muchas alumnas vienen a preguntar por pérdidas de referencia con remote, o como actualizar código de un fork, o qué sucede en caso de conflictos, etc... Cosas que aparecerán en su vida laboral más adelante y que sería bueno que tuvieran una ayuda permanentemente para entender qué sucede y poder solucionarlo.

**Comment by FabianBravoA** [comment]
¿Podría ser una posibilidad tener material así en algún repositorio o carpeta compartida con las alumnas?

**Comment by giancorzo** [comment]
Hola @FabianBravoA 

Apoyo la moción de la guía más compleja, muchas veces las chicas tienen problemas que van más allá de simple add, commit push. Por ejemplo seria bueno enseñarles a hacer pull requests, agregar más de un remoto, git stash, git fetch, etc...

Te comento que todos tienen la capacidad de crear repositorios en la organización de laboratoria (públicos como privados), yo sugiero que podriamos tomar esa guía básica de @karlanavam y pasarla a una web bonita que podamos compartir fácilmente, así generamos tráfico hacia tu guía más completa.

**Comment by paolocarrasco** [comment]
A mis compañeros de trabajo les hago repasar esta guía que justamente tiene temas un poco más avanzados, especialmente los relacionados a branching y repositorios remotos, no solo es visualmente atractivo y dinámico, sino que también interactivo:
https://learngitbranching.js.org/
Otro tutorial bueno para los diferentes stages que se tienen en git es este (también interactivo y visual):
http://www.ndpsoftware.com/git-cheatsheet.html
**¡Tienen ambos versión en español!**

**Comment by FabianBravoA** [comment]
Genial aporte, especialmente para hacer las clases. Muchas gracias Paolo.

**Comment by ivandevp** [comment]
@FabianBravoA a partir de la visita de Google, creamos cierto tipo de contenido que no necesariamente es calificado pero que ayuda en muchos procesos del aprendizaje durante el Bootcamp, por el momento lo hemos puesto en un folder llamado `99-general-concepts`. Sería genial, si el contenido de `GIT` que estás agregando va ahí. La idea es que este curso esté siempre disponible para las estudiantes 😃  ¿Qué opinas?

**Comment by FabianBravoA** [comment]
Oka, ahora estaba trabado tratando de obtener algunos conflictos para la guía. Apenas termine el capítulo comienzo la migración.

**Comment by ivandevp** [comment]
Genial @FabianBravoA, cualquier duda o apoyo que necesites, me comentas.

**Comment by AnaSalazar** [comment]
Hola @FabianBravoA !!! Me encantaría saber el status de este issue para saber si lo damos por cerrado, lo mantenemos abierto, se necesitan manos...?
