### ISSUE TITLE
03-interactive-site: Mejoras del texto de lectura `02-ux-design`

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#356]
@indie-rok @lalogf este issue es respecto a la conversación del #344 

El detalle de la observación fue el siguiente:

> @lalogf: Me gusta el texto y las preguntas. Dos temas que acotar, quizás en lugar de consumo pondría satisfacción. Y esta satisfacción se podría medir en mayor consumo en una 'for profit' o en mayor impacto en una 'non for profit'. La parte final sí es tricky porque un mayor consumo no necesariamente significa un mejor UX. Aquí un ejemplo:

> Page Views kinda’, sorta’ measures consumption. But are a lot of Page Views per visit a good thing (“the visitor loved our site so much!”), a bad thing (“our site is so bad it takes 23 pages to find what you’re looking for!”), or a horrible thing (“After a 23-page hunt, the visitor gave up!”)?
(https://www.thinkwithgoogle.com/marketing-resources/data-measurement/you-are-what-you-measure/)

**Comment by valesmithb** [comment]
Hola chicos! Cuando corrimos UX tuvimos algunos errores de cálculo del tiempo que está en el LMS, al parecer están contabilizados sólo para la lectura del texto, nos pasó en:
- Navegación: incluye una lectura de 30 páginas https://drive.google.com/file/d/0B0NdG2VNCDPzcU5qMG5SWnBpeEE/view
está para 30 min, calculamos 90
- Sketching: inlcuye un video de una hora https://www.youtube.com/watch?v=L1pBhHjGKvI&feature=youtu.be&t=23m00s
está para 15 min, calculamos 80 min
para que calculemos más tiempo en esos temas @ivandevp

**Comment by lalogf** [comment]
Gracias por el feedback @valesmithb . Para el sketching solo era necesario ver una parte del video, del minuto 23:00 al 25:00, creo que eso no quedó claro . @alejandrarv porfa ténganlo en cuenta para cuando se ejecute el contenido en Lima.

**Comment by alejandrarv** [comment]
gracias! @valesmithb @lalogf
