### ISSUE TITLE
03-interactive-site: Propuesta de rúbrica

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#365]
@brecabal creo este issue para que puedas poner la propuesta de la rúbrica de corrección de ejercicios y podamos discutir al respecto 😃

**Comment by brecabal** [comment]
Dejo la propuesta de rúbrica realizada por @marciamillanao del team de Chile , para su feedback

https://docs.google.com/spreadsheets/d/1EYBpz35FIHGIIt6VybVkyuROMBcyhKUz5ZIpuGGfLR8/edit#gid=982745944

@ivandevp @Laboratoria/instructores-bootcamp

**Comment by RuthSalvador** [comment]
@ivandevp @brecabal @MarciaMillanao 
Hola chicos! 
- En la parte de comentario para alumna, sugiero que usemos el método feedback hamburger: un comentario positivo + cosas a mejorar + comentario positivo.

Gracias

**Comment by bosqueinvierno** [comment]
Hola! Dejo la propuesta de rúbrica para el producto final para su feedback:
https://docs.google.com/spreadsheets/d/1QrcUlHmHf0tP63rDNzzm3rjvhMAo3TaIEHHKGTbbgC8/edit#gid=205542111

**Comment by ivandevp** [comment]
@bosqueinvierno en la sección de buenas prácticas deberían usar la guía de estilos de Laboratoria, cuenta incluso con un archivo de configuración de [eslint](eslint.org).

**Comment by RuthSalvador** [comment]
Hola! creo que sería una buena idea en lugar de desplegar cada funcionalidad(perfil, newfeed, subir fotos, etc) mejor considerar todo como funcionalidad de la red social, es decir, que la red social contenga lo que ellas están proponiendo. Por ejemplo si hacen una red social de libros, puede ser que en lugar de subir la imagen del libro, mejor linkeen el pdf del libro o no necesiten subir imágenes para eso y según la última rúbrica, el subir imágenes vale un 10%(no podríamos ponerles nota de ello).
Es una sugerencia no sé que opinan...

**Comment by bosqueinvierno** [comment]
La decisión de poner esos puntos dentro de la rúbrica se debe al planteamiento del ejercicio, ya que se especifica que el supuesto emprendedor que les encarga la red social considera algunos puntos básicos para que lo desarrollado sea una red social, que serían:

- Perfiles de usuarios
- Un newsfeed donde puedes ver las actualizaciones de todos tus contactos
- Un lugar donde poder escribir posts
- Un lugar para subir fotos
- Capacidad para poder tener amigos o para poder seguir a personas/marcas dentro de la red social
- Ser mobile friendly

Al final, eso fue lo básico que se consideró para realizar la rúbrica. Lo que se podría añadir para compensar puntaje en caso de que alguna pareja no realizara uno de esos puntos, es que añadamos una columna de "extras" que no se pidieran en el producto final (sea utilizar alguna API, etc).

**Comment by RuthSalvador** [comment]
Estaría bien!!!
Qusieramos agregar también la evaluación del trabajo en equipo y trabajo individual.

Trabajo en equipo: Colaboraron equitativamente en maquetado y funcionalidad(puedes guiarte de los gráficos de contribuciones en Github, además del blame and history en cada archivo en Github).

Trabajo individual: Colaboró en maquetado y colaboró en funcionalidad.

**Comment by RuthSalvador** [comment]
Les dejo la rúbrica de Lima https://docs.google.com/spreadsheets/d/1-H8u5B_eXzJYaCFkDVyLU6NEANXnbNLoWRpfQdpI-IA/edit#gid=636516141

**Comment by AnaSalazar** [comment]
Hola @Laboratoria/instructores-bootcamp 

Hay algo que quieran agregar, modificar o comentar acerca de esta rubrica o la damos por cerrada?

**Comment by ivandevp** [comment]
Cerramos el issue debido a que ya fue ejecutado este curso en las sedes de CDMX, Lima, Santiago de Chile y que la rúbrica se viene trabajando a nivel regional.
