### ISSUE TITLE
03-interactive-site: Videos de limpieza de código en base a estándares

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#366]
@AnaSalazar en este issue específico es para mantener el status de mejora de los videos en base a los estándares en formato de código y estructura de archivos.

Si es posible, sería bueno que agregues un `to-do list` a este issue para que puedan ir marcando el avance 😃 

cc/ @IntiDev @AmaliaRiveraC @shirley-suarez @memecast @karlanavam

**Comment by AnaSalazar** [comment]
- [ ] menú Hamburguesa @IntiDev 

- [ ] Lab Menú @memecast 

- [ ] Buscaminas @karlanavam

- [ ] Dropdown @shirley-suarez 

- [ ] Reserva de lugares @AmaliaRiveraC

**Comment by AnaSalazar** [comment]
Se cierra este issue, ya que ha quedado completado.
