### ISSUE TITLE
14-chatbot: Propuesta curso chatbot en Azure

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#377]
El primer objetivo principal es proponer reto(s) sobre los que desarrollar la agenda y contenido de acompañamiento para el curso.

**Comment by lupomontero** [comment]
Hola @jcastanedacano, alguna novedad con respecto a este issue? Avísame si te podemos ir dando feedback sobre la propuesta.

Como referencia, acá dejo links a brief y notas para instructores de otros retos que se están diseñando en esta línea:

* [Propuesta nuevo reto 2nda iteración curso de React: brief](https://github.com/rlazo/curricula-js/blob/70c7dddf0782690872d760b312204b494871abea/11-react/product-suggestion/student-handout.md)
* [Propuesta nuevo reto 2nda iteración curso de React: notas para instructorxs](https://github.com/rlazo/curricula-js/blob/70c7dddf0782690872d760b312204b494871abea/11-react/product-suggestion/instructor-handout.md)
* [Reto final de curso 03-interactive del bootcamp: brief](https://github.com/ivandevp/curricula-js/blob/03-interactive/03-interactive-site/03-data-dashboard/01-final-product/README.md)
* [Reto final de curso 03-interactive del bootcamp: notas para instructorxs](https://github.com/ivandevp/curricula-js/blob/03-interactive/03-interactive-site/03-data-dashboard/01-final-product/README-instructor.md)

Saludos! 💪 

cc/ @CaroLaboratoria

**Comment by jcastanedacano** [comment]
Este curso está diseñado para desarrolladores. Este curso acelerará rápidamente al asistente en el Microsoft Bot Framework como una herramienta / portal de desarrollo y las API de Servicios Cognitivos para inteligencia, uniendo los dos en la creación de un bot inteligente de chat para plataformas conversacionales. Se enfatizará el diseño reflexivo, al igual que en Data Science, así como la experiencia del usuario junto con las pruebas para crear las mejores experiencias de bot.

**Comment by jcastanedacano** [comment]
A continuación se está proponiendo la siguiente estructura del desarrollo de este curso:

- Principios del diseño de Bot
- Tipos de Bots
- Introducción al Microsoft Bot Framework
- Microsoft Bot Framework - Trabajando con canales
- Descripción de los servicios cognitivos
- Integración de Servicios Cognitivos con Bots
- Prueba de Bots
      Pruebas unitarias
      Usando Ngrok para probar
      Línea Directa API 
- Vigilar la salud de los bots - Telemetría
- Introducción a LUIS

**Comment by lupomontero** [comment]
@jcastanedacano: Gracias por los comentarios. Tomando esto como punto de partida me he tomado la libertad de actualizar el [`README.md`](https://github.com/Laboratoria/curricula-js/blob/14-chatbot/14-chatbot/README.md) del curso (ver https://github.com/Laboratoria/curricula-js/commit/1762662690bf803eca9340e2525d606f8c8e5ba4). Seguiremos iterando... 💪 

He añadido un _syllabus_ (por ahora solo los headings) basado en la estructura que propones, además de un ejemplo de _agenda_, que conceptualmente es algo separado del _syllabus_, que debe estar enfocado en ser material de apoyo (que puedan consumir en cualquier momento, y no necesariamente de forma lineal).

Como siguiente paso, creo que lo más importante sigue siendo la propuesta del reto (o los retos). Lo ideal es que el reto se plantee como un _brief_ que pudieran recibir de un cliente ficticio que quiere prototipar una idea. En base a estos retos, la chicas tendrán que elegir un reto (si hay más de uno) y hacer una propuesta de producto/prototipo que desarollarán a lo largo del curso.

Podrías añadir tu propuesta de reto(s) en la [sección de "Producto" del README.md](https://github.com/Laboratoria/curricula-js/blob/14-chatbot/14-chatbot/README.md#producto) o añadir un archivo markdown (ver [ejemplo](https://github.com/Laboratoria/curricula-js/tree/03-interactive/03-interactive-site/03-data-dashboard/01-final-product)) y enviar un pull request desde tu fork para darte feedback?

cc/ @CaroLaboratoria

**Comment by orortega** [comment]
@jcastanedacano Favor de cambiar público objetivo a: Está destinado a personas con conocimientos básicos en C# y bots que deseen comenzar a desarrollar bots multi-plataforma utilizando la nube para integrar un bot en aplicaciones web, redes sociales y otros medios de comunicación.

**Comment by lupomontero** [comment]
Conversación continúa en #464
