### ISSUE TITLE
Recopilar recursos para el curso de React

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curricula-js#38]

**Comment by merunga** [comment]
genail @indie-rok 
aqui mismo en un comentario puede ir pegando las referencias. Si son muchas por favor colocalas en dos categorias tipo "fundamentales" y "recomendadas" o algo asi, para no tener q volver a curarlas.

las q decidamos, las incluyo ya formalmente en el README

Gracias!

**Comment by merunga** [comment]
@lupomontero cerramos este issue?

**Comment by lupomontero** [comment]
Cerrado en #57

@indie-rok: si tienes cualquier sugerencia con respecto a este tema no dudes en abrir un issue nuevo o enviar PR a este branch ;-)
