### ISSUE TITLE
12-redux: Separar syllabus de agenda

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#382]
El _syllabus_ debe quedar como material de apoyo, mientras que la agenda debe estar pensada para las sesiones presenciales, los retos, demos, ...

cc/ @CaroLaboratoria

**Comment by lupomontero** [comment]
Ver https://github.com/Laboratoria/curricula-mobile/issues/6

**Comment by lupomontero** [comment]
En el readme tal y como astá ahorita se mencionan un montón de librerías (thunk, rxjs, observable, saga, ...). Creo que no hay necesidad de cubrirlas todas... quizás mencionarlas?

**Comment by rodrwan** [comment]
Si, no veo la necesidad de mencionar todas, quizás confundirían más, algunas de ellas son bien complejas de entender a priori, y si a lo largo del curso no las usamos, no vale la pena, quizás en el cierre de la última catedra, se podrían mencionar como posibles trabajos futuros y para dejarles el bichito (:bug:) de investigar más sobre esas librerías.

**Comment by ivandevp** [comment]
@lupomontero Este PR se debe ir cerrando, verdad? Veo que el PR de @rodrwan fue aceptado.

**Comment by lupomontero** [comment]
Me temo que por el momento esto no es una prioridad... así que cierro el issue por ahora. En el momento en que se retome este tema vemos cómo continuar.

Gracias!
