### ISSUE TITLE
12-redux: Crear brief(s) para retos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#383]
Necesitamos producir los briefs para los retos que les vamos a plantear a las chicas. La descripción del proyecto o producto en este caso viene como un _brief_ de un cliente ficticio, acompañado de los necesarios assets y notas para instructores.

cc/ @CaroLaboratoria

**Comment by lupomontero** [comment]
Algunas notas sobre ideas que estamos conversando y deberían informar la creación de cursos:

* grades are irrelevant when you can show the work done (portfolio) and the experiences lived (community, hackathons, events, challenges, …)
* grades are a really outdated way of generating a profile, we can do better
* courses should build your portfolio, hence the deliverable is always a “public” piece of work
* some soft skills can be “inferred” from work done, roles assumed, successes, failures, …
* learners should be presented challenges that they can only solve through learning, and let them learn, only guiding them when really needed

**Comment by rodrwan** [comment]
Un reto a priori, que se me viene a la cabeza, es utilizar la herramienta `create-react-app` de facebook que entrega lo básico para llegar y programar sobre ReactJS, y sobre esto agregarle redux. Algo tipo, "tienes este boilerplate, necesitamos agregarle redux porque es cool". Luego avanzar con conceptos más claves sobre este mismo proyecto, cosa de ir añadiendo los reducers, las acciones y todo lo demás.

Inclusive, una primera parte sería armar el proyecto (por ejemplo un *grocery store*) que no tiene redux y aplicarle redux a ese pet-project, con tal de ir limpiando los estados de cada componente e ir mostrando como se centraliza la data de una aplicación con redux.

La idea madre, es que sea progresivo, por ejemplo:

1.- agregar redux
2.- crear store
3.- primeros reducers y actualizar componentes.
4.- fetch de datos y guardar la data a través de las acciones.
5.- etc, etc... 

Por nada del mundo haría un TODO List porque eso está ultra desarrollado y creo que la idea un poco sería que las chicas y los profesores puedan idear sus propias soluciones al problema, dando paso a la creatividad.

qué opinan?

**Comment by lupomontero** [comment]
Me parece buena idea que tengan que arrancar con `create-react-app` y el flujo esperado de desarrollo. Ahora lo que nos falta es _crear_ la **narrativa** de un _reto_ y escribir tanto el brief como las notas para instructorxs.

Como referencia, acá dejo links a brief y notas para instructores de otros retos que se están diseñando en esta línea:

* [Propuesta nuevo reto 2nda iteración curso de React: brief](https://github.com/rlazo/curricula-js/blob/70c7dddf0782690872d760b312204b494871abea/11-react/product-suggestion/student-handout.md)
* [Propuesta nuevo reto 2nda iteración curso de React: notas para instructorxs](https://github.com/rlazo/curricula-js/blob/70c7dddf0782690872d760b312204b494871abea/11-react/product-suggestion/instructor-handout.md)
* [Reto final de curso 03-interactive del bootcamp: brief](https://github.com/ivandevp/curricula-js/blob/03-interactive/03-interactive-site/03-data-dashboard/01-final-product/README.md)
* [Reto final de curso 03-interactive del bootcamp: notas para instructorxs](https://github.com/ivandevp/curricula-js/blob/03-interactive/03-interactive-site/03-data-dashboard/01-final-product/README-instructor.md)

💪

**Comment by klujanrosas** [comment]
Hola @lupomontero Estos retos, ¿se enfocan en un área específica?

Como veo en la propuesta de **rlazo**,  en el instructor-handout especifíca un _Foco de aprendizaje_ , que para el son: 
- Modularización
- Stateful vs Stateless
- State Management
- Responsive Design

Entonces, ¿la idea es que estos retos envuelvan todo junto?, por ejemplo los conceptos de Redux, como Single Source of Truth, o Pure Functions, etc.

¿O plantear un reto para cada concepto _fuerte_ que tiene Redux?

**Comment by rodrwan** [comment]
Hola @lupomontero y @klujanrosas  

Tomando en cuenta ese approach, propondría dividir la parte practica en las siguiente 5 secciones:

* Agregar redux al workflow de desarrollo.
  - crear store y reducers básicos.

* Arquitectura.
  - estructura del proyecto para utilizar redux. (folder, best practice, etc).

* Aplicación de los conceptos básicos.
  - Single Source of Truth.
  - State is read-only.
  - Changes are made with pure functions.
Como se muestra [aquí](https://github.com/reactjs/redux/blob/master/docs/introduction/ThreePrinciples.md).

* Actions (aplicadas al proyecto) y multiples reducers.
  - combine reducers.
  - dispatch actions.

* Acceso de store en componentes, uso de mapStateToProps, mapDispatchToProps, etc.

Creo que abarca lo más importante de redux, creo que algunas se podrían combinar, para tener solo 4 puntos, eso ayudaría a dictar esos contenidos en 4 semanas.

**Comment by lupomontero** [comment]
Gracias por el feedback @rodrwan y @klujanrosas y disculpas por la demora en responder... 😰

Me temo que este issue no es prioridad ya que ahora los proyectos (retos) se manejan fuera de los contenidos (tópicos). Cerrando...
