### ISSUE TITLE
12-redux: recursos/material de apoyo para curso

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#389]
Inicio este thread (issue) para ir recopilando recursos/material de apoyo para el curso de [Redux](https://github.com/Laboratoria/curricula-js/tree/12-redux/12-redux)

Por ahora:

* https://redux.js.org/
* https://egghead.io/courses/getting-started-with-redux
* https://github.com/happypoulp/redux-tutorial
* https://medium.com/@pedroparra/redux-tutorial-bb8e87eebb09
* https://www.youtube.com/watch?v=1w-oQ-i1XB8
* ...

Se agradecen sugerencias :wink:

cc/ @Laboratoria/developers

**Comment by klujanrosas** [comment]
Hola @lupomontero acá dejo más recursos:

- **https://github.com/markerikson/react-redux-links**
- https://www.robinwieruch.de/learn-react-before-using-redux/
- https://www.robinwieruch.de/tips-to-learn-react-redux/
- https://medium.com/swlh/the-case-for-flux-379b7d1982c6
- https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367
- https://www.fullstackreact.com/articles/redux-with-mark-erikson/
- http://www.thegreatcodeadventure.com/building-a-simple-crud-app-with-react-redux-part-1/
- http://blog.isquaredsoftware.com/series/practical-redux/
- http://blog.isquaredsoftware.com/2017/02/presentation-react-redux-intro/
- https://www.reactiflux.com/
- https://daveceddia.com/how-does-redux-work/
- ...

**Comment by rodrwan** [comment]
* https://github.com/reactjs/redux/tree/master/docs/introduction
* https://medium.com/coding-artist/practical-redux-chapter-1-core-concepts-f5a53f74505c
* https://medium.com/@notrab/getting-started-with-create-react-app-redux-react-router-redux-thunk-d6a19259f71f
* https://medium.com/geogo-in/how-to-build-a-react-redux-application-with-api-first-cms-contentful-84efdd7ee654

**Comment by lupomontero** [comment]
* https://redux.js.org/docs/recipes/
* https://github.com/erikras/ducks-modular-redux
* https://github.com/reactjs/reselect

**Comment by merunga** [comment]
https://hackernoon.com/shape-your-redux-store-like-your-database-98faa4754fd5

**Comment by tzkmx** [comment]
Recientemente este artículo de Auth0 saltó a mi vista y me parece genial: https://auth0.com/blog/redux-practical-tutorial/

**Comment by lupomontero** [comment]
Gracias a todxs por los comentarios!

Me tomo la libertad de ir cerrando este issue por _inactividad_...

Acá les dejo link al _tópico_ de `redux` tal y como está la rama `v2.x` si quieren sugerir algún PR ahí:

https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/redux
