### ISSUE TITLE
09-paradigms: separar syllabus de agenda (revisar hoja de ruta...)

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#394]

**Comment by ivandevp** [comment]
Alguna novedad con este issue? Se necesita apoyo aun?

**Comment by lupomontero** [comment]
Este issue queda un poco obsoleto ahora que estos cambios se están llevando a cabo a nivel de _toda_ la currícula. Ver:

* https://github.com/Laboratoria/curricula-js/issues/546
* https://github.com/Laboratoria/curricula-js/issues/534

Así que cierro este issue...
