### ISSUE TITLE
09-paradigms: Proofreading

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/curricula-js#40]
Por encargo de Lupo, aquí un feedback sobre este enlace

https://github.com/Laboratoria/curricula-js/blob/09-paradigms/09-paradigms/03-paradigms.md

Observación 1.

En esta lección aprenderás las características y diferencias entre los paradigmas más relevantes para JavaScript, que es un lenguaje multi-paradigma y nos permite programar en varios estilos: imperativo, por procedimientos, orientado a objetos (OOP), funcional (FP), orientado a eventos, ...

En esta lección aprenderás que es un paradigma de programación, que existe varios tipos distintos como el imperativo, por procedimientos, orientado a objetos (OOP), funcional (FP), orientado a eventos, etc y cual de estos es revelante en JavaScript

Observacion 2

En "Objetivos de la lección " faltaria incluir que objetivo se aplica a Javascript

Observacion 3

Instalar learnyouparadigms con el siguiente comando: npm install -g Laboratoria/learnyouparadigms

Seria bueno incluir una guia al uso de NPM (si es que hay no dije nada). learnyourparadigms es planet proto?

Observacion 4 (sección recurso vs imperativo)

Solo como comentario quizá es bueno poner una referencia al concepto de recursividad y quiza explicar las diferencias entre cada una (es importante notar que una mala recursividad te puedes volar la memoria, pero quiza este comentario esta fuera de scope)

Observacion 5

Ejercicio paradigma imperativo - Incluir guia a forkeo

Observacion 6
Referente a esta sección:
"Una de las consecuencias de estos cambios es el concepto de "modularidad". Esto va a permitir que empecemos a escribir programas estructurados en módulos independientes, que son más fáciles de entender, testear, mantener, ..."

Entiendo 100% porqué quieres sacar este concepto ahi pero sugiero que esta sección o se ponga como topico extra o en otro lado porque corta el flow de la explicación que estas dando. 

Mi opinión personal respecto a la modularidad es que tiene que ver más en la forma en que estructuramos nuestro archivos de codigo mas que con el hecho de usar funciones.

**Comment by diegovelezg** [comment]
https://github.com/Laboratoria/curricula-js/tree/master/01-intro

D = Dice
DD = Debe decir

## Aprenderás
D: "como: variables, tipos datos, estructuras"
DD: "como: variables, tipos **de** datos, estructuras"

### Productos a desarrollar
D: "¿Es una tarjeto de crédito falsa?"
DD:  "¿Es una tarjeta de crédito falsa?" (tarjetA)

### Lección 08
D: "el siguiente código para que de acuerdo a la edad clasifique entre"
DD: "el siguiente código para que, de acuerdo a la edad, clasifique entre" (comas prep)

### Lección 10
D: "profundidad y por lo tanto retornarás"
DD: "profundidad y, por lo tanto, retornarás" (comas prep)

D: "darás tu primer paso a entender"
DD: "darás tu primer paso para entender"

### Lección 16
D: "¿Es una tarjeto de crédito falsa?"
DD:  "¿Es una tarjeta de crédito falsa?" (tarjetA)

**Comment by chamodev** [comment]
@diegovelezg: ¡Gracias por el feedback! He modificado el texto en la branch del curso `intro-js`: 
https://github.com/Laboratoria/curricula-js/tree/intro-js/01-intro (ojo que este branch tiene la última versión del contenido de ese curso).

Otra cosa, para feedback del curso `Intro a la programación (con JS)` es mejor utilizar el issue #61. En este issue se está recopilando feedback del curso de `paradigmas` (asignado a @lupomontero).

@giancorzo: tip para crear futuros issues: agregarle el nombre del curso que estás dando feedback. Thanks!!

**Comment by giancorzo** [comment]
Listo ya le agregue al issue el nombre del curso

**Comment by giancorzo** [comment]
Cierro este issue porque los cambios ya fueron integrados en la curricula.

**Comment by giancorzo** [comment]
Sorry, no vi que lupo cambio el proposito del issue. Lo voy a reabrir

**Comment by lupomontero** [comment]
@giancorzo: ahora que estamos iterando sobre el curso `09-paradigms` aprovecho a incluir tus comentarios. Ahí van mis respuestas:

1. Siendo un tema de estilo, por ahora lo dejo como está
2. He añadido detalle sobre contexto de JavaScript en opening de unidad (https://github.com/Laboratoria/curricula-js/commit/8a8f82616288e12cdaecd2a1a8d1686cfc159d70#diff-05c432f0e36817ef6aaa32d31b216fc2R26)
3. Ya no se aplica, ahora los ejercicios están adentro del LMS
4. El tema de recursividad se ve en "JS Deep Dive" justo antes y más en detalle en "Functional JavaScript" que viene justo después. Por eso la decisión de no hacer mucho incapié en este curso.
5. Ya no se aplica, ahora los ejercicios están adentro del LMS
6. Con respecto al tema de la modularidad, estoy de acuerdo en que no es un paradigma ni parte de un paradigma, pero desde el punto de vista histórico (y técnico) es con la programación procedural, y gracias a las funciones que se el concepto de modularidad, que es algo que queremos incluir ya que es un concepto fundamental que por lo general las chicas no parecen tener tan claro todavía.

Gracias! 💪
