### ISSUE TITLE
Añadir soporte para emojis

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#419]
Referencias:

* https://gist.github.com/rxaviers/7360908
* https://github.com/omnidan/node-emoji

**Comment by AnaSalazar** [comment]
Hola @lupomontero , me gustaría saber el status de este issue. 😄 

En que se va a añadir el soporte?
Qué se está haciendo?
Hay alguien encargado de esto?

**Comment by lupomontero** [comment]
Este issue realmente pertenece en el repo de LMS ya que es un feature de la interfaz y no de la currícula en sí. Lo he movido donde corresponde: https://github.com/Laboratoria/lms.laboratoria.la/issues/159
