### ISSUE TITLE
05-deep-dive: definir cambios para conversión a formato bootcamp

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#424]
Replantear curso, nuevo reto, agenda...

Como referencia, el _producto_ de ejemplo está [acá](https://github.com/Laboratoria/pinterestify)

cc/ @ivandevp

**Comment by lupomontero** [comment]
@ivandevp: finalmente estoy pudiendo avanzar con este tema (😰) y me surgen varias preguntas:

1. No estoy seguro de si la idea es _mover_ el curso al Bootcamp o _crear_ un curso nuevo y dejar el que está ahora en EC tal y como está? Creo que tiene más sentido _moverlo_ y sacarlo de EC por ahora... qué opinas?

2. Las chicas ya han visto algo de `jQuery` antes de este curso?

Por ahora he estado retocando el `README.md` principal y me gustaría hacer lo siguiente:

1. Convertir reto actual en un brief más abstracto y agregar dos retos más para que las chicas puedan elegir.

2. Añadir el concepto de testing desde el principio. En este caso, al ser el diseño de una librería, esto implica diseñar de acuerdo a un contrato (API), lo cual es perfecto para hacer TDD. Mi intención es introducir los temas específicos de JavaScript (variables, scope, funcs, estructuras, ES6...) a través de tests que demuestren estos features.

3. Introducir convenciones comunes en módulos y librerías: `package.json`, `README`, tests, linter, ci, ...

4. ...

Esta tarde estoy subiendo la descripción de los retos (y más cambios a la estructura) para que se entienda más fácilmente lo que tengo en mente...

**Comment by AnaSalazar** [comment]
@lupomontero Las alumnas en este punto ya tuvieron un acercamiento a jquery. 
https://github.com/Laboratoria/curricula-js/tree/04-social-network/04-social-network es justo en el último sprint antes de la especialización.

**Comment by ivandevp** [comment]
1. El curso debería ser uno nuevo para el bootcamp, al final en EC es probable que si UXs quieren entrar a Front-end empiecen por este curso.

2. Algo cierto es que es una visión superficial sobre jQuery, saben como manipular y recorrer el DOM, pero no del todo las buenas prácticas y convenciones de código.

Respecto a los temas que propones me parecen muy chevere.

**Comment by lupomontero** [comment]
Ver https://github.com/Laboratoria/curricula-js/issues/472#issuecomment-357043381

**Comment by lupomontero** [comment]
Cierro este issue por ahora y continuamos las conversaciones en issues más específicos (#479, #478, #479, #473, ...)

**Comment by lupomontero** [comment]
A modo informativo, finalmente decidimos no incluir la unidad sobre paquetes y módulos...
