### ISSUE TITLE
04-social-network: Contenido de 02-jQuery

### ISSUE THREAD

**Issue by AnaSalazar** [Laboratoria/curricula-js#426]
- [x] 00-Opening  @AnaSalazar
 
- [x] 01-Intro-jQuery @AnaSalazar

- [x] 02-selectores @AnaSalazar

- [x] 03-DOM @AnaSalazar

- [x] 04-eventos @AnaSalazar

- [x] 05-quiz @karlanavam

- [x] 06-seminar

- [x] 07-guided-exercises @Jonhks

- [x] 08-code-challenges @memecast 

- [x] 09-solutions

- [x] 10-requiz @karlanavam

- [x] 11-self-assesment

- [x] 12-closing

**Comment by memecast** [comment]
@AnaSalazar Quiero ayudar con los code-challenges :D

**Comment by AnaSalazar** [comment]
Se cierra este issue porque ya se han realizado todos los pendientes. Gracias por sus aportes!!
