### ISSUE TITLE
Desarrollar Lección 02-variables-and-data-types del curso Intro a JS

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#43]
To Do:

- [x] @chamodev hacer encuesta de entrada
- [x] @chamodev afinar [quiz](https://goo.gl/forms/mfLgPHFwGfI0lrSH2)
- [x] @chamodev hacer auto-evaluación
- [x] @ivandevp revisar y aprobar [lectura 01 valores y tipos de datos](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/04-variables-and-data-types/01-values-data-types-and-operators.md)
- [x] @ivandevp revisar y aprobar [lectura 02 variables](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/04-variables-and-data-types/02-variables.md)
- [x] @ivandevp revisar y aprobar [lectura 03 self-learning MDN](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/04-variables-and-data-types/03-self-learning-MDN.md)
- [x] @ivandevp revisar y aprobar [lectura 04 COMMENTS](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/04-variables-and-data-types/04-Comments.md)
- [x] @MichelleSV crear videos de ejercicio guiado 1: Edad en segundos
- [x] @MichelleSV crear videos de ejercicio guiado 2: Convertidor de temperatura
- [x] @MichelleSV crear videos de ejercicio guiado 3: Ganancias y pérdidas
- [x] @MichelleSV crear videos de ejercicio guiado 4: Iniciales
- [x] @ivandevp revisar y aprobar los 4 videos de ejercicios guiados
- [x] @ivandevp validar [reto de código](https://repl.it/classroom/invite/GLlJ8G7)
- [x] @diegovelezg coordinar "test" con usuarios que no saben de código para validar que el material (lecturas, videos, cuestionario y reto) se entiende y cumple con el objetivo de aprendizaje
- [x] @chamodev agregar contexto sobre creación de cuenta en Replit (quizás @MichelleSV grabar un video de esto?)

**Comment by chamodev** [comment]
Otros cambios del review de Ivan:
- [ ] `ytengo`
- [ ] `Mucho éxito`

**Comment by ivandevp** [comment]
@MichelleSV Solo tengo unos comentarios respecto a los videos pero son menores y no creo que necesiten una corrección en el momento, pero si tenerlos en cuenta para los siguientes:

- Básicamente consistencia, en el video de `Mi primera web - Parte 2` no usas `;` al final del statement en JS. Luego en los PPTs usas mezclado `HTML` y `html` además de `Javascript` y `javascript`, yo prefiero `JavaScript` pero más que usar lo que yo prefiero, es tener consistencia en lo que usas.
- En los videos de los ejercicios guiados, tener en cuenta la separación del comentario luego de las 2 barras (`//`) y la separación que le das al operador `+` o cuando estás concatenando o sumando.

- Respecto a las soluciones, tengo la duda del ejercicio de iniciales, el porqué usar `.slice` y no un `.charAt` si solo vamos a obtener un caracter. Además es mucho [más rápido](https://jsperf.com/charat-vs-index/5).

**Comment by ivandevp** [comment]
Retos de código validado y conforme.

cc\ @chamodev @diegovelezg

**Comment by lupomontero** [comment]
Este issue se puede considerar "_solucionado_"?

@chamodev, si es así lo puedes cerrar, porfa?

**Comment by chamodev** [comment]
Correcto @lupomontero. Cerrado
