### ISSUE TITLE
18-data-visualization: videos

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/curricula-js#445]
@CaroLaboratoria: Me gustaría saber sobre el status de los videos,  si ya encuentran en el wistia. Si necesitas ayuda puedo apoyarte con eso para poder estar incluyendolo en la nueva estructura del curso.

**Comment by CaroLaboratoria** [comment]
@MaiaRojas muchas gracias por tu apoyo! No he podido subir los videos dado que son varios y no nos queda espacio en Wistia. @diegovelezg y @lalogf ven alguna alternativa?

**Comment by CaroLaboratoria** [comment]
@MaiaRojas ya se encuentran los videos subidos en wistia. Cualquier duda quedo atenta.

**Comment by MaiaRojas** [comment]
@CaroLaboratoria  ya desplegue el curso en mi dev para que lo puedas chequear , si hay algo que modificar por favor me avisas. :calling: 
https://laboratoria-la-dev-maia.firebaseapp.com/courses

**Comment by lupomontero** [comment]
@MaiaRojas: este issue ya se puede considerar como cerrado?

**Comment by MaiaRojas** [comment]
@lupomontero  Si este issue ya  fue resuelto en el PR #451

**Comment by lupomontero** [comment]
Gracias @MaiaRojas!
