### ISSUE TITLE
14-chatbot: Curso chatbot en Azure

### ISSUE THREAD

**Issue by cristianca-lagash** [Laboratoria/curricula-js#464]
**RETO #1**

Bot para fidelizar amigos/contactos

Como un usuario de Facebook sin tiempo necesito crear un Bots que me ayude
a mantener la relación con amigos con los cuales no hablo diariamente en Facebook

Criterios de aceptación

- El Bot debe conectarse a Facebook
- El Bot debe saludar para su cumpleaños a cada amigo
- El Bot debe tener interacción con amigos a los cuales no he hablado durante 30 días
- El Bot debe avisarme de los amigos que no contestan y recomendarme eliminarlos

**RETO #2**

Bot para apoyo de maestros sobre dudas de tareas

Como profesor necesito crear un bot que me apoye en contestar preguntas sobre las dudas que puedan surgir
en las tareas que doy para el hogar

Criterios de aceptación

- Las preguntas deben ser contestadas en un chat de una pagina web, Facebook o Skype
- El Bot debe poder indentificar a cada alumno
- El Bot debe contestar dudas sobre las tareas en particular
- El Bot debe aviarnos sobre la fecha limite de la tarea
- El Bot debe ser tener aspectos graciosos

**RETO #3**

Bot para consejos de belleza y combinacion de colores

Como dueña de una tienda de cosmeticos y accesorios necesito crear un bot que ayude a mis clientas a 
seleccionar los productos que necesiten, además debe prestar apoyo en la combinación de colores de accesorios

Criterios de Aceptación

- El bot debe considerar solo los productos deben ser solo de la tienda online
- Los consejos del Bot deben guiar la selección de cosmeticos sustentables y como última opción recomendar otro tipo de cosmeticos
- El apoyo en la combinación de colores debe ser además de accesorios sobre colores de tinturas para el pelo
- El Bot debe incluir un link para agregar productos a un carrito de compra

**Comment by cristianca-lagash** [comment]
DEFINICIÓN DE CLASES

CLASE #1

¿Que es Azure?
¿Que es un Bot y porque implementarlo en Azure?
¿Tipos de Bot?
¿Que utilidades le podemos dar a los bots?
Conozcamos Microsoft Bot Framework
 ¿Que es Bot Frameworks?
 ¿Que técnologias podemos integrar?
Coffe Break
Armar grupos
Definir Reto y como lo abordarán   
Comenzando con el reto

CLASE #2
Creando un Bot con node.js y Microsoft Framework Bot - 60 Min
Desarrollo y/o avance del Reto

**Comment by cristianca-lagash** [comment]
Las presentaciones de las clases deben estar en algún formato de Laboratoria o es abierto?

**Comment by lupomontero** [comment]
@cristianca-lagash: gracias por las propuestas. Me parece que va en la dirección correcta.

He añadido una estructura general de _unidades_ (que es lo que lee nuestro LMS) para ir dándole forma al flujo de todo el curso. Hay todavía mucho por rellenar, pero ya he añadido las propuestas de retos (las tuyas y las de @orortega) acá: https://github.com/Laboratoria/curricula-js/tree/14-chatbot/14-chatbot/01-challenge/01-challenges

Puedes ver los cambios en la rama [`14-chatbot`](https://github.com/Laboratoria/curricula-js/tree/14-chatbot/14-chatbot).

Con respecto a la definición de las _clases_, pensando en la primera semana, podrías ir llenando los textos de la [unidad 2](https://github.com/Laboratoria/curricula-js/tree/14-chatbot/14-chatbot/02-getting-started) con texto, links, videos, según consideres necesario y enviar pull request con tus cambios?

Esta tarde voy a leer los retos con más detenimiento para poder dar feedback más específico, por ahora me he concentrado en la estructura para que te sirva de guía y podamos tener esto _armado_ en cuanto antes ;-)

Finalmente, con respecto al formato de presentaciones, puedes usar lo que más te acomode para la clase en sí, pero para el repo y LMS lo mejor es exportar los slides como imágenes (png o jpg) y acompañarlas con texto dentro de un archivo markdown.

Gracias por el esfuerzo 💪 🚀

**Comment by CaroLaboratoria** [comment]
Estimados,

Dada la premura de la partida del curso, veo la alternativa de realizar las presentaciones en google drive y subirlas embed al LMS.
Si les parece puedo crear la carpeta con acceso a todos para guardar las presentaciones.
@cristianca-lagash @lupomontero

**Comment by ccardensa** [comment]
@lupomontero acá esta el repo para que le hagas un clon https://github.com/ccardensa/bot-framework, la idea de este primer código (modulo-01) es que vean como funciona el framework de bots con un ejemplo simple donde se podrá ejecutar en una consola.

En la siguiente clase mostraré un bot avanzado y su implementación, este ejemplo será rapido 60 minutos para que conozcan los tipos de bot en vivo con el código disponible.

El tema de los bots es muy amplio por lo cual debemos mostrar un universo acotado con interacciones sencillas, para que luego las alumnos se introduzcan de lleno en este mundo, pero de todos modos creo que no podemos mostrar un bot muy pobre, alguna de las demos debe incluir la publicación en azure.

**Comment by ccardensa** [comment]
@lupomontero favor agregar al siguiente usuario para poder descargar y modificar el repo @ccardensa

**Comment by lupomontero** [comment]
### 1. He echado un vistazo rápido al repo [ccardensa/bot-framework](https://github.com/ccardensa/bot-framework) y me llama la atención lo siguiente:

  * El ejemplo (`modulo-01`) contiene un `package-lock.json`, lo cual indica que se ha ejecutado `npm install`, pero falta el archivo `package.json` (a partir del cual `npm` crea el `package-lock.json` a la hora de hacer `npm install`).
  * Se ha incluido la carpeta `node_modules`, la cual no debería incluirse en el repo (debería estar ignorada via `.gitignore`). A nivel de dependencias, lo único esencial es el `package.json`, que es lo único que falta 😕
  * Tratándose de un ejemplo tan pequeño (menos de 10 líneas de código), creo que tendría más sentido incluirlo como `snippet` dentro del contenido del curso en sí (probablemente [acá](https://github.com/Laboratoria/curricula-js/tree/14-chatbot/14-chatbot/02-getting-started/02-ms-bot-framework)).
  * Como aclaración, a nivel de código fuente, esperaba un ejemplo de implementación de un bot dentro del _scope_ de los [retos planteados](https://github.com/Laboratoria/curricula-js/blob/14-chatbot/14-chatbot/01-challenge/01-challenges/README.md) que nos pudiera servir para informar las decisiones acerca de qué necesitamos para apoyar a las chicas a completar sus retos. El ejemplo visto por ahora sólo es un _hello world_ prácticamente igual al primer _snippet_ de ejemplo en la [documentación oficial de Bot Builder para Node.js](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart).

### 2. Con respecto a...

  > En la siguiente clase mostraré un bot avanzado y su implementación, este ejemplo será rapido 60 minutos [...]

  Por favor tener en cuenta que la idea es que las chicas usen el tiempo en clase presencial para _programar_ (construir su bot), con la excepción de la primera clase, donde sí tiene más sentido _enseñar_ o _mostrar_ ejemplos como parte de la introducción. Tratemos de evitar que el tiempo presencial se dedique casi en su totalidad a programar, en un espacio donde las chicas tienen acceso a sus instructores y compañeras (esa es la pieza clave de la experiencia de aprendizaje). Pensemos en una _hackathon_ de varias sesiones y no en una clase magistral.

### 3. Scope de retos

Por otro lado, como parte de cada uno de los retos se espera que las alumnas lleguen a desplegar su bot en Azure, pero no necesariamente es algo que les _enseñamos_, siempre y cuando les demos el material de apoyo necesario, ya sean textos/videos/ejemplos escritos por nosotros o documentación oficial, blog posts, videos en youtube, ...

### 4. Acceso al repo

Con respecto al acceso al repo, ten en cuenta que este repo es abierto (open source). Para hacer tus cambios simplemente crea un _fork_, haz los cambios en tu _fork_ y de ahí manda un _pull request_ a la rama correspondiente del repo de Laboratoria (`14-chatbot` en este caso). No se necesitan permisos especiales para esto. Como referencia, en este artículo del wiki de este repo está detallado el proceso más común de colaboración para la creación de un curso:

https://github.com/Laboratoria/curricula-js/wiki/Colabora

Finalmente, quería que me aclares qué usuario de GitHub es el que vas a estar usando, @ccardensa o @cristianca-lagash? Pregunto para poder linkear correctamente tu nombre como autor en el `README.md` del curso, así como para incluirte oficialmente como colaborador en GitHub, lo cual nos permitirá asignarte issues.

cc/ @CaroLaboratoria @orortega

**Comment by cristianca-lagash** [comment]
@lupomontero te dejo mis comentarios

R1: Modificaré los archivos de git, por otra parte el tamaño del bot para la primera clase de demostración esta bien, recuerda que por muy pequeño que sea debemos mostrar instalación, sintaxis y una pequeña interacción para que puedan seguir adelante.
Estoy preparando un ejemplo con servicios cognitivos para la segunda clase, así que tranquilo como introducción esta muy bien, a las chicas les vendrán muchas preguntas y dudas que deberemos abarcar en la primera clase (espero alcanzar hoy a dejar el bot con servicios cognitivos listo, si no para mañana)

R2: durante el día seguire subiendo material para consolidar las 2 primeras clases
R3: Esto es parte del material que estamos construyendo y mejorando semana a semana

¿Puedo generar link hacia mi blog con información de Bots?

Con respecto al usuario estoy utilizando @ccardensa, y no esta demás contarles que estamos haciendo todo el esfuerzo posible para que el material sea consistente y un apoyo a las chicas.

cc/@CaroLaboratoria @orortega

**Comment by lupomontero** [comment]
@cristianca-lagash: gracias por tu respuesta y disculpa si mis comentarios sonaron un poco _tersos_ (😊)... sé que están haciendo un super esfuerzo (💪❤️).

1. Estoy de acuerdo con que el _snippet_ sirve como primer ejemplo a ver en la primera clase. Por otro lado, yo esperaba una implementación de ejemplo de un bot que se ajuste al _scope_ de los retos planteados. Este proceso, tener que _resolver_ alguno de los retos, es lo que nos debe de servir de guía para determinar el _syllabus_ y la _agenda_ (las chicas tienen que poder construir un bot similar a lo largo del curso).

> Como aclaración, a nivel de código fuente, esperaba un ejemplo de implementación de un bot dentro del scope de los retos planteados que nos pudiera servir para informar las decisiones acerca de qué necesitamos para apoyar a las chicas a completar sus retos.

2. 👍 

3. De acuerdo con que el material lo iremos construyendo y mejorando en las próximas semanas. Al mismo tiempo, creo que es fundamental que desplegar el _producto_ construido sea un requerimiento de los retos y se les comunique a lxs alumnxs desde el primer día.

4. Por supuesto, en el contenido se pueden incluir links a todos los recursos que consideres necesarios, incluido tu propio blog 😉 

5. Veo que algunos comentarios vienen de @cristianca-lagash y otros de @ccardensa, así que por si acaso he agregado ambos como _colaboradores_.

Gracias otra vez y sigo conectado para apoyar con todo lo que pueda.

Vamos 🚀

**Comment by ccardensa** [comment]
@lupomontero tranquilo somos grandes y no hay tiempo para sentirse mal jeje 😉

1- haré lo posible por tener un ejemplo que sea parecido a los retos
3- Eso haremos desde el primer día
4- 👍 
5- Me ayudaria mucho que solo dejaras el usuario @ccardensa ya que ese es mi personal y así no lo mezclo con la cuenta persona.

Seguimos dandole... go go go go

**Comment by ccardensa** [comment]
@lupomontero el demo completo quedaré al debe para esta primera clase, pero estoy trabajando para completar el desarollo durante esta semana, para poder entregar algo 100% diseñado por mi, es más estaba pensando en tomar uno de los retos para generar el demo.
         
NUEVA DEFINICIÓN DE CLASES

**CLASE #1 180m**

##INTRODUCCIÓN 15min
¿Que es Azure?
¿Que es un Bot y porque implementarlo en Azure?
¿Tipos de Bot?
¿Que utilidades le podemos dar a los bots?

--Espacio para preguntas

##Microsoft Bot Framework 15min
¿Que es Microsoft Bot Frameworks?
Tecnologias con las cuales podemos diseñar Bot en Azure
Servicios Cognitivos con Microsoft Bot Framework

--Espacio para preguntas

##Construyendo Bots (construiré bots simples para generar empatia con el código) 20min
Configurando Ambiente
Creando nuestro primer bot

**nota: en lo anterior tenemos 50min, como una introducción abreviada necesaria**

Coffe Break --espacio para preguntas

Organización de grupos
Definir Reto por grupos
Hacking

**CLASE #2 Webinar 90m**

Flujo de Trabajo - Dialogos y Estados
Interacción con usuarios
Despliegue - Registro de un bot en Bot Services en Azure
Procesamiento de Lenguaje Natural

--espacio para preguntas

**CLASE #3 180m**
Localización
Hacking
--espacio para preguntas

**CLASE #4 180m**  
Azure: Middleware y comandos globales
Hacking
--espacio para preguntas

**CLASE #5 Webinar 90m**
Despliegue en Azure App Services 
--espacio para preguntas

**CLASE #6 180m** 
Demo Day
Finalización del curso

Mi correo ccardensa@outlook.com y redes sociales estaran disponibles para consulta de las alumnas durante toda la duración del curso, obviamente despues igual pero prestaré toda la atención para responder ASAP las dudas de las alumnas.

**Comment by CaroLaboratoria** [comment]
@ccardensa dos temas de implementación del curso con respecto a lo expuesto.
1) La comunicación con las alumnas la realizamos a través de slack que se te invitará hoy a participar. Ahí crearemos un grupo especial con las alumnas para que ellas puedan realizar las preguntas, dudas, etc.
2) Lo segundo, te compartí una carpeta en google drive para guardar las presentaciones del curso.
Saludos y nos vemos hoy!

**Comment by ccardensa** [comment]
Hola @CaroLaboratoria acabo unirme a slack y veré el drive para guardar la presentación

Nos vemos

**Comment by lupomontero** [comment]
@ccardensa: gracias por el esfuerzo 💪

Podrías enviar tus cambios y contenido via pull request como acordamos? Si tienes problema con esto házmelo saber por favor para poder echarte una mano urgentemente.

> Con respecto a la definición de las clases, pensando en la primera semana, podrías ir llenando los textos de la unidad 2 con texto, links, videos, según consideres necesario y enviar pull request con tus cambios?

Esto se necesita para poder agregar el curso al LMS.

cc/ @CaroLaboratoria

**Comment by lupomontero** [comment]
Adjunto imagen de _hoja de ruta_:

![kickoff chatbot con azure - sclene18](https://user-images.githubusercontent.com/110297/34795694-1f114566-f621-11e7-8d99-7edd1c30aa97.png)

**Comment by lupomontero** [comment]
Cierro este issue por ahora. Queda pendiente redefinir syllabus en base a agenda #475

**Comment by ccardensa** [comment]
@lupomontero que rama utilizo?, estoy solucionando mi problema con git
![image](https://user-images.githubusercontent.com/25645113/34836807-c46189b6-f6d7-11e7-83ac-314a6f1e2e18.png)

Me cuentas

**Comment by lupomontero** [comment]
`14-chatbot`
