### ISSUE TITLE
05-deep-dive: definir scope de retos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#472]
Para poder determinar el scope del curso se ha implementado este _producto modelo_ de referencia:

https://github.com/Laboratoria-learning/cardify

El producto modelo cubre más o menos esto:

* JavaScript (var, let, const, funcs, objs, es6, ...)
* Implementación requerimientos del _módulo_ (API + funcionalidad)
* git (`.gitignore`, issues, fork, clone, checkout, branch, commit, push, pull, pull request, merge, ...)
* npm/`package.json`
* docs/`README.md`
* ejemplos de uso
* tests (karma, mocha, chai, ...)
* linter / guía de estilos (eslint, `.eslintrc`, ...)
* build (babel, uglify, webpack, browserify ...)
* UMD
* `.editorconfig`
* CI (travis, circle, ...)?

La idea es decidir en qué centrarnos y qué dejar fuera. En base a eso el siguiente paso es ir concretando la agenda.

cc/ @ivandevp @nerdale @FabianBravoA @AnaSalazar @brecabal @MarciaMillanao

**Comment by nerdale** [comment]
@lupomontero Estuvimos debatiendo acá en Chile lo conversado en el handoff de ayer, pensamos que este primer sprint de la especialización debería ocurrir lo siguiente:

1. En la primera semana nos gustaría nivelar y profundizar los temas de javascript vistos en el common core

2. En la segunda semana nos gustaría ya migrar a es6, tener un primer acercamiento a TDD y la creación de librerías.

3. En la tercera y última semana se desarrollaría el producto final, sería ideal que este haga sentido con todo lo visto en el sprint y que para ellas genere un valor tangible y reutilizable.

cc/ @ivandevp @FabianBravoA @AnaSalazar @brecabal @MarciaMillanao

**Comment by lupomontero** [comment]
@nerdale: gracias por el feedback 🚀🎸

Con respecto al tema de la agenda, me gustaría introducir testing antes de empezar con el resto del contenido para así poder usar tests en los seminarios y ejercicios guiados para demostrar los diferentes features del lenguaje. Qué opinan?

He estado plasmando una propuesta de estructura tanto de contenido como de agenda. Acá pueden ver las propuestas en mi fork:

* [AGENDA](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/AGENDA.md)
* [README - Syllabus, evaluación, ...](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/README.md)

La estructura la estoy creando siguiendo la convención de carpetas y markdown de la currícula para poder ir parseando el curso desde ya y siempre poder ir viéndolo en el LMS, como lo verán las chicas. He parseado y subido el curso al cohort `test` en el [LMS de staging](https://laboratoria-la-lms-staging.firebaseapp.com/cohorts/test/courses/deep-dive) y les he dado acceso para que podamos todos ir viendo el progreso/completitud directamente ahí.

Se agradece todo el feedback. Gracias!

***

Output del parser (contenido):

```
# JS Deep Dive: Crea tu propia librería usando JavaScript (deep-dive)

Duration: 17h
Units: 8
Parts: 63
Exercises: 1


## Unit 1: Reto (01-challenge)

Duration: 1.6h
Parts: 4
Exercises: 0

| 01-welcome | seminario | guiado | 20min | Presentación del Curso
| 02-challenges | seminario | guiado | 30min | Retos
| 03-teams | taller | guiado | 15min | Equipos
| 04-proposals | taller | guiado | 30min | Propuesta de reto

## Unit 2: Entorno de desarrollo (02-env)

Duration: 1.6h
Parts: 8
Exercises: 0

| 00-opening | lectura | self-paced | 5min | Apertura
| 01-shell | lectura | self-paced | 15min | Shell de UNIX
| 02-git+github | lectura | self-paced | 15min | Git + GitHub
| 03-node+npm | lectura | self-paced | 15min | Node.js + npm
| 04-babel | lectura | self-paced | 10min | Babel
| 05-editor | lectura | self-paced | 10min | Editor de texto
| 06-seminar | seminario | guiado | 20min | Ejemplos y ejercicios guiados
| 07-closing | lectura | self-paced | 5min | Cierre

## Unit 3: Unit Testing / Pruebas unitarias (03-testing)

Duration: 1.8h
Parts: 8
Exercises: 0

| 00-opening | lectura | self-paced | 5min | Apertura
| 01-basics | lectura | self-paced | 15min | Qué es un test unitario?
| 02-frameworks | lectura | self-paced | 15min | Frameworks
| 03-tdd | lectura | self-paced | 15min | TDD
| 04-assertions | lectura | self-paced | 15min | Aserciones
| 05-runners | lectura | self-paced | 15min | Test runners
| 06-seminar | seminario | guiado | 20min | Ejemplos y ejercicios guiados
| 07-closing | lectura | self-paced | 5min | Cierre

## Unit 4: Paquetes y módulos (04-packages)

Duration: 1.2h
Parts: 5
Exercises: 0

| 01-package-json | lectura | self-paced | 15min | package.json
| 02-commonjs | lectura | self-paced | 15min | CommonJS
| 03-es6-modules | lectura | self-paced | 15min | ES6 Modules
| 04-seminar | seminario | guiado | 20min | Ejemplos y ejercicios guiados
| 05-closing | lectura | self-paced | 5min | Cierre

## Unit 5: Fundamentos de JavaScript (05-foundations)

Duration: 4.5h
Parts: 14
Exercises: 1

| 00-opening | lectura | self-paced | 5min | Apertura
| 01-variables-values-and-types | lectura | self-paced | 15min | Variables, Tipos de datos y Operadores
| 02-flow-control | lectura | self-paced | 15min | Control de Flujo
| 02-operators | lectura | self-paced | 15min | Operadores
| 04-funcs | lectura | self-paced | 20min | Funciones
| 05-scope | lectura | self-paced | 10min | Scope
| 06-arrays | lectura | self-paced | 15min | Arreglos
| 07-objects | lectura | self-paced | 15min | Objetos
| 08-destructuring | lectura | self-paced | 15min | Desestructuración de arrays y objetos
| 09-built-ins | lectura | self-paced | 15min | Objetos preconstruidos
| 10-strings | lectura | self-paced | 5min | Template Strings
| 11-practice | practice | self-paced | 1h | Ejercicios
| 12-seminar | seminario | guiado | 1h | Ejemplos y ejercicios guiados
| 13-closing | lectura | self-paced | 5min | Cierre

## Unit 6: Asincronía: Callbacks, eventos y promesas (06-async)

Duration: 2.4h
Parts: 9
Exercises: 0

| 00-opening | lectura | self-paced | 5min | Apertura
| 01-callbacks | lectura | self-paced | 15min | Callbacks
| 02-events | lectura | self-paced | 20min | Events handling
| 03-bubbling-capturing | lectura | self-paced | 15min | Bubbling vs Capturing
| 04-this-eventtarget | lectura | self-paced | 10min | `this` vs `event.target`
| 05-promises | lectura | self-paced | 15min | Promesas
| 06-practice | practice | self-paced | 30min | Ejercicios
| 07-seminar | seminario | guiado | 30min | Ejemplos y ejercicios guiados
| 08-closing | lectura | self-paced | 5min | Cierre

## Unit 7: Manejo de errores (07-errors)

Duration: 2.2h
Parts: 8
Exercises: 0

| 00-opening | lectura | self-paced | 5min | Apertura
| 01-strict-mode | lectura | self-paced | 15min | Modo Estricto
| 02-try-catch | lectura | self-paced | 15min | Try...catch
| 03-callbacks | lectura | self-paced | 15min | Errores en callbacks
| 04-promises | lectura | self-paced | 15min | Errores en promesas
| 05-practice | practice | self-paced | 30min | Ejercicios
| 06-seminar | seminario | guiado | 30min | Ejemplos y ejercicios guiados
| 07-closing | lectura | self-paced | 5min | Cierre

## Unit 8: Browser APIs (08-browser-apis)

Duration: 1.8h
Parts: 7
Exercises: 0

| 00-opening | lectura | self-paced | 5min | Apertura
| 01-dom-traversing | lectura | self-paced | 15min | Recorrido del DOM
| 02-dom-manipulation | lectura | self-paced | 15min | Manipulación del DOM
| 03-browser-reflow | lectura | self-paced | 10min | Redibujo del navegador
| 04-practice | practice | self-paced | 30min | Ejercicios
| 05-seminar | seminario | guiado | 30min | Ejemplos y ejercicios guiados
| 06-closing | lectura | self-paced | 5min | Cierre
```

cc/ @ivandevp @FabianBravoA @AnaSalazar @brecabal @MarciaMillanao @AnaSalazar

**Comment by lupomontero** [comment]
Una cosa que olvidé mencionar es que me gustaría dejar jQuery como una unidad opcional. Thoughts?

**Comment by AnaSalazar** [comment]
@nerdale Me suena coherente el como proponen en Chile el distribuir las 3 semanas.

@lupomontero Te refieres a ver TDD antes de migrar a ES6? 
En el caso de que jQuery sea opcional, van a tener guía de parte de las teachers?
Más adelante daremos jQuery a todas de manera pareja?

cc/ @ivandevp @FabianBravoA @brecabal @MarciaMillanao

**Comment by nerdale** [comment]
La primera semana de este sprint comienza el próximo miércoles, si bien entendemos la importancia de testing, creemos necesario primero reforzar todo lo visto de javascript y profundizar en esos 3 primeros días, por ejemplo aún les falta entender y saber que existen forEach/map/reduce/filter, manejar en profundidad objetos etc (por nombrar un par de temas) los cuales son súper necesarios. Teniendo esto claro ya podemos adentrarnos en testing y la migración hacia es6.

Sobre jQuery opcional nos parece perfecto, ya tuvieron un acercamiento en el common core y eso les da el acceso a profundizar autonomamente si así lo quieren.

Que piensan?

cc/ @ivandevp @lupomontero @FabianBravoA @AnaSalazar @brecabal @MarciaMillanao

**Comment by lupomontero** [comment]
Ok. Me parece sensato. Me hubiera gustado hacer la prueba pero ganan por mayoría 😊 

Voy a cambiar el orden como sugieren.

Mientras tanto, agradecería un montón cualquier feedback sobre las lecturas que acabo de subir de la unidad de testing (quizás así entienda mejor la idea que tengo en mente).

* [00-opening](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/03-testing/00-opening/README.md)
* [01-basics](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/03-testing/01-basics/README.md)
* [02-frameworks](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/03-testing/02-frameworks/README.md)
* [03-assertions](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/03-testing/03-assertions/README.md)

Pueden dejar comentarios directamente sobre el PR: https://github.com/Laboratoria/curricula-js/pull/471

**Comment by FabianBravoA** [comment]
Yo aun debo un "cheatsheet"/"torpedo" o como lo llamen en su país para GIT, pero podría ser una buena forma de darles un poco más de acercamiento a JQuery a las alumnas. 
Al igual que @nerdale pienso que el foco debe estar en javascript. Y agrego que deberíamos ver, si es posible, promesas, aunque sea nombrarlas para que ellas aprendan a usarlas por su cuenta si es que el curso no da más tiempo.

**Comment by giancorzo** [comment]
Hola a todos, Lupo me pidió un poco de feedback. 

Quizá ya están con los tiempos ajustados pero me parece interesante el planteamiento de Lupo,  Testing es una forma de desarrollo en sí independiente del tema que toquen y toma su tiempo dominarla sobre todo si estas acostumbrado a sólo hacer el código de frente. 

Podrían incluir testing al nivel de saberlo usar y correrlo (quizá para los ejercicios guiados y que ellas luego hagan el código con testing opcionalmente). 

Como Git, va a ser complicado de entender al principio pero luego le van a ver el valor.

Sobre el tema de map, reducers, filters me parece que debe enmarcarse dentro de un curso funcional más que un tema suelto (quizá ya lo están haciendo así y estoy hablando de más). 

Promises también es chevere sobre todo si lo combinan con los temas de funcional. 

La agenda me pareció algo extensa cada tópico de por si es un mundo a mi parecer. 

@lupo ahora leo tus links que has puesto y te comento

**Comment by lupomontero** [comment]
Gracias a todxs por el feedback! Se agradece mucho :star:

Acá pueden cómo estamos presentando los retos: https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/01-challenge/02-challenges/README.md

Cierro este issue por ahora. Si tienen cualquier sugerencia o encuentran errores porfa abran nuevos issues más específicos:

💪 🚀
