### ISSUE TITLE
05-deep-dive: definir agenda

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#473]

**Comment by lupomontero** [comment]
Primera propuesta de [agenda](https://github.com/lupomontero/curricula-js/blob/05-deep-dive/05-deep-dive/AGENDA.md)

cc/ @ivandevp @FabianBravoA @AnaSalazar @brecabal @MarciaMillanao @AnaSalazar

**Comment by ivandevp** [comment]
@lupomontero al final, ¿cómo queda la agenda? y ¿qué contenido está pendiente?

**Comment by lupomontero** [comment]
Ésta es la agenda propuesta: https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/AGENDA.md

**Comment by lupomontero** [comment]
Por ahora queda cerrada la agenda como está. Finalmente quitamos las unidades de paquetería y jQuery, además de arrancar con fundamentos de JavaScript (repaso) la primera semana en vez de arrancar con testing, que ahora está programado para la segunda semana.
