### ISSUE TITLE
14-chatbot: redefinir syllabus en base a agenda

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#475]
Por ahora solo hemos _publicado_ las unidades 1 y 2. Ahora necesitamos completar el _syllabus_ del curso de acuerdo a la agenda presentada hoy en [_kick-off_](https://github.com/Laboratoria/curricula-js/issues/464#issuecomment-356738557).

Esto require:

- [ ] Modificar el índice del [_syllabus_ en el README.md principal del curso](https://github.com/Laboratoria/curricula-js/tree/14-chatbot/14-chatbot#syllabus).
- [ ] Crear/renombrar las carpetas de unidades y partes (1er y 2ndo nivel del anidación dentro de carpeta `14-chatbot`).
- [ ] Crear los `README.md`s correspondientes para cada parte (placeholders con meta data - tipo, formato y duración)

**Comment by ccardensa** [comment]
Hola @lupomontero estoy subiendo la nueva información y mi usuario no tiene permisos para hacer push

![imagen](https://user-images.githubusercontent.com/25645113/35030054-839bbc1c-fb3c-11e7-9667-e60435c5d86b.png)

me avisas cuando tenga los permisos para subir las modificaciones y contenido correspondiente

**Comment by lupomontero** [comment]
@ccardensa: parece que estás tratando de hacer `push` directamente al repo alojado en la organización de @Laboratoria en GitHub. Para poder _enviar_ cambios, lo primero debería ser que hagas un _fork_ de nuestro repo. En tu propio fork tienes todos los permisos, y una vez hayas hecho `push` a tu propio _fork_, de ahí nos puedes enviar un _pull request_.

Como referencia, acá puedes ver la documentación oficial de GitHub sobre este tema:

* https://help.github.com/articles/fork-a-repo/

Y la descripción del proceso de colaboración de este repo:

* https://github.com/Laboratoria/curricula-js/wiki/Colabora

Cualquier duda me avisas... voy a estar conectado (por acá y/o slack).

**Comment by ccardensa** [comment]
tienes toda la razón, estoy acostumbrado a trabajar directamente sobre los repo, ahora me queda una duda... como puedo anexar imagenes?

**Comment by lupomontero** [comment]
Con respecto a las imágenes, hay varias opciones, ... pero personalmente recomiendo esta solución:

https://github.com/Laboratoria/curricula-js/issues/114#issuecomment-358324487

Al final lo más importante es que las imágenes queden an algún tipo de CDN con URLs permanentes.

**Comment by ccardensa** [comment]
Ok, me quedo clarito lo de las imagenes...

@lupomontero acabo de subir la clase de hoy a git, favor integrar al LMS

**Comment by lupomontero** [comment]
El temario queda redefinido [acá](https://github.com/Laboratoria/curricula-js/issues/464#issuecomment-356738557), pero falta completar el _syllabus_ en el [README.md](https://github.com/Laboratoria/curricula-js/tree/14-chatbot/14-chatbot#syllabus) principal del curso (y el contenido correspondiente en las subcarpetas que sean necesarias).

@ccardensa, podrías porfa hacer los cambios sugeridos en el primer comentario de este thread? Si tienes cualquier consulta no duded en preguntar.
