### ISSUE TITLE
13-angular - Ejercicio fuera de alcance en unidades 2 y 3

### ISSUE THREAD

**Issue by FabianBravoA** [Laboratoria/curricula-js#478]
Hola a todos,

Revisando el ejercicio de las unidades 2 y 3, están mal planteados y en el orden incorrecto.
Para la unidad 2 no se ha visto servicios, y se pide crear un servicio. Para la unidad 3 se pide lo mismo que en la 1, siendo que debería ser progresivo (probablemente es un error de copia de las unidades).

Saludos.

**Comment by lupomontero** [comment]
@FabianBravoA: gracias por reportar el problema 👍 

@aldo-roman: Fabián es el instructor que está dirigiendo este curso en Santiago. Podrías echar un vistazo a esto?

Gracias a los dos!

**Comment by aldo-roman** [comment]
hola @lupomontero y @FabianBravoA 

Me he perdido bastante en el repo, no termino de comprender la estructura que tienen para los cursos y no encontré el syllabus en una sola vista.

Pueden revisar cómo lo planteé originalmente en el fork que hice:
https://github.com/aldo-roman/curricula-js/tree/master/30-angular-fundamentals

En ese planteamiento:
- En la semana 02 se estudia formularios, y se pide crear un formulario simple
- En la semana 03 se pide el consumo de servicios, mientras que en la semana 01 se pide solo crear un componente que muestre un texto desde una variable (data binding)

saludos!

**Comment by FabianBravoA** [comment]
Probablemente el cambio quedó en algún pull-request olvidado. ¿Puedes comprobar si hiciste el pull-request o en caso contrario mandarlo? Porque en el LMS se ve mal y está como puse en el issue.

Saludos y muchas gracias Aldo por la respuesta.

**Comment by lupomontero** [comment]
@aldo-roman: el contenido del curso está en la carpeta [`13-angular` de la rama `13-angular`](https://github.com/Laboratoria/curricula-js/tree/13-angular/13-angular). Podrías revisar las diferentes _partes_ de cada _unidad_ (en las subcarpetas) para ver si esto tiene sentido? El contenido de las subcarpetas es lo que ven las chicas en el LMS.

**Comment by lupomontero** [comment]
En la versión actual de la currícula no estamos usando este contenido ya que estaba un poco incompleto y todo cambia muy rápido. Hoy por hoy preferimos apuntar a nuestras estudiantes a la documentación oficial y otros recursos externos (tutoriales, blog posts, ...).

Cerrando por _inactividad_.
