### ISSUE TITLE
Ops Team Feedback: JS DEEP DIVE / especialización

### ISSUE THREAD

**Issue by AnaSalazar** [Laboratoria/curricula-js#487]

**Comment by lupomontero** [comment]
Hola @AnaSalazar, veo que se ha abierto este issue, pero todavía no hay _comentario_ o _sugerencia_... imagino que el plan es ir añadiéndolos según los vayan recopilando? 💪

**Comment by AnaSalazar** [comment]
Hola @lupomontero 

Así es, aun se encuentra vacío. 
Ayer se lanzó el hand-off de este contenido y los teachers tienen unos días para revisarlo y entonces ir añadiendo lo que notan. También se les adjuntó el issue donde se enlistan los pendientes por si gustan colaborar.

**Comment by lupomontero** [comment]
Disculpen por la super demora... hoy he subido nuevas lecturas que faltaban en las unidades 5 y 6. Me tomado la libertad de empujar los cambios directamente a la rama [05-deep-dive](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive) y actualizar el curso en el LMS en producción.

Las nuevas lecturas son:

* [05-async/00-opening](https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/05-async/00-opening/README.md)
* [05-async/01-callbacks](https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/05-async/01-callbacks/README.md)
* [05-async/05-promises](https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/05-async/05-promises/README.md)
* [06-errors/03-callbacks](https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/06-errors/03-callbacks/README.md)
* [06-errors/04-promises](https://github.com/Laboratoria/curricula-js/blob/05-deep-dive/05-deep-dive/06-errors/04-promises/README.md)

Se agradece cualquier tipo de feedback.

cc/ @Laboratoria/developers

**Comment by AnaSalazar** [comment]
Genial @lupomontero 

Lo checo

**Comment by lupomontero** [comment]
Se han añadido también un par de ejercicios en la unidad de 06-errors (y publicado en el LMS):

* https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/06-errors/05-practice

cc/ @brecabal @FabianBravoA @nerdale @bosqueinvierno @MarciaMillanao @ivandevp

**Comment by AnaSalazar** [comment]
Este issue se cierra ya que se ha finalizado esta unidad y ninguna de las sedes está usando este contenido actualmente. 

Para las futuras mejoras e iteraciones de este contenido se crearán nuevos issues en su debido momento.
