### ISSUE TITLE
Ops Team Feedback: SPA / especialización

### ISSUE THREAD

**Issue by AnaSalazar** [Laboratoria/curricula-js#499]

**Comment by FabianBravoA** [comment]
A pesar de que hay preguntas en el quiz sobre puertos en la URL, no hay material sobre ello, ni ninguno de los links lo menciona en la unidad correspondiente.

**Comment by FabianBravoA** [comment]
Falta una sección especial para los ejercicios, por ahora solo son links a ejercicios aportados por chile a través de google docs.

**Comment by AnaSalazar** [comment]
@FabianBravoA Ha quedado solucionado en este momento lo de la falta de información del tema de URL´s

Y estamos en este instante trabajando sobre los ejercicios. Gracias por tus observaciones **:-D**

**Comment by AnaSalazar** [comment]
Este issue se cierra ya que se ha finalizado esta unidad y ninguna de las sedes está usando este contenido actualmente.

Para las futuras mejoras e iteraciones de este contenido se crearán nuevos issues en su debido momento.
