### ISSUE TITLE
Revisar, feedback y sugerencias de cursos bootcamp

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#5]
- [x] Actualizar outline del bootcamp y el [`README.md`](https://github.com/Laboratoria/curricula-js/blob/master/README.md)
- [x] Propuestas de _productos_
- [x] Desarrollar un poco el concepto para uno de los _cursos_ del bootcamp

**Comment by chamodev** [comment]
¡Gracias por la nueva propuesta del Bootcamp @ivandevp!. Ahora que ya la tenemos, podemos retomar el feedback en este issue.

En general, me parece que tenemos la dirección correcta y es un súper punto de partida. En base a la experiencia, sabemos que conforme vayamos desarrollando el contenido específico del curso, esa visión general irá adaptándose. 

Por ahora, sólo tengo un par de comentarios:

1. Creo que aún estamos en una etapa preliminar sobre la visión de tener el track de `UI Developer` (necesitamos, por ejemplo, entender y puntualizar muy bien con el equipo de inserción laboral la diferencia entre `UI Dev` y `Front-End Dev`). Por eso, creo que lo mejor sería excluir ese track por ahora, o al menos dejar claro que una "idea/concepto" de track
2. Me parece que los conceptos del curso de `JS Deep Dive` deben haberse cubierto antes, así que haría un merge de ese curso con `03. Web Development: Getting Deeper` y/o con `02. Web Development: Getting Started`
3. En `Educación Continua` eliminaría los cursos que ahora son parte del Bootcamp en esta nueva visión: `The Web Stack` imagino que será parte de `Internet Deep Dive` o de alguno de los de `Web Devs`; `Node.js` será parte de `NodeJS` (al menos que hagamos un curso tipo "You Don't Know Node.js"); y `Algos` y `Estructuras de Datos` serán parte de `Computer Science Intro`. Cierto?

Seguiré dandole una pensada y si veo algo te hago un PR directo.

¡Gracias!

**Comment by ivandevp** [comment]
@chamodev,  estos son mis comentarios:

1. De acuerdo, nos hace falta entender el perfil de `UI Dev`, desde mi punto de vista, hace referencia a las estudiantes que terminan como `prototypers` en los bootcamps actuales.

2. El problema de meter `JS Deep Dive` en este punto puede que no sea tan necesario para las que van hacia el perfil de `UX` y pueda generar una frustración en ellas o retrasar el ritmo del aula debido a que tal vez optemos por hacer repasos o ayudantías. Esto al menos he podido notar en las promociones pasadas.

3. Los cursos de educación continua que ahora serían parte del bootcamp, me parece que deben mantenerse aun en ambos, considero que en el bootcamp no vamos a poder meter todos los temas desde un inicio, menos en esta primera iteración de un nuevo modelo. Dejaría que los cursos de educación continua traten lo mismo pero con mayor profundidad, teniendo en cuenta que las estudiantes ahora tendrán al menos nociones de estos temas.

Saludos!

**Comment by lupomontero** [comment]
Cierro este issue ya que la conversación ha evolucionado a la nueva propuesta de @ivandevp en [actualización del flujo del bootcamp](https://github.com/Laboratoria/curricula-js/issues/81) y [PR correspondiente](https://github.com/Laboratoria/curricula-js/pull/82).
