### ISSUE TITLE
01-intro: Ops Team Feedback (GDL)

### ISSUE THREAD

**Issue by AnaSalazar** [Laboratoria/curricula-js#524]
Comentarios @lupomontero respecto a contenido:

- [x] En la primera parte de la unidad 1, se hace referencia al 3 de agosto. Esto es una fecha obsoleta?
- [x] Hay que verificar también la sección de [horarios de consulta](https://github.com/MaiaRojas/curricula-js/blob/231239d0d6c10b35d69f22b61e9a18b548f1e83a/01-intro/01-intro/00-welcome-and-orientation/README.md#2-horas-de-consulta)
- [x] En esta primera parte, también se hace referencia al "syllabus" específicamente del "pre-trabajo". Esto puede resultar un poco confuso en relación a la estructura de cohorts y cursos del LMS. Creo que tenemos varias opciones: una sería sacar este texto de esta parte y asumir que la estructura que comunica el LMS es suficiente para que las postulantes entiendan donde están en el flujo, o adaptamos el texto, o incluso podría ser una opción partir el curso en 2, pre-trabajo y pre-admisión, en vez de unidades 1 y 2 el pre-trabajo y unidad 3 la pre-admisión.
- [x] El contenido en sí creo que está bastante bien, quizás trataría de cambiar un poco la narrativa para hacerlo on poco más en estilo code along.
- [x] Con respecto a los quizzes en general, y en particular los de las unidades 2 y 3, creo que quizás están muy enfocados en detalles y sutilezas del lenguaje que muchos desarrolladores no sabrían responder, o no sin antes ir y ejecutar el código para ver el resultado. Qué les parece quitar algunas de estas preguntas? (ver comentarios al PR).
- [x] Falta migrar los ejercicios

Observaciones:

- [x] Pregunta del quiz sobre la diferencia entre `null` y `undefined`
- [x] Pregunta de quiz sobre tipo de dato de `Infinity`

Comentarios de @MaiaRojas:

- [x] Falta actualizar link de grupo de Facebook

**Comment by MaiaRojas** [comment]
Solo como comentario en este nuevo contenido se ha agregado una unidad adicional de UX, a solicitud de selección. @danielasarzosa , no se si esto  aplica al pretrabajo de Guadalajara.
[ux-design](https://github.com/MaiaRojas/curricula-js/tree/01-intro/01-intro/03-ux-design)

**Comment by lupomontero** [comment]
Ya solo falta migrar los ejercicios de la unidad 4 que actualmente están en [replit](https://repl.it/classroom/invite/HWss9Vr)... esto queda pendiente... alguien se anima a echarme una mano?

cc/ @MaiaRojas @AnaSalazar

**Comment by AnaSalazar** [comment]
Migrarlos! Eso cómo se hace? :sweat_smile: @lupomontero

**Comment by MaiaRojas** [comment]
@AnaSalazar  esta fácil, si quieres hacen un ejemplo juntas. La idea es pasar los ejercicios que estan en replit  para que las estudiantes puedan ejecurlos.
![code](https://user-images.githubusercontent.com/25912510/37219934-02423784-2393-11e8-9398-24e795466f0b.png)

**Comment by AnaSalazar** [comment]
Solo para actualizar este issue y que no se cierre:

Estoy haciendo la migración de los ejercicios, que ya es el último pendiente de este issue. Solo me falta crear los tests.

**Comment by lupomontero** [comment]
@AnaSalazar: gracias por el update 👍 

Ahora que ha cambiado la estructura de "ramas" (branches) del repo estos cambios habría que verlos primero en la rama `v1.x` y después den `v2.x`...

**Comment by AnaSalazar** [comment]
Se cierra este issue porque ya se han terminado todos los pendientes de la lista
