### ISSUE TITLE
Limpieza de ramas obsoletas

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#530]
Estoy haciendo un poco de limpieza en el repo y he encontrado varias ramas _stale_ (que parecen obsoletas). Me pueden porfa confirmar si se pueden borrar estas ramas:

![image](https://user-images.githubusercontent.com/110297/37117300-d9c60e0e-221e-11e8-94ae-8930f3ff3ad1.png)

https://github.com/Laboratoria/curricula-js/branches/stale

cc/ @ivandevp @brecabal @diegovelezg

**Comment by lupomontero** [comment]
Las ramas `revert-149-08-deep-dive` y `GitbookJSDeepDive` ya se han borrado con el permiso de @brecabal.

Faltan las otras... (@diegovelezg, @ivandevp)

**Comment by lupomontero** [comment]
Todavía quedan algunas ramas _stale_... @diegovelezg e @ivandevp pueden confirmar si se pueden borrar?

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/110297/38386925-f026421c-38db-11e8-833f-2e4ea76570cb.png">

https://github.com/Laboratoria/curricula-js/branches/stale

**Comment by ivandevp** [comment]
¿Qué hacemos con la rama de `xy-hse`?

cc/ @alejandrarv

**Comment by alejandrarv** [comment]
@ivandevp estamos reestructurando los talleres así que probablemente todos vayan a cambiar un poco, creo que podemos borrar esa rama e ir subiendo los nuevos talleres conforme los tengamos, qué opinas?

**Comment by ivandevp** [comment]
Listo! Rama `xy-hse` eliminada 💪

**Comment by ivandevp** [comment]
Solo faltaría la rama `GitbookPreadMisión`

cc/ @diegovelezg

**Comment by lupomontero** [comment]
Cerrando issue por ahora...
