### ISSUE TITLE
02-basic-programing: Iteración y revisión de contenido

### ISSUE THREAD

**Issue by AnaSalazar** [Laboratoria/curricula-js#533]
En esta unidad en el quizz y requizz las preguntas que se plantean son buenas y sirven mucho para afianzar los conocimientos que son base para seguir avanzando, pero siento que son muchas (32 y 25) para solo 30 minutos. 

Que opinan:
- Reducimos la cantidad de preguntas?
- Aumentamos el tiempo?
- Otra sugerencia?

**Comment by lupomontero** [comment]
@AnaSalazar: gracias por abrir este issue.

Como aclaración, esto hace referencia a los quizzes de la unidad `01-basic-programming` dentro del curso `02-basic-programming` (la nomenclatura resulta un poco confusa).

A mí me parece buena idea que los quizzes sean un poco (o bastante) más cortos, pero antes de sacar la tijeras y ponernos a recortar me gustaría que veamos si quizás tiene sentido usar las preguntas que saquemos en otro lado. De esos dos quizzes pueden salir 4 o más...

Por otro lado, he creado otro issue con ideas para esta segunda iteración de este curso:

https://github.com/Laboratoria/curricula-js/issues/535

**Comment by AnaSalazar** [comment]
@lupomontero Si, totalmente de acuerdo. Me parece excelente la creación del otro issue y tal vez me parece podemos cerrar este para trabajar esto en el nuevo ya que al reestructurar el curso 02-basic-programming podemos separar las preguntas dependiendo del tema

**Comment by AnaSalazar** [comment]
Se cierra este issue para seguir trabajando todo junto desde el issue [#535](https://github.com/Laboratoria/curricula-js/issues/535)
