### ISSUE TITLE
Separación de retos, syllabus y agenda

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#534]
El tiempo va pasando... y la primera iteración de nuestro bootcamp usando este repo está por concluir... 🎉💪 ... así que ya estamos poniéndonos las 🔋para pulir y mejorar los cursos que se han ido creando gracias al esfuerzo de todo el equipo y colaboradores externos... gracias ❤️

Como todo proyecto, estamos en constante evolución y su feedback es esencial.

Desde hace un tiempo estamos poco a poco evitando mezclar el _syllabus_ de la _agenda_. Esto básicamente quiere decir que las clases presenciales tratamos de no incluirlas como _partes_ dentro de las _unidades_, y en vez de eso estamos agregando un archivo con el nombre `AGENDA.md` ([ejemplo](https://github.com/Laboratoria/curricula-js/blob/01-intro/01-intro/AGENDA.md)), que sirve más como sugerencias de sesiones guiadas y son notas dirigidas a instructorxs y no necesariamente directamente a las alumnas.

La idea detrás de esto es que nos hemos ido dando cuenta de que tiene muchos beneficios manejar _syllabus_ y _agenda_ por separado. Por un lado, la agenda depende de cada ejecución (está amarrada a fechas, necesidades particulares de cada cohort y equipo técnico), mientras que el _syllabus_ debería ser completamente self-paced (en un mundo ideal) y no estar amarrado a ninguna fecha ni progreso lineal o cronológico. De esta forma, poco a poco queremos ir haciendo más contenido disponible a las alumnas para que puedan elegir y usarlo como referencia o hacerlo en su propio tiempo.

Dentro del contexto de un _cohort_, obviamente podemos y queremos pedir a las alumnas que completen ciertos cursos, y en cierto orden, pero aspiramos a que cada una pueda avanzar a su ritmo y consultar las cosas que le sean de mayor interés. Este cambio de enfoque también facilita el "reuso" de los cursos, ya que el _syllabus_ no depende de fechas o sesiones guiadas que varían de ejecución en ejecución.

Vale la pena mencionar que se está desarrollando un [_feature_ de Agenda en el LMS](https://github.com/Laboratoria/lms.laboratoria.la/issues/160) para que cada cohort (ejecución) pueda organizar su agenda de sesiones presenciales independientemente de la currícula compartida en GitHub.

cc/ @ivandevp @chamodev @diegovelezg @Laboratoria/instructores-bootcamp @Laboratoria/developers

**Comment by KarlaRejas** [comment]
Hola!, después de la reunión que tuvimos con Lupo, estoy de acuerdo en que el LMS sea la herramienta para las estudiantes, donde ellas encuentren lo que necesitan, en material, y que lo demás perteneciente a ejecución se haga en la agenda. 
Ya se que los están trabajando, pero si es muy importante que la agenda se pueda armar sola en base a tiempos que pongamos y los sugeridos. Actualmente lo hacemos manualmente en un excel, y si hay un cambio hay que cambiarla, incluso para que las estudiantes puedan verla. :)

**Comment by lupomontero** [comment]
Cierro este issue ya que esto se puede considerar hecho :muscle:
