### ISSUE TITLE
02-basic-programing: v2

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#535]
En esta iteración del curso las prioridades que quiero poner sobre la mesa son:

1. Me gustaría cambiar la estructura general del curso. Por el momento tenemos 3 unidades (`00-welcome`, `01-basic-programming` y `02-final-products`). De estas 3 unidades la primera y la última son bien cortitas, y con poco contenido, mientras que la unidad 2 es enorme y contiene prácticamente todo el contenido (técnico y self-paced). Mi propuesta es separar la unidad en varia unidades, (quizás una sobre `shell` y `git`, otra sobre `arrays` otra sobre `objetos`. De esta forma creo que puede ser un poco más friendly... además de permitirnos "esparcir" los quizzes y ejercicios en bloques más chicos y específicos de cada unidad.

2. Separar agenda de syllabus (ver #534)

cc/ @ivandevp @chamodev @AnaSalazar

**Comment by AnaSalazar** [comment]
@lupomontero Estoy de acuerdo con lo que propones. Si hacemos esto, nos ayuda a resolver lo que se había mencionado acerca de lo extenso de los quizzes ( ver [#533](https://github.com/Laboratoria/curricula-js/issues/533)) 

cc/ @ivandevp @chamodev

**Comment by memecast** [comment]
Hola @lupomontero, yo estoy muy de acuerdo con esta propuesta de separar los temas y tambien estoy de acuerdo con @AnaSalazar  en que se refactoricen los quizzes, porque  son demasiado  largos.

**Comment by IntiDev** [comment]
@lupomontero Me parece muy acertada la decisión de separar el contenido, ya que como mencionan es  muy extensa ya que se pretende abarcar 4 temas diferentes en una sola unidad y por tanto los quizzes se vuelven demasiado largos. 
Personalmente creo que estaría bien separarla en 2 unidades 1 (como ya mencionaste) sobre shell y git y la otra sobre arreglos y objetos, ya que en esta segunda se abarcan los mismos puntos con ambos enfoques (definición, manipulación de data, vídeos de ejemplo) lo cual me parece de mucho valor para las estudiantes. ¡Saludos!

**Comment by lupomontero** [comment]
Actualizo este issue para mantenerlo al día con las últimas conversaciones que hemos ido teniendo en persona, llamadas, chats, ...

Como parte de esta propuesta para redefinir este curso creo que tendría sentido separar este curso de la siguiente manera:

* `00-welcome` es una introducción a la experiencia y metodología de Laboratoria. Creo que tiene sentido sacar esta unidad de la currícula de JS y ponerla en otro lugar. De hecho creo que necesitamos crear (o quizás reusar) otro repo donde menejar contenidos de currícula que no sean específicos de JS (por ejemplo esta unidad, pero también debería servir para cursos que no tocan JS que actualmente viven en la currícula - `18-data-visualization`, `25-solutions-architecture` - además de los cursos de liderazgo digital, y otros). Lo que no me queda claro es cómo se debería _llamar_ este otro track donde poner los contenidos comunes para todxs (ya se JS, UX, L4B, ...).

* La unidad de `01-shell+git` creo que tendría más sentido como dos cursitos independientes: `x-nix shell` y `control de versiones`.

* Las unidades `02-arrays` y `03-objects` son las únicas que dejería como parte de este curso, y las acompañaría con la mayoría del contenido de la unidad [03-foundations del curso 05-deep-dive](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/03-foundations)
  - Intro a testing ([basics](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/04-testing/01-basics), [frameworks](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/04-testing/02-frameworks), [assertions](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/04-testing/03-assertions), [browser](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/04-testing/04-browser)) [L]
  - Vars, vals, types [L]
  - Operators [L]
  - Flow control 
  - Funcs and scope
  - Strings [M]
  - Data structures (arrays, objects) [M]
  - Built-ins (std lib)

* `04-final-products`: Los productos propuestos para este _curso_ son el _cifrado césar_ y _validación de tarjeta_ (algo Luhn). Como ya hemos conversado, parte de la propuesta es que los retos queden fuera del _contenido_, así que se moverían a una carpeta de _retos_ (que todavía no existe en la currícula).

**Comment by AmaliaRiveraC** [comment]
Acá en Ciudad de México cuando dimos la unidad de JS Deep Dive, previamente nos vimos en la necesidad de dar unas sesiones sobre callbacks para luego entrar en el tema de métodos de arrays (forEach, map, filter, reduce y sort (ese fue nuestro alcance)), como ejercicio les dejamos hacer e hicimos nuestros propios métodos para entender la lógica que existe detrás de éstos. Esto porque hasta ese punto del bootcamp no había material dentro de la currícula para estudiar estos temas, los cuales nos parecían de suma importancia, ya que en nuestra generación si se habían tocado y nos habían dado la oportunidad de mejorar el nivel de nuestro desarrollo.
