### ISSUE TITLE
11-react: Ops team feedback

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#538]
Abro este issue para que tengamos un lugar donde manejar el feedback sobre el curso de `React` que actualmente está corriendo en Lima y Santiago con vistas a su próxima ejecución en Ciudad de México.

Todo el feedback, sugerencias y dudas son bienvenidas. Lxs que estén ejecutándo el curso en este momento (@alejandrarv, @joalbertg, @michellesegv, @developerVilchez y @RuthMeryCardenas en Lima, y @brecabal, @FabianBravoA, @nerdale, @MarciaMillanao y @bosqueinvierno en Santiago) porfa compartan sus experiencias para que el equipo de CDMX (@LucileBaratier, @indie-rok y @shirley-suarez) pueda aprovechar esos aprendizajes.

Off-topic: Alguien sabe si Valentina está en GitHub?

cc/ @chamodev @merunga @ivandevp

**Comment by brecabal** [comment]
Si @lupomontero , es @valesmithb

**Comment by shirley-suarez** [comment]
@lupomontero hemos estado revisando como estructurar nuestras clases y nos gustaría que nos dijeras ¿Por qué razón la unidad 5 de "Estado global" (que contiene Redux) antes que la unidad 6 "React OOP : ciclo de vida, estados" y porque desde la unidad 4 (componentes) ya no existen quizes?.

**Comment by indie-rok** [comment]
Complementando a @shirley-suarez , también me gustaría preguntar si hay alguna razón en especifica por la cual no hubo algún recurso en el curso acerca de yarn/npm? Se asumió que se cubrió en deep dive? Si es asi? Podriamos agregar algún recurso nosotros en algún lado? Algunas estudiantes aún tienen dudas.

Saludos @lupomontero @merunga

**Comment by lupomontero** [comment]
@shirley-suarez, @indie-rok: gracias por las preguntas/feedback 👍

Respondiendo a sus preguntas...

***

> ¿Por qué razón la unidad 5 de "Estado global" (que contiene Redux) antes que la unidad 6 "React OOP : ciclo de vida, estados" (@shirley-suarez)

El motivo por el que se decidió primero introducir componentes como funciones puras, después estado global (con redux) y finalmente OOP, es porque nos parece que de esa forma la complejidad va aumentando de forma gradual.

Un componente _stateless_ es más simple a nivel de API e implementación, y no requiere haber visto el paradigma de OOP ni _clases_ de ES6. De hecho, en nuestra experiencia, en aplicaciones reales casi siempre se usa un manejador de estado (ie: redux) en conjunción con React y se prefieren componentes _stateless_ antes que _stateful_, a menos de que necesitemos algunos de los features específicos de los componentes como _clases_ (_hooks_ de _life-cycle_, _refs_, o estado que por algún motivo queramos mantener como interno del componente).

Por otro lado, React y su comunidad favorecen el estilo (paradigma) funcional sobre el orientado a objetos a nivel de arquitectura y diseño. De hecho, la implementación OOP de componentes en React es un _azúcar sintáctico_ para facilitar la encapsulación de estado y lógica interna, pero no se usa como mecanismo de herencia y reuso de código, que es la motivación principal detrás del paradigma orientado a objetos. En el universo de React siempre se favorece la composición sobre la herencia, la inmutabilidad, las funciones puras, ... En ese contexto, se considera una buena práctica el solo implementar un componente como clase cuando es la única manera de hacerlo, y la mayoría de componentes se pueden/deben implementar como funciones puras (_stateless_), lo cual trae los beneficios añadidos de ser más fácil de razonar, aislar y testear.

Siguiendo la misma filosofía, se decidió arrancar con `React` y `ReactDOM` _calatos_ (sin JSX, ni Babel, ni Webpack, ...) en vez de usar `creare-react-app`, con la idea de que fueramos viendo paso a paso donde encaja cada pieza (su función y necesidad), y poco a poco ir aumentando la complejidad según aparecen las necesidades. Asumimos que las chicas van a ver `create-react-app` por su cuenta (un _googleo_ básico y la documentación oficial te van a llevar ahí), y quizás deberíamos incluir aunque sea un _side note_ sobre esta herramienta en el _syllabus_, pero justamente lo _lindo_ de `create-react-app` es que _oculta_ toda la complejidad del _set up_, que en este caso queremos aclarar. Es un tema básicamente de propuesta de ruta de aprendizaje. Qué opinan?

***

>  ¿Por qué desde la unidad 4 (componentes) ya no existen quizzes? (@shirley-suarez)

Originalmente este curso no tenía quizzes por diseño. A la hora de _reorganizar_ el curso para dictarse en el Bootcamp, el equipo de operaciones en Santiago propuso agregar algunos quizzes ya que ellas sienten que esto ayuda a las estudiantes a ellas mismas ir midiendo su aprendizaje. Así que @brecabal y @nerdale se animaron a contribuir con los quizzes que tenemos actualmente (https://github.com/Laboratoria/curricula-js/pull/520, https://github.com/Laboratoria/curricula-js/pull/522). Si consideran que sería útil agregar quizzes en otras unidades, se puede proponer y estamos abiertxs a que cualquiera se ofrezca como voluntarix 😉

***

> Hay alguna razón específica por la cual no hay ningún recurso en el curso acerca de yarn/npm? Se asumió que se cubrió en deep dive? Si es así, podríamos agregar algún recurso nosotros en algún lado? (@indie-rok)

Efectivamente en este curso se asume que a estas alturas ya te ha tocado trabajar con `yarn` y/o `npm`. Quizás podríamos agregar un nota y/o links a recursos externos, pero creo que queda fuera de _scope_ del _syllabus_ de este curso.

***

Thoughts?

**Comment by merunga** [comment]
Un comentario en relacion a lo q dice @shirley-suarez y @lupomontero 
Si analizamos el curso hasta la unidad 4, el contenido es puramente react presentacional, no existe nada en relacion a estados ni manejos de eventos. La unidad 5 y 6 muestran 2 maneras distintas (y potencialmente complementarias) de como hacer justamente eso.

En el caso especifico de por qué esta primero estado global q react oop, es como dice @lupomontero porque en su momento consideramos estructurar el contenido asi porque sigue el mismo paradigma de programacion: el funcional (solo funciones puras y objetos json inmutables). Pero en lineas generales yo diria que *ambas unidades son intercambiables*, ya q no existe una dependencia de una a otra y creo q el orden final en el q se exponen los contenidos del curso, es flexible en ese aspecto, (@lupomontero  me corrijes si lo q digo no es asi porfa) y depende del contexto en el q se dicte

**Comment by indie-rok** [comment]
> Es un tema básicamente de propuesta de ruta de aprendizaje. Qué opinan?
En esto estoy muy deacuerdo, @lupomontero, a mi me gusto mucho la forma de como en  este curso se enseñan las bases; sin dependencias y solo React :+1: 

> Si consideran que sería útil agregar quizzes en otras unidades, se puede proponer y estamos abiertxs a que cualquiera se ofrezca como voluntarix wink

Les mandamos PR en estos dias con quizzes de próximas unidades cc @shirley-suarez 

> Quizás podríamos agregar un nota y/o links a recursos externos, pero creo que queda fuera de scope del syllabus de este curso.

Si me gustaría agregar un link validado por algún profe (yo lo puedo hacer) para poder decir a las estudiantes: "A las que no sepan que estamos haciendo con yarn install react, por favor chequen su LMS en la unidad de React Sub sección node".

Si me das tu ok @lupomontero, te mando un PR en estos dias.


>  Pero en lineas generales yo diria que ambas unidades son intercambiables.

Igual, si @lupomontero nos da su ok, preferimos dictar primero OOP React como experimento (les damos feedback al terminar) para intentar enamorar a las estudiantes del poder de OOP y React antes de enojarnos con Redux ( :smiley: ) por su larga curva de aprendizaje.

**Comment by shirley-suarez** [comment]
> Igual, si @lupomontero nos da su ok, preferimos dictar primero OOP React como experimento (les damos feedback al terminar) para intentar enamorar a las estudiantes del poder de OOP y React antes de enojarnos con Redux ( 😃 ) por su larga curva de aprendizaje.

Igual si alguien de otra cede (@alejandrarv, @joalbertg, @michellesegv, @developerVilchez y @RuthMeryCardenas, @brecabal, @FabianBravoA, @nerdale, @MarciaMillanao y @bosqueinvierno )  tiene algún comentario o aportación por su experiencia que nos pueda ayudar, se los agradeceríamos.

**Comment by lupomontero** [comment]
> [...] yo diría que ambas unidades son intercambiables, ya q no existe una dependencia de una a otra y creo q el orden final en el q se exponen los contenidos del curso, es flexible en ese aspecto, (@lupomontero me corriges si lo q digo no es así porfa) y depende del contexto en el q se dicte @merunga

Efectivamente cada equipo de operaciones tiene la libertad y flexibilidad para adaptarse tanto a las alumnas como a lxs instructorxs. En este caso estoy de acuerdo con que las unidades 5 y 6 se pueden dictar en orden inverso si consideran que puede ser beneficioso.

> Les mandamos PR en estos días con quizzes de próximas unidades [...] (@indie-rok)

Genial 🎉🎈. Quedamos a la espera de propuestas de quizzes via PR.

> Si me gustaría agregar un link validado por algún profe (yo lo puedo hacer) para poder decir a las estudiantes: "A las que no sepan que estamos haciendo con yarn install react, por favor chequen su LMS en la unidad de React". (@indie-rok)

Esto, siendo un tema más genérico de JavaScript y no necesariamente parte del curso de React, quizás tenga más sentido como un blog post o incluso en el curso `99-general-concepts`, donde estamos acumulando temas generales para compilar como un curso de referencia... pero esto todavía está cocinándose... En el curso de React en particular, sólo añadiría una nota (un parrafito) con links a recursos externos (por ahora).

**Comment by developerVilchez** [comment]
Si! Si!! Tengo mucho que aportar!! Por favor, estoy estructurando las ideas para poder plasmarlo.

**Comment by PenelopeLghtn** [comment]
Dear Mr Montero,
Apologies interrupting the conversation. Am hoping you can help me, please? Are you still servicing the enoi.se business? I have a very urgent query I'm seeking assistance with on our account. Look forward to a rapid response.
Many thanks
Penelope

**Comment by lupomontero** [comment]
La semana pasada tuve la oportunidad de participar en salón de clase del Bootcamp en Lima junto con @merunga, y nos gustaría compartirles nuestras impresiones, comentarios, cosas que nos funcionaron, ... como feedback de nuestra experiencia de la semana pasada.

## Cosas buenas

* Antes de arrancar con la clase hicimos un **termómetro**. Básicamente les pedimos a las chicas que se paren y se organicen entre los dos extremos de la clase en base a cómo se sentían con respecto a _React_ primero y después _Redux_. Esto nos permitió ver dónde ellas sentían que necesitaban más ayuda y la distribución de confianza. En base a esto decidimos organizar y dividir la clase. También creo que ayudó mucho empezar la sesión teniendo que pararse y dejar la computadora, creando una separación clara entre lo que estaban haciendo hasta ese punto (hackeando en sus proyectos) y el comienzo de la sesión presencial. El resultado del termómetro determinó el contenido de la clase (orientado a Redux y ver sus problemas).
* **Código en vivo**: las demostraciones paso a paso y pensar en voz alta mientras uno _codea_ aportan un montón de valor. Conclusión: más código en vivo, menos slides.
* Clase guiada con **problemas de las alumnas** (en primera persona). En este caso se trataba del final de un sprint, así que tuvimos la libertad de separar el salón de clase y dedicar tiempo a resolver problemas "reales" que estaban teniendo en sus proyectos.

## Cosas no tan buenas

* **Scope de retos**. En esta ejecución del curso se usaron retos propuestos por empresas, lo cual es algo positivo, pero vimos problemas y contradicciones en algunos de los retos con respecto a los objetivos de aprendizaje del curso. Por ejemplo, teníamos retos donde el _cliente_ (la empresa) literalmente decía que no querían _React_ o que no eran _compatibles_ (??) con _React_... La conclusión es que no podemos depender totalmente de la definición de retos de 3eros, y nos toca o proponer nuestros retos y/o participar/coordinar más cuidadosamente la selección de retos de 3eros.
* **Requerimientos previos**. Una vez en el salón de clase nos dimos cuenta de que no se habían visto muchos temas que asumíamos habían visto, en base a la currícula. Esto tiene muchas explicaciones, y en este caso creo que evidencia una desconexión entre la currícula y la ejecución de los cursos que tenemos que mejorar. Necesitamos más feedback de ambos lados.
* Teniendo en cuenta el contexto, quizás **redux** tenga sentido plantearlo como un curso aparte, ya que causa mucha confusión cuando todavía no se tiene React claro. Así quedaríamos con dos cursos más concisos y digeribles. Para que esto se pueda dar, necesitaríamos llegar a un Bootcamp realmente _no lineal_ dónde cada chica pueda ir profundizando en cada tema a su ritmo (esto ya es otra conversación).
* **Tiempos**. Medimos muy mal los tiempos, nos faltó programar un poco mejor sesiones tan largas y quizás haber usado un timer para obligarnos a no divagar...
* Otro comentario que queríamos hacer es que el **salón de clase es muy grande**... y esto dificulta las dinámicas de grupo y el nivel de _personalización_. Pudimos partir el salón de clase en dos (con un biombo), pero sería muy chévere explorar formas de dividir el espacio para crear más _rincones_ y poder dividir la clase en más grupos de menos alumnas.

***

Food for thought... 💭 

cc/ @chamodev @merunga @ivandevp @developerVilchez, @alejandrarv, @joalbertg, @michellesegv, @RuthMeryCardenas, @valesmithb, @brecabal, @FabianBravoA, @nerdale, @MarciaMillanao @bosqueinvierno @LucileBaratier, @indie-rok y @shirley-suarez

**Comment by indie-rok** [comment]
Muy interesante aporte tu reflexión @lupomontero .

Algunas cosas de las que mencionas ya las empecé a notar. (AKA Redux xd)

Te pido que dejes este issue abierto un par de semanas mas y cuando termine el sprint @shirley-suarez y yo te damos un feedback concentrado.

**Comment by lupomontero** [comment]
Hola @indie-rok, qué tal? Cómo les ha ido? Tienen algo de feedback que quieran agregar a este issue?

cc/ @shirley-suarez @LucileBaratier

**Comment by lupomontero** [comment]
Cierro este issue en favor de #569, que todavía está pendiente...
