### ISSUE TITLE
Crear plantillas para cursos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#54]
Bootcamp (depende de #51):

- [ ] Mi primer website @ivandevp
- [ ] JS Fundamentals @ivandevp

Educación continua

- [x] The web stack @lupomontero
- [x] Node.js @lupomontero
- [x] NoSQL @lupomontero
- [x] Command Line Foo @lupomontero
- [x] Data visualisation @chamodev

**Comment by chamodev** [comment]
Ya he creado el branch y un draft del README.md para el curso de `Data Visualization`: 
https://github.com/Laboratoria/curricula-js/tree/18-data-visualization/18-data-visualization

**Comment by lupomontero** [comment]
He creado una primera versión (semilla) de los cuatro siguientes cursos a desarrollar para EC:

* https://github.com/Laboratoria/curricula-js/tree/54-plantillas-cursos-ec/13-web-stack
* https://github.com/Laboratoria/curricula-js/tree/54-plantillas-cursos-ec/14-nodejs
* https://github.com/Laboratoria/curricula-js/tree/54-plantillas-cursos-ec/15-nosql
* https://github.com/Laboratoria/curricula-js/tree/54-plantillas-cursos-ec/16-cli

**Comment by lupomontero** [comment]
@arcuellar88: gracias por el comentario y sorry por la demora en responder 😰 

Tenemos la intención de desarrollar un curso sobre bases de datos relacionales y otro sobre bases de datos no relacionales (bases de datos de documentos json en particular - ie: mongo o couch).

Por ahora sólo hemos creado la plantilla para ir empezando con el diseño de "no relacionales", que desde el punto de vista de la currícula "full stack js" es probablemente más "natural". Si te animas a hacer una propuesta para ese curso porfa añade un comentario en [este issue](https://github.com/Laboratoria/curricula-js/issues/72) con las ideas que tengas y ofreciéndote como voluntario 👻

Cierro este issue por ahora ya que las plantillas que estaban pendientes dependen de https://github.com/Laboratoria/curricula-js/issues/81

cc/ @ivandevp @chamodev
