### ISSUE TITLE
Revisión malla curricular

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#546]
Esta semana estamos teniendo la oportunidad de tener unas sesiones de trabajo para imaginar (y aterrizar ☁️✈️) nuestra propuesta para la próxima iteración de nuestro Bootcamp 💪 🎸 

Después de largas conversaciones, feedback, retros, reus, llamadas, chats, ...me tomo la libertad de poner por escrito lo que creo que son las principales decisiones que afectan directamente a este proyecto de la _malla curricular_ de JavaScript.

## Rúbrica y proceso de evaluación

Hemos decidido desarrollar una rúbrica conjunta de JS, UX y HSE. Esta rúbrica se aplicará a los **retos**, que siempre contienen elementos de las 3 ramas. Para el final de la semana (mañana?) esperamos tener un prototipo de rúbrica y proceso de evaluación que podamos compartir para ilustrar la idea. Como referencia hemos tomado las experiencias pasadas, feedback y [rúbricas de otras instituciones como Summit Learning](https://www.summitlearning.org/rubric).

## Diseñar pensando en 5 meses (no 6)

El Bootcamp tiene una duración de 6 meses de calendario, pero la malla curricular debe apuntar a cubrir 5 meses, teniendo en cuenta que hay parones por vacaciones, hackathones, eventos, ... Creemos que en el pasado hemos sufrido de ser muy ambiciosos con la _cantidad_ y los _detalles_, lo cual no permite el nivel de profundidad que nos gustaría en la bases (del _common core_ en particular).

## Menos contenido / más profundidad

Creemos que quizás no hay necesidad de incluir tanto contenido en el common core, y dar más imporancia a la profundidad, retries, ... Así que estamos viendo qué cosas podemos/debemos dejar fuera del common core.

## Menos _manual de referencia_, más narrativa y más links

Con lo que respecta a las lecturas, videos, ... creemos que tiene más sentido centrarnos en sólo crear contenidos que sean orientados al _code along_, _story telling_, para introducir conceptos o demostrar código, pero no para describir las características y todos los detalles de features del lenguage o APIs de librerías. También debemos hacer más esfuerzo en "curar", recolectar (y si fuera necesario traducir) contenido antes que lanzarse a escribir (más DRY 🙈).

## Más de énfasis en fundamentos de CS y JS

Una de la conclusiones principales de la última iteración del Bootcamp es que necesitamos hacer un poco **más de énfasis en fundamentos de CS y JS**. Para atacar este tema en particular la propuesta es mover muchos de los contenidos del curso de [deep dive](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive) (en particular las unidades de testing y foundations) al inicio del bootcamp, así como hacer énfasis en conceptos de pensamiento algorítmico, principios de computación, pseudo-código, ...

## Mover herramientas de productividad después del common core

Como consecuencia del punto anterior, hemos decidido dejar las herramientas de productividad (libs, frameworks, ...) para después del common core, donde no necesariamente todas verán las mismas herramientas.

## Dividir "cursos" en artefactos más chicos y manejables

Con el objetivo de facilitar el manejo (creación, revisión, consumo, ...) de los cursos hemos decidido _partirlos_ en pedacitos más chiquitos en base a temas. Esto hace que se puedan consumir de forma **no lineal**. La idea no es que todas las chicas pasen por todo el contenido, si no que todo el contenido esté disponible a las chicas y que ellas puedan ir consumiendo a demanda.

Ya hay una [propuesta de cómo _partir_ el curso 02-basic-programming](https://github.com/Laboratoria/curricula-js/issues/535#issuecomment-380834467), que es el curso con el que arranca el Bootcamp.

## Separar agenda, syllabus (contenido) y retos

Esta es una de las grandes tareas que venimos conversando hace ya un tiempo y tiene su propio [issue](https://github.com/Laboratoria/curricula-js/issues/534)

## Mover contenidos no específicos de la malla de JavaScript a un repositorio aparte

A día de hoy tenemos varios contenidos en este repo que no son específicos de JavaScript. Para poder mantener y reusar estos contenidos con mayor facilidad (en otros programas de formación) hemos decido moverlos a un repositorio separado (por crear). Como ejemplo de este tipo de contenido, la [primera unidad del curso `02-basic-programming`](https://github.com/Laboratoria/curricula-js/tree/02-basic-programming/02-basic-programming/00-welcome) contiene la bienvenida a Laboratoria junto con lecturas sobre el modelo de aprendizaje, growth mindset ...

Otros contenidos que se deberían de mover a otros repos:

* Curso [`18-data-visualization`](https://github.com/Laboratoria/curricula-js/tree/18-data-visualization/18-data-visualization)
* Curso [`25-solutions-architecture`](https://github.com/Laboratoria/curricula-js/tree/25-solutions-architecture/25-solutions-architecture)
* Curso [`xy-hse`](https://github.com/Laboratoria/curricula-js/tree/xy-hse/xy-hse)

***

Todo el feedback es bienvenido! Tratemos de mantener lo que podamos de la conversación por acá para mantener el contexto y ser inclusivos.

cc/ @alejandrarv @LucileBaratier @valesmithb @KarlaRejas @diegovelezg @lalogf @AmaliaRiveraC @AnaSalazar @merunga @Laboratoria/developers

**Comment by ivandevp** [comment]
Yo estoy de acuerdo en la mayoría de puntos, solo tengo los siguientes comentarios:

* De acuerdo con los fundamentos de CS y JS, pero _no creo_ que sea viable en el Common Core, teniendo en cuenta que están las de UX. Al menos no tanta profundidad, creo que les agregaría más ver temas de problem solving a través de flowcharts que ver testing y/o entender funciones y objetos a detalle.

* Respecto a la cantidad de contenido, yo creo que llevamos varias iteraciones con esto y funciona bien. Lo particular del último bootcamp fue que la mayoría se volvió _self-learning_ y en ese aspecto fue abrumador tanto para crear el contenido como para las estudiantes. Yo creo que esto debe ser una mejor organización y distribución de temas, eso disolvería la cantidad. Sobre todo si pensamos en separar contenido de agenda.

* Respecto a recolectar contenido existente, todos ansiamos eso, una de las cosas por la que nos hemos matado haciendo contenido ya sea en presentaciones, markdown o lo que sea. Es porque la información en español es muy poca y sobretodo no está estandarizada y muchas de ellas no se pueden extraer por si sola, sino que llevan muchos enlaces a un flujo particular. (Creéme que ya lo hemos intentado).

* Respecto a las herramientas de productividad (librerías y/o frameworks) para el common core, depende del approach y productos que queramos proponer. Pues, particularmente creo que si es un _common core_, donde están diversos perfiles podría dar una perspectiva de todo lo que pueden lograr rápidamente sin reinventar la rueda.

**Comment by FabianBravoA** [comment]
Super de acuerdo con el "menos contenido, más profundidad", sobre esto pienso, y ojalá lo podamos discutir acá también, que hay varios contenidos que deberíamos quitar o ver con mucha menos profundidad. 
Un componente que está entrando en desuso rápidamente (como alguna vez fue flash) es JQuery, gracias a React, Vue, Ember y Angular ya no es tan necesario como antes y muchas veces viene incluido más por familiaridad de algunos programadores más que por que sea necesario. Probablemente sea bueno mencionarlo solamente, pero no profundizar como en esta generación que ya está terminando, donde hasta hicieron una biblioteca de JQuery, siendo que quizá no era tan necesario.

**Comment by nerdale** [comment]
Me parece súper lo de las rúbricas, no solo por lo integral que son sino que también por lo estandar que pueden ser para todas las Sedes, así buscamos todos la misma calidad en nuestras alumnas :metal:

**Menos contenido, más profundidad** me parece excelenteeee! Hay contenidos como por ejemplo de CSS que se hacen largos y que luego al ver frameworks se ven algunas veces innecesarios, lo mismo sucede con jQuery como comenta @FabianBravoA, si bien son parte de la "cultura general del programador" no creo que sea tan necesario verlos toooodos y si profundizar en lo más necesario para el ámbito laboral actual.

**Mover herramientas de productividad después del common core**
Me hace mucho sentido en el tema de jQuery por ejemplo, pero quizás los frameworks de CSS si sean algo medianamente necesario para las posibles alumnas de UX, al menos manejarlo básicamente.

**Comment by indie-rok** [comment]
🎉  🎉 

MUY  de acuerdo en _Menos contenido / más profundidad._

Desde hace tiempo venimos jugando con esa idea.

Detecte con muchas estudiantes el hecho que tantos temas del LMS les parecia abrumador y optamos por la estrategia: "Leelo solo si tienes tiempo  y como extra"

jQuery,  "crear tu propia librería con JS",  firebase en sprints iniciales, "crea tu spa", etc

Aun que muy ambiciosos, son temas que simplemente una gran parte de las estudiantes no hacen por que están enfocadas en aprender las bases (como se debe).

Como menciona @ivandevp , probablemente una mejor distribución de estos temas pueda solucionarlo. Pero por ahora dejar los temas como "extra y solo si tienes tiempo" funciono bastante bien.

--

También dejo sobre la mesa el tema de los _videos_.

Muchas estudiantes consumen una cantidad grandisima de videos (de mis clases, de otros profes, o algún otro profe de You Tube)

Se que es un gran reto, pero estaría interesante explicar conceptos teoricos (no solo solucionarios de ejercicios) con videos.

**Comment by memecast** [comment]
Estoy de acuerdo con **Menos contenido/ Más profundidad** creo que es importante recordar que no sirve de nada saber el nombre de abc si no podemos aplicarlo en la realidad. Estaría increíble que dieramos especial enfásis en tecnologías como React, Angular y Firebase. Tecnologías que en este momento están teniendo un auge impresionante. Además me gustaría rescatar el tema que expuso @ivandevp. 
Creo que durante el common core, sería muy interesante profundizar en resolución de problemas a través de la lógica en programación, además de otros conceptos en ciencias de la computación, creo que eso nos ayudaría a evitar el temor a todo el track de "Full Stack Dev" y también creo que es muy importante que las alumnas entiendan desde el common core **Qué hace realmente un UXer**. Encontrar contenido o generarlo que les de un panorama más amplio para tomar una decisión sobre el track que desean llevar. 

En mi opinión, creo que podríamos conservar herramientas de productividad como los frameworks de css, pues creo que son de provecho tanto para uxers como para front-ends y coincido con @nerdale en reducir la cantidad de contenido que manejamos para css puro, pues sí, se vuelve repetitivo y en muchos casos innecesario conocer todas las sutilezas del lenguaje.

**Comment by AnaSalazar** [comment]
- En cuanto a la _rúbrica y proceso de evaluación_ se me hace super valioso que se haga un conjunto de JS, Ux y HSE. Esto nos orilla a tener muy claro los objetivos o alcances que esperamos ver de las estudiantes en los productos finales y por lo tanto deben ser productos bien definidos y planteados.

- En lo de menos contenido y más profundidad tal vez sería bueno mencionar que temas o en cuales de ellos profundizar y en que dirección. Si bien ya mencionaron que podemos eliminar jQuery y algunos temas de css, creo que podemos enfocarnos en como queremos esto.

- Recolectar contenido existente es una joda, contenido bueno y concreto es carente en español. Justo por eso nos dimos a la tarea de crearlo nosotros, creo que dejarles los links mientras ellas aun están _aprendiendo a aprender y buscar por su cuenta_ puede llevarlas a perderse catastróficamente.

- De los temas que podemos sacar del common core a mi me parece que podemos prescindir de framworks (de css y js) y librerías pero enfocando bien los productos que entonces les vamos a pedir desarrollar.

- Retomando el tema que @indie-rok puso "sobre la mesa" acerca de los vídeos, yo también opino que son importantes y pueden volverse una herramienta que nos ayude mucho para evitar tanto texto.

- Y por último pero no menos importante, estoy totalmente de acuerdo en separar la agenda del syllabus y mover los contenidos que no son de JS fuera de este repo.

**Comment by diegovelezg** [comment]
### 1.  Contenido y tipo de contenido

Si bien hay montones de opiniones/literatura/críticas/discrepancias/etc. sobre "estilos de aprendizaje", acá hay un poco de data recolectada de nuestras estudiantes del final del CC.

![image](https://user-images.githubusercontent.com/28717078/38836287-30c99d0e-4193-11e8-8802-7a11f01ae32c.png)
Leyendo - Con videos - Me da igual dónde, siempre que pueda intentar aplicar/practicar lo más pronto posible.

### 2.  Menos cantidad y más profundidad
 - Si vas a hacer algo, hazlo bien
 - Data de la misma encuesta: "En una escala de 1-10, cuántos vacíos de conocimiento tienes después del CC (10 = todos los vacíos posibles"
 -- 62% >=6
 -- 38% <=5

Quizás una buena parte se resuelve simplemente reorganizando contenido como dice @ivandevp

**Comment by merunga** [comment]
en relacion al punto (1), yo no se exactamente como es el escenario en Chile o Mexico, pero aca en Peru con los indices terribles de comprensión lectora, estos son datos super "esperables".
@diegovelezg esos datos son promediados de todas las sedes?

Quizas se prefieren los videos, simplemente porque el texto no es un recurso valido, al no ser posible sacarle valor?

Yo se que el problema de la comprension lectora es un problema q afecta transversalmente a todas las disciplinas, pero particularmente en nuestro caso, creo q quizas valdria la pena analizar un poquito mas este dato e intentar de entender mejor cuánto de este numero es "hacerlo mas ameno" y cuánto es "me cuesta mucho trabajo entender lo que leo".

Quizas estamos dando por sentado que lxs alumnxs entienden lo que leen, y quizas no sea tan asi? No tengo idea si es algo q se tiene en cuenta en proceso de selección. Pero creo q estamos todos de acuerdo con que lxs egresadxs deberia salir pudiendo seguir sin problemas consignas y especificaciones escritas, asi como comunicarse efectivamente de manera escrita en el ambito profesional, y encontrar soluciones de buscadores, github, blogs y stackoverflow, no?

Tb deberiamos tener en cuenta el factor "flojera", analogamente con lo que decia @lupomontero sobre nuestra actitud hacia el testing:

![image](https://user-images.githubusercontent.com/211721/38840278-7243872a-41a4-11e8-8d15-703a42a304fc.png)
*\* esta afirmación podría ser válida para casi cualquier aspecto de la vida*

Yo opino que obviamente el video es un recurso q ayuda enormemente, pero creo que el texto es el **único recurso** que nos permite realmente aprender a nuestro propio ritmo y antes de aprender viendo videos, creo q es basico primero poder aprender leyendo.

**Comment by chamodev** [comment]
¡Gracias @lupomontero por abrir la discusión y a los demás por la participación!

Aprovecho esta conversación abierta para compartir un par de acuerdos adicionales y algunos documentos (todos _work-in-progress_) relacionados a la visión del Bootcamp 2018-1:

## 1) Backbone Curricular
@lupomontero hizo el súper trabajo de crear un representación gráfica del [Backbone Malla Bootcamp 2018](https://docs.google.com/drawings/d/1NmDVTea4oHGAhbJ8_ygzFYII7NuumuiZxCunj-lNO20/edit). ¡Gracias @lupomontero! 👍 Esta representación hace énfasis en los proyectos finales de cada Sprint y asocia los conceptos/temas a cada uno. Es un _work-in-progress_ así que su input es valioso. Aquí podemos canalizar (y llegar a un acuerdo) sobre la `profundidad` de los temas y sobre el `flujo/orden`.

Un aspecto interesante de esta visualización es que la idea es que tenga el backbone de JS, UX y Soft-Skills integrado en un mismo doc 💪. @lalogf estará integrando la visión de [malla de UX](https://docs.google.com/spreadsheets/d/1ZFQcNWKYqCbR5OeyiYZ-G2LGnlpSjeQTuPkAOE3O4jI/edit#gid=531649374) a este documento. ¡Gracias @lalogf !

De las conversaciones iniciales, hay fuerte inclinación por:
* Incluir una noción básica de `bases de datos` en el common core, dado que muchos squads en los Talent Fests sufren por no tener los mínimos conocimientos para estructurar la data de las empresas
* Reducir `jquery` al mínimo y eliminarlo del common core (en línea con el comentario de @FabianBravoA). Hacer algo similar con frameworks de css
* Incluir `git` desde el inicio  
* Incluir `testing` desde el inicio 
* Incluir las bases de `diseño visual` en el common core y mucho más de `Intro a UX` 

## 2) Cronograma 2018-1 
En cuanto a los tiempos, como mencionó @lupomontero, hemos acordado diseñar el Bootcamp para 5 meses efectivos. El plan es ejecutar el Backbone curricular (punto anterior) de la siguiente manera:
* 2 meses de Common Core (dividido en 3 sprints)
* 2 meses de "core" para cada especialización (JS y UX)
* 1 mes libre para que la alumna se especialice en lo que más le guste. El plan es tener un repertorio grande de proyectos y cada alumna decide cuáles completar. ¡Puede completar tantos como quiera! 🚀. La visión es que cada alumna construya un skill-set diferente y así se diferencian los perfiles.
 
## 3) Rúbricas y expectativas
Rocío hizo un súper trabajo en crear un primer draft de lo que será [nuestra rúbrica de evaluación 2018-1](https://docs.google.com/spreadsheets/d/1jrVLq8YfYIlXkUQMNiDWgyWJmM5_t4fVoxiNo9H88EA/edit#gid=76928813). ¡Gracias Rose! 💪. Aquí el plan es que tengamos los skills a desarrollarse en las 3 áreas (Soft, JS y UX), detallando diferentes niveles de competencia (0-5) y las expectativas tenemos para el final del CC y el final del bootcamp.  

## 4) Flujo del Sprint y Dinámica de Clases (Storyboard)
Hemos creado un storyboard que explica el [flujo del sprint y dinámica de clases 2018-1](https://docs.google.com/spreadsheets/d/1jVxI-kdFS5bXLGU9zBnIydC7SuJoQjZnewoiCNruJ8I/edit#gid=1710169812). 

## 5) Semana 1: Bienvenida
@diegovelezg y @alejandrarv están trabajando en diseñar una experiencia única para la primera semana que sirva de inducción para las nuevas alumnas y que deje bien claro las reglas del juego. Pueden dejar sus comentarios y seguir el desarrollo [aquí].(https://docs.google.com/document/d/1xt3BgFk4EPZx78_3nvtnlVdmcq-wbMIzi4Bi0b7ah3I/edit)

## 6) Filosofía sobre el aprendizaje
Otra cosa que necesitamos es un documento que explique [nuestra filosofía](https://docs.google.com/document/d/1ESFOaUXs5LhFcr6LjaWYT_Th3PcfNtwWPBO-PPCTE7o/edit). Eventualmente tendrá narrativa y lo convertiremos en una especie de manifesto. Por ahora, lo que estamos construyendo es una lista de principios clave. Invito a todxs a dar feedback (en calidad de comentarios para que sea ordenado). ¡Gracias!

¡Gracias a todxs por el esfuerzo! Se viene un gran bootcamp 🏅. Sigamos la conversación en cada espacio correspondiente. 

¡Abrazo fuerte!

**Comment by levhita** [comment]
## 1 Fomentar comprensión lectora > Vídeos.
Los contenidos técnicos pueden dividir en 2:

### 1.1 Abstractos/Conceptuales/Filosofiá
Son fácilmente digeribles con vídeos y gráficos, explicaciones más complejas se vuelven manejables a través del dialogo ameno.

### 1.2 APIs/Referencias/Código
Necesitan de hacer copy/paste y hacer pausas para ejecutar pruebas, (sistemas de aprendizaje dínamico con consolas interactivas son muy valiosas en estos casos), el riesgo de hacerlo en vídeo es que la estudiante dé por hecho que el comando ejecuta correctamente porque lo vió en en el vídeo.


## 2 Énfasis en CS
El énfasis en CS en el common core puede funcionar como una forma de quitar miedo a lo técnico en las estudiantes.

Si bien tenemos varias vertienes y una de ellas en teoría no requiere tanta profundidad en CS, parte de la misión de Laboratoria es expander las opciones disponibles a las estudiantes y eso no se va a conseguir cediendo a sus miedos (existe una linea delgada entre querer UX y tener miedo a CS).

Mi propuesta aquí es eleguir un punto medio, y monitorearlo en el próximo bootcamp, ajustandolo hasta conseguir el sweet spot.

Como maestrxs en el día a día aplicar estrategias para remover esos miedos.

Énfasis en CS en el common core como forma de quitar miedo a los técnico en las estudiantes(¿why? UX no tienes tanta vertienes como CS).

**Comment by levhita** [comment]
PD: Mi voto a encontrar los usos más comunes de JS y reemplazar lo que enseñaríamos de jQuery, con JS Vanilla, y dejar un módulo opcional de jQuery en el syllabus a forma de comparativa(lo mismo podría aplicar con Vuejs/Angular/React), como forma de desmitificar los frameworks.

Esto porque on-the-wild encontrarán estas librerias y frameworks instalados en los proyectos que reciban y les resultará útil y empoderante saber que debajo de todo, todos son lo mismo (Aunque @lupomontero ame React).

**Comment by diegovelezg** [comment]
@merunga Acá los datos por ciudad. De hecho, es en SCL donde el 0% dice que prefiere leyendo.
![image](https://user-images.githubusercontent.com/28717078/38896100-695688a2-4257-11e8-9370-3d2258555a40.png)

**Dos consideraciones:**
- Hasta donde sé, el nivel paupérrimo de comprensión de lectura es bien parecido en PE, CL y MX
- La generación que comienza el 14 de mayo, pasa por un proceso de selección que sí considera comprensión de lectura (contenido parecido al prework) y de hecho, tiene un peso preponderante porque sabemos que predice +/- bien un buen desempeño.

**Algunas ideas:**
- Es fundamental entender cuánto es por "lo ameno" y cuánto por la "incomprensión", de acuerdo.
- De acuerdo con incentivar la lectura, pero reconociendo el nivel con el que llegan. Quizás deba ser algo más progresivo.
- También es cierto lo que dice @levhita sobre considerar la naturaleza del contenido.
- Independientemente de todo lo anterior, quizás también haya que considerar la cantidad de conceptos en un texto (independientemente de su extensión, mi hipótesis es que mientras menos, más probabiliad de enmendar la incomprensión en clases.

No es la idea entrar en una discusión bizantina pero creo que vale la pena reconocer que son temas que a todos nos preocupan.
