### ISSUE TITLE
Publicación de contenido en el LMS

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/curricula-js#549]
Hola,
Abro esta discusión sobre un tema de crucial importancia y que impacta en muchas cosas.

@lalogf @lupomontero @CaroLaboratoria @claudiaalf @chamodev @coloradomarin @alejandrarv @valesmithb @LucileBaratier @ivandevp @FabianBravoA @MaiaRojas @RuthMeryCardenas @danielasarzosa 

### Contexto principal:
El LMS es un vehículo para otros productos (Bootcamp, L4B, etc.) que "sirven" contenido mediante él.

### Github como herramienta de trabajo colaborativo para crear contenido:
- Creo que a estas alturas, está fuera de discusión su tremenda utilidad como repositorio y herramienta de tracking y colaboración.
- Si bien hay una curva  de aprendizaje un poco "atemorizante" para quien lo hace por primera vez y no está familiarizadx, no es muy difícil de superar.

### Problemas:
Hasta acá todo muy bonito. El problema lo tenemos al pasar al LMS.
- Que dependa de un proceso manual de unas pocas personas lo convierte en un cuello de botella. 
- Atenta directamente contra la autonomía de los equipos.
- Si no está a tiempo, básicamente convierte al LMS en una herramienta inútil.

### Recordando:
- Entiendo que en la visión real, el paso debería ser "automágico" ¿Es así @lupomontero ?
- En mi opinión, debería ser tal cual GitBook, es decir, una vez que se pasa un contenido a Master, se publica automáticamente. Esto es algo que se necesita ASAP y el ownership de ese paso debe estar distribuído de manera que permita autonomía.

### Discusión:
- Propongo que automatizar el proceso sea nuestra prioridad antes de meterle un feature más al LMS y/o API.
- Mientras tanto:
  * Que tengamos un ciclo predecible de pases a producción del contenido. Por ejemplo, los lunes a las 11am GMT-5. Todos los creadores de contenido saben a qué hora parte el tren, si no llegas, fue.
  * Que hayan al menos 2 responsables del paso a prod que tengan la disponibilidad suficiente.
  * ¿Sugerencias/Ideas?

**Comment by claudiaalf** [comment]
Gracias @diegovelezg 

1. Estoy de acuerdo de empezar a darle más autonomía a los equipos. Hay que juntarnos para esa definición, dado que no debería funcionar tanto así como Gitbook, porque nosotros trabajamos con branches por empresa, no necesariamente con el master.
2. En el caso de L4B lo queremos usar para las empresas, y estos contenidos van ir variando por clase, por lo que vamos a ir subiendo contenido por cada clase que tengamos siempre. El material no se puede reusar, dado que cambian ejemplos. Esto hace que tengamos dependencia del pase a producción.
3. Por el momento estoy de acuerdo que tener un proceso para subir el contenido a producción, si es que acordamos que sean los lunes AM todo bien, pero URGENTE! tener este acuerdo, quiénes serían los responsables y qué es lo que deberíamos enviar exactamente.

**Comment by diegovelezg** [comment]
@claudiaalf respecto a gitbook, solamente me refería a lo automático de la publicación, nada más.

**Comment by lupomontero** [comment]
La conversación continúa en https://github.com/Laboratoria/lms.laboratoria.la/issues/186
