### ISSUE TITLE
02-basic-programming: Data structures

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#551]
@merunga: con respecto al _contenido_ (lecturas, recursos, ...) sobre estructuras de datos (arrays y objetos en particular) que [conversamos](https://github.com/Laboratoria/curricula-js/issues/535#issuecomment-380834467) para el primer _curso_ del Bootcamp, creo que sería bueno que nos comunicáramos por acá.

Cómo vas con esto? Podrías compartir tus _referencias_, ideas o work in progress por acá?

Ahí te dejo links a algunos contenidos que ya tenemos (extractos de las versiones actuales de los cursos `02-basic-programming` y `05-deep-dive`). La idea no es reciclar _as is_, pero pueden servir como referencia (o includo reciclar y remezclar a discreción):

* [02-basic-programming/02-arrays](https://github.com/Laboratoria/curricula-js/tree/02-basic-programming/02-basic-programming/02-arrays)
* [02-basic-programming/03-objects](https://github.com/Laboratoria/curricula-js/tree/02-basic-programming/02-basic-programming/03-objects)
* [05-deep-dive/03-foundations/06-arrays](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/03-foundations/06-arrays)
* [05-deep-dive/03-foundations/07-objects](https://github.com/Laboratoria/curricula-js/tree/05-deep-dive/05-deep-dive/03-foundations/07-objects)
* [Antigua currícula de EC](https://github.com/Laboratoria/curricula_javascript_ec/tree/new-file-structure/src/estructuras-de-datos)
* https://medium.com/laboratoria-how-to/pilas-stacks-76f3b8a31f61
* https://medium.com/laboratoria-how-to/sets-en-javascript-3388920f7cea

Aprovecho a pegar acá los links que me compartiste por slack:

* http://wcipeg.com/wiki/Array
* https://www.quora.com/Which-is-the-best-online-course-to-learn-data-structures
* https://visualgo.net/en
* https://www.topcoder.com/community/data-science/data-science-tutorials/data-structures/
* https://www.youtube.com/watch?v=DuDz6B4cqVc

Otras referencias:

* https://study.cs50.net/
* https://www.youtube.com/watch?v=eZQBx8YJ6Zs

Te aviso que estamos en proceso de reorganizar la estructura de archivos en este repo, así que estemos preparados para adaptarnos a los cambios... 🤞⛑

**Comment by merunga** [comment]
@lupomontero aca las referencias a ver que opinan:

### Tipos de datos estructurados

Estas referencias son por si antes de hablar puntualmente de `arrays` y `objects` queremos dar un paseo por los tipos de datos mas populares:

- https://medium.com/swlh/introduction-to-data-structures-9134b7d064a6
- https://medium.com/omarelgabrys-blog/diving-into-data-structures-6bc71b2e8f92

### Arrays
 
Y estos ya estan exclusivamente orientados a arrays.

- Este que ya esta en castellano, me parece q abarca todo lo necesario: https://devcode.la/tutoriales/manejo-de-arrays-en-javascript/
- Este es recontra minimal pero me encanta el codigo vivo mezclado con la lectura, me parece muy util: https://www.javascript.com/learn/javascript/arrays
- Para complementar el primero con algunos otros casos de uso: https://tech.io/playgrounds/6181/javascript-arrays---tips-tricks-and-examples
- Y por último, un recurso ya conocido que me encanta, pero q no estoy priorizando porq me he enfocado en encontrar referencias bien concretas, pero q si lo decidimos podemos usarlo de base: Elocuent Javascript Data types: https://eloquentjavascript.net/04_data.html

Y casi todos estos tienen referencias analogas para objects y strings.

**Comment by merunga** [comment]
@lupomontero a ver q te parece:
https://gist.github.com/merunga/0f4164f46f45fb54ec2302d25107f44a

![image](https://user-images.githubusercontent.com/211721/39106430-48df6f84-4681-11e8-9397-dd7396fb8ede.png)

Este es un ejemplo de como estarian orientadas las lecturas


Hay q ver como pasar eso a markdown para meter un poco de narrativa y explicar lo q esta sucediendo, pero la idea seria esa, que se vaya explicando la funcionalidad usando asserts.

Es probable que sea necesario bajarle el tamaño a los datasets para que sean mas facil de seguir y predecir, pero creo q la idea general se entiende.

Esto en relación a **como orientar la lectura**.

En relación a **contenido**, aca una propuesta de contenido:

- construir arrays
- indices y length del array
- iteración (de varias formas)
- metodos fundamentales de arrays: map, filter, sort, reduce
- otros metodos: some, every, find, findIndex, splice
- arrays como colas: push, pop
- copias vs referencias

que opinan?

**Comment by ivandevp** [comment]
Hola @merunga! 

Acabo de ver los links que has propuesto (aun no revisado, pero algunos conozco 😅), mi feedback es el siguiente:

- Creo que es conveniente categorizarlo, hay algunos que hablan desde el punto de vista de ciencias de la computación. Por ejemplo: cómo se guarda en memoria, que deben de ser de un solo tipo, tienen una longitud definida, el análisis de complejidad de tiempo, etc. Por otro lado, tenemos los links que son muy cercanos a JavaScript, algunos teóricos (**Eloquent JavaScript**) y otros más prácticos como **JavaScript30.com**.
- Una vez categorizado, creo que sería bueno ordenarlo, me refiero a que tal vez los de CS no son los que deberían de ir primero si lo pensamos en una curva progresiva.

En cuanto a la relación del contenido, me parece genial, agregaría como parte práctica el dejar claro en la parte de iteración que los arrays en JS pueden almacenar diferentes tipos y algo que se complican en mi experiencia como instructor, es cuando mezclan arrays vs objects 😱 🔫. 

Conforme vaya revisando más los enlaces te seguiré dando feedback 😃

**Comment by merunga** [comment]
Siguiendo con la iteracion, de **[este código](https://gist.github.com/merunga/0f4164f46f45fb54ec2302d25107f44a#file-arrays-js)** podemos extraer el *markdown* de mas abajo, usando [jdi](https://github.com/alexanderGugel/jdi):

Funciona este formato self-paced basado en assertions y un codigo que realmente se pueda correr y testear?

Si podemos definir si este formato funciona y el contenido detallado en el [comentario anterior](https://github.com/Laboratoria/curricula-js/issues/551#issuecomment-383448748) tb, podemos avanzar con las lecturas.

@lupomontero @ivandevp 

---

Usaremos el `assert` de node
```js
const assert = require('assert');

```
## Unos datos que usaremos para nuestros ejemplos
### Inventores
```js
const inventors = [
  {
    first: 'Albert',
    last: 'Einstein',
    year: 1879,
    passed: 1955,
  },
  {
    first: 'Isaac',
    last: 'Newton',
    year: 1643,
    passed: 1727,
  },
  {
    first: 'Galileo',
    last: 'Galilei',
    year: 1564,
    passed: 1642,
  },
  {
    first: 'Marie',
    last: 'Curie',
    year: 1867,
    passed: 1934,
  },
  {
    first: 'Johannes',
    last: 'Kepler',
    year: 1571,
    passed: 1630,
  },
  {
    first: 'Nicolaus',
    last: 'Copernicus',
    year: 1473,
    passed: 1543,
  },
  {
    first: 'Max',
    last: 'Planck',
    year: 1858,
    passed: 1947,
  },
  {
    first: 'Katherine',
    last: 'Blodgett',
    year: 1898,
    passed: 1979,
  },
  {
    first: 'Ada',
    last: 'Lovelace',
    year: 1815,
    passed: 1852,
  },
  {
    first: 'Sarah E.',
    last: 'Goode',
    year: 1855,
    passed: 1905,
  },
  {
    first: 'Lise',
    last: 'Meitner',
    year: 1878,
    passed: 1968,
  },
  {
    first: 'Hanna',
    last: 'Hammarström',
    year: 1829,
    passed: 1909,
  },
];

```
## Personas
```js
const people = [
  'Beck, Glenn', 'Becker, Carl', 'Beckett, Samuel',
  'Beddoes, Mick', 'Beecher, Henry', 'Beethoven, Ludwig',
  'Begin, Menachem', 'Belloc, Hilaire', 'Bellow, Saul',
  'Benchley, Robert', 'Benenson, Peter', 'Ben-Gurion, David',
  'Benjamin, Walter', 'Benn, Tony', 'Bennington, Chester',
  'Benson, Leana', 'Bent, Silas', 'Bentsen, Lloyd',
  'Berger, Ric', 'Bergman, Ingmar', 'Berio, Luciano',
  'Berle, Milton', 'Berlin, Irving', 'Berne, Eric',
  'Bernhard, Sandra', 'Berra, Yogi', 'Berry, Halle',
  'Berry, Wendell', 'Bethea, Erin', 'Bevan, Aneurin',
  'Bevel, Ken', 'Biden, Joseph', 'Bierce, Ambrose',
  'Biko, Steve', 'Billings, Josh', 'Biondo, Frank',
  'Birrell, Augustine', 'Black Elk', 'Blair, Robert',
  'Blair, Tony', 'Blake, William',
];

```
# Array.prototype.filter()
```js
describe('Array.prototype.filter()', () => {
```
## 1. Buscar los inventares nacidos en el siglo XVI
```js
  it('1. Buscar los inventares nacidos en el siglo XVI', () => {
    const fifteen = inventors.filter(inventor => (inventor.year >= 1500 && inventor.year < 1600));
    return assert.deepStrictEqual(
      fifteen,
      [
        {
          first: 'Galileo',
          last: 'Galilei',
          year: 1564,
          passed: 1642,
        },
        {
          first: 'Johannes',
          last: 'Kepler',
          year: 1571,
          passed: 1630,
        },
      ],
    );
  });
});

```
# Array.prototype.map()
```js
describe('Array.prototype.map()', () => {
```
## 2. Construir un array de Strings que contenga nombre y apellido de los inventores
```js
  it('2. Construir un array de Strings que contenga nombre y apellido de los inventores', () => {
    const fullNames = inventors.map(inventor => `${inventor.first} ${inventor.last}`);
    return assert.deepStrictEqual(
      fullNames,
      [
        'Albert Einstein',
        'Isaac Newton',
        'Galileo Galilei',
        'Marie Curie',
        'Johannes Kepler',
        'Nicolaus Copernicus',
        'Max Planck',
        'Katherine Blodgett',
        'Ada Lovelace',
        'Sarah E. Goode',
        'Lise Meitner',
        'Hanna Hammarström',
      ],
    );
  });
});

```
# Array.prototype.sort()
```js
describe('Array.prototype.sort()', () => {
```
## 3. Ordenar a los inventores del mas viejo al mas joven
Este es el resultado esperado
```js
  const oldestToYoungest = [
    {
      first: 'Nicolaus',
      last: 'Copernicus',
      passed: 1543,
      year: 1473,
    },
    {
      first: 'Galileo',
      last: 'Galilei',
      passed: 1642,
      year: 1564,
    },
    {
      first: 'Johannes',
      last: 'Kepler',
      passed: 1630,
      year: 1571,
    },
    {
      first: 'Isaac',
      last: 'Newton',
      passed: 1727,
      year: 1643,
    },
    {
      first: 'Ada',
      last: 'Lovelace',
      passed: 1852,
      year: 1815,
    },
    {
      first: 'Hanna',
      last: 'Hammarström',
      passed: 1909,
      year: 1829,
    },
    {
      first: 'Sarah E.',
      last: 'Goode',
      passed: 1905,
      year: 1855,
    },
    {
      first: 'Max',
      last: 'Planck',
      passed: 1947,
      year: 1858,
    },
    {
      first: 'Marie',
      last: 'Curie',
      passed: 1934,
      year: 1867,
    },
    {
      first: 'Lise',
      last: 'Meitner',
      passed: 1968,
      year: 1878,
    },
    {
      first: 'Albert',
      last: 'Einstein',
      passed: 1955,
      year: 1879,
    },
    {
      first: 'Katherine',
      last: 'Blodgett',
      passed: 1979,
      year: 1898,
    },
  ];

  it('3. Ordenar a los inventores del mas viejo al mas joven', () => {
    const ordered = inventors.sort((a, b) => {
      if (a.year > b.year) {
        return 1;
      }
      return -1;
    });
    return assert.deepStrictEqual(
      ordered,
      oldestToYoungest,
    );
  });

```
### Ahora usando el *operador ternario*
```js
  it('3.a Ordenar a los inventores del mas viejo al mas joven, usando el operador ternario', () => {
    const ordered = inventors.sort((a, b) => (a.year > b.year ? 1 : -1));
    return assert.deepStrictEqual(
      ordered,
      oldestToYoungest,
    );
  });

```
## 4. Ordenar a los inventores, según la cantidad de años vividos
```js
  it('4. Ordenar a los inventores, según la cantidad de años vividos', () => {
    const oldest = inventors.sort((a, b) => {
      const lastInventor = a.passed - a.year;
      const nextInventor = b.passed - b.year;
      return lastInventor > nextInventor ? -1 : 1;
    });
    return assert.deepStrictEqual(
      oldest,
      [
        {
          first: 'Lise',
          last: 'Meitner',
          passed: 1968,
          year: 1878,
        },
        {
          first: 'Max',
          last: 'Planck',
          passed: 1947,
          year: 1858,
        },
        {
          first: 'Isaac',
          last: 'Newton',
          passed: 1727,
          year: 1643,
        },
        {
          first: 'Katherine',
          last: 'Blodgett',
          passed: 1979,
          year: 1898,
        },
        {
          first: 'Hanna',
          last: 'Hammarström',
          passed: 1909,
          year: 1829,
        },
        {
          first: 'Galileo',
          last: 'Galilei',
          passed: 1642,
          year: 1564,
        },
        {
          first: 'Albert',
          last: 'Einstein',
          passed: 1955,
          year: 1879,
        },
        {
          first: 'Nicolaus',
          last: 'Copernicus',
          passed: 1543,
          year: 1473,
        },
        {
          first: 'Marie',
          last: 'Curie',
          passed: 1934,
          year: 1867,
        },
        {
          first: 'Johannes',
          last: 'Kepler',
          passed: 1630,
          year: 1571,
        },
        {
          first: 'Sarah E.',
          last: 'Goode',
          passed: 1905,
          year: 1855,
        },
        {
          first: 'Ada',
          last: 'Lovelace',
          passed: 1852,
          year: 1815,
        },
      ],
    );
  });

```
## 5. Ordenar a los inventores, según la fechade nacimiento de mas viejo a mas joven
```js
  it('5. Ordenar a los inventores, según la fechade nacimiento de mas viejo a mas joven', () => {
    const alpha = people.sort((lastOne, nextOne) => {
      /* eslint-disable no-unused-vars */
      const [aLast, aFirst] = lastOne.split(', ');
      const [bLast, bFirst] = nextOne.split(', ');
      /* eslint-enable no-unused-wars */
      return aLast > bLast ? 1 : -1;
    });
    assert.deepStrictEqual(
      alpha,
      [
        'Beck, Glenn',
        'Becker, Carl',
        'Beckett, Samuel',
        'Beddoes, Mick',
        'Beecher, Henry',
        'Beethoven, Ludwig',
        'Begin, Menachem',
        'Belloc, Hilaire',
        'Bellow, Saul',
        'Ben-Gurion, David',
        'Benchley, Robert',
        'Benenson, Peter',
        'Benjamin, Walter',
        'Benn, Tony',
        'Bennington, Chester',
        'Benson, Leana',
        'Bent, Silas',
        'Bentsen, Lloyd',
        'Berger, Ric',
        'Bergman, Ingmar',
        'Berio, Luciano',
        'Berle, Milton',
        'Berlin, Irving',
        'Berne, Eric',
        'Bernhard, Sandra',
        'Berra, Yogi',
        'Berry, Halle',
        'Berry, Wendell',
        'Bethea, Erin',
        'Bevan, Aneurin',
        'Bevel, Ken',
        'Biden, Joseph',
        'Bierce, Ambrose',
        'Biko, Steve',
        'Billings, Josh',
        'Biondo, Frank',
        'Birrell, Augustine',
        'Black Elk',
        'Blair, Robert',
        'Blair, Tony',
        'Blake, William',
      ],
    );
  });
});

```
# Array.prototype.reduce()
```js
describe('Array.prototype.reduce()', () => {
```
## 7. Calcular la cantidad de años vividos, de todos los inventores sumados
```js
  it('7. Calcular la cantidad de años vividos, de todos los inventores sumados', () => {
    const totalYears = inventors
      .reduce((total, inventor) => total + (inventor.passed - inventor.year), 0);
    return assert.equal(totalYears, 861);
  });

```
## 8. Sumar la cantidad de apariciones de cada medio de transporte
```js
  it('8. Sumar la cantidad de apariciones de cada medio de transporte', () => {
    const data = [
      'car', 'car', 'truck', 'truck', 'bike', 'walk',
      'car', 'van', 'bike', 'walk', 'car', 'van',
      'car', 'truck',
    ];
    const transportation = data.reduce((obj, item) => {
      const result = {
        ...obj,
      };
      if (!obj[item]) {
        result[item] = 0;
      }
      result[item] += 1;
      return result;
    }, {});
    assert.deepStrictEqual(
      transportation,
      {
        car: 5, truck: 3, bike: 2, walk: 2, van: 2,
      },
    );
  });

```
## 8.a ahora agregando un nuevo medio de transporte (pogostick)
```js
  it('8.a ahora agregando un nuevo medio de transporte (pogostick)', () => {
    const data = [
      'car', 'car', 'truck', 'truck', 'bike', 'walk',
      'car', 'van', 'bike', 'walk', 'car', 'van',
      'car', 'truck', 'pogostick',
    ];
    const transportation = data.reduce((obj, item) => {
      const result = {
        ...obj,
      };
      if (!obj[item]) {
        result[item] = 0;
      }
      result[item] += 1;
      return result;
    }, {});
    assert.deepStrictEqual(
      transportation,
      {
        car: 5, truck: 3, bike: 2, walk: 2, van: 2, pogostick: 1,
      },
    );
  });
});

```

**Comment by lupomontero** [comment]
Cerrado en https://github.com/Laboratoria/curricula-js/pull/574 y https://github.com/Laboratoria/curricula-js/pull/602
