### ISSUE TITLE
Narrativa: Reto Cifrado César

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#559]
- Cumpleaños de tu flacx

Está próxima la fecha del cumpleaños de tu _flacx (novix)_ y estás organizando una fiesta sorpresa. Un gran problema es que pones tu alarma según para levantarte temprano, sin embargo (como supondrás) eso nunca sucede y _tu flacx_ es quien termina apagando la alarma y "de casualidad" revisando tus mensajes. Debido a que es algo sorpresa, decides crear una aplicación que te permita enviar un mensaje encriptado y que las demás personas (partícipes de la fiesta) puedan tener una interfaz para desencriptarlo. Así que ahora te toca aplicar tus superpoderes 😎

**Comment by lupomontero** [comment]
Gracias @ivandevp  💪

La intro ya está integrada en la descripción del [reto](https://github.com/Laboratoria/cipher) 😉
