### ISSUE TITLE
Detallar método de evaluación en curso React

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#56]
La propuesta de "60% producto/equipo + 40% desempeño personal" me parece bien. Pero todavía no me queda tan claro cómo vamos a evaluar cosas como la participación en sesiones presenciales o actividad en slack, ...

Me imagino que irá detallándose según evolucione el syllabus y especialmente cuando haya que desarrollar la primeras lección (#55).

**Comment by merunga** [comment]
@lupomontero @chamodev @CaroLaboratoria podemos coordinar call o reu para hablar de esto?

**Comment by lupomontero** [comment]
@merunga, después de la conversación de ayer, quedamos en que tienes libertad de experimentar con la propuesta de evaluación (sin exámenes, ...) pero siempre teniendo en cuenta que debemos recolectar la data necesaria para poder medir progreso y aprendizaje, tanto a nivel grupal como individual. Por ahora la propuesta está aceptada! ;-)
