### ISSUE TITLE
Introducción: Reto cifrado César

### ISSUE THREAD

**Issue by AnaSalazar** [Laboratoria/curricula-js#560]
El cifrado César es uno de los primeros métodos de cifrado conocidos históricamente, es un tipo de cifrado por sustitución en el que una letra en el texto original es reemplazada por otra letra que se encuentra un número fijo de posiciones más adelante en el alfabeto.

El emperador Julio César lo usaba para enviar órdenes a sus generales en los campos de batalla, es una de las técnicas más simples y más usadas para cifrar un mensaje. 

Por ejemplo si usáramos un desplazamiento de 3:
Alfabeto en claro:  A B C D E F G H I J K L M N Ñ O P Q R S T U V W X Y Z
Alfabeto cifrado:    D E F G H I J K L M N Ñ O P Q R S T U V W X Y Z A B C

Actualmente todos los cifrados de sustitución alfabética simple, se descifran con facilidad y en la práctica no ofrece mucha seguridad en la comunicación, pero el cifrado César muchas veces puede formar parte de sistemas más complejos de codificación, como el cifrado Vigenère, e incluso tiene aplicación en el sistema ROT13.

**Comment by lupomontero** [comment]
Gracias @AnaSalazar 💪

La intro ya está integrada en la descripción del [reto](https://github.com/Laboratoria/cipher) 😉
