### ISSUE TITLE
Hacer del contenido del LMS descargable.

### ISSUE THREAD

**Issue by memecast** [Laboratoria/curricula-js#565]

**Comment by lupomontero** [comment]
Hola @memecast, gracias por abrir el _issue_ 🥇 

En este caso, creo que este _issue_ pertenece al [repo del LMS](https://github.com/Laboratoria/lms.laboratoria.la/), ya que es un _feature_ que toca implementar ahí, ... y es un feature importante 😰 

Puedes abrir en nuevo [issue en el repo del LMS](https://github.com/Laboratoria/lms.laboratoria.la/issues), porfa?

Gracias!
