### ISSUE TITLE
i18n: portuguese translation

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#567]
Our first Bootcamp in Sao Paulo is about to get started 🎉, which implies that our _content_ is being translated into portuguese.

In order to accommodate the translation the following decisions have been made:

## Branches

1. We have merged all pending PRs into master, tagged the _current_ version of the content as `v1.0.0` and created a _maintenance branch_ ([`v1.x`](https://github.com/Laboratoria/curricula-js/tree/v1.x)) that will serve two puposes:
   1. to provide a maintenance branch for the Bootcamp currently running in Guadalajara
   2. to provide a _stable_ point for the portuguese translation to take place.

2. @ivandevp will create a _branch_ with the name `v1.x-pt` based on the above mentioned `v1.x` branch. It is this branch (`v1.x-pt`) where @cemsbr should direct his pull requests and keep updated with.

This is a short term solution, as development of `v2.x` comes along (more on this very soon) and the Bootcamp progresses, we would ideally get the instructors involved, helping @cemsbr to gradually _migrate_ to the new version of the _content_. This is mostly about weeding stuff out, reorganising files into a different structure, and changes to very specific bits of actual content (reads, exercises, quizzes, ...).

The next _version_ of the curriculum (`v2.x`) will take into account i18n (internationalisation), so the long term goal is to integrate both _languages_ in the same branch (under a common file structure).

## New parser features

Related to these changes, and relevant mainly to @ivandevp and @AnaSalazar for the time being, we have added `locale` and `suffix` to take into account the translated courses.

```sh
course-parser 11-react/README.md --track js --locale es-ES
```

In order to avoid `id` collisions with existing courses, when parsing a translated course we should use the `suffix` option:

```sh
course-parser 01-intro/README.md --track js --locale pt-BR --suffix pt
```

This will produce a JSON object where the courseid is `01-intro-pt` (instead of the default `01-intro`).

cc/ @ivandevp @AnaSalazar @cemsbr

**Comment by cemsbr** [comment]
Nice work. I'll be migrating the Brazililian Portuguese version in the next days and sending you PRs.

**Comment by vanessapinheiro** [comment]
Great! Thank you!
