### ISSUE TITLE
Cifrado, proyecto individual

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/curricula-js#570]
Un poco extemporáneo pero lo planteo igual.

Dado que es el primer proyecto, yo propondría que sea en equipo, puede ser parejas (la versión más simple de trabajo en equipo). Creo que es importante considerar:
- Ir de menos complejidad a más (el enfoque de cono: <)
- feedback y metacognición ocurren naturalmente cuando la responsabilidad es compartida. (sobretodo por ser el proyecto 1)

https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/01-cipher

@lalogf @lupomontero @rocioalberdi @valesmithb @alejandrarv @LucileBaratier

**Comment by lupomontero** [comment]
De acuerdo _el enfoque de cono_ 😉

Personalmente me gusta la idea de que el _primer_ proyecto sea individual, en el sentido de que cada una debe hacer su propia implementación y desplegarla. Por otro lado, sí creo que tiene sentido que trabajen por squads, enfatizando el **peer-learning** y **peer-review**, pero no entraría en la mecánica de trabajo en equipo (desde el punto de vista de software: _pair programming_, _pull requests_, _merges_, _issues_, ...).

En el segundo o tercero proyecto incluiría trabajo y entregable por parejas, con un énfasis en trabajo en equipo y herramientas convenciones al respecto.

Thoughts 🤔?

**Comment by alejandrarv** [comment]
De acuerdo con Lupo!

**Comment by rocioalberdi** [comment]
Más que promover creo que hay que formalizar instancias de peer learning y peer review en el primer proyecto.
Por ejemplo, que piensen en el usuario en conjunto con su squad y logren identificar sus necesidades,  o que en la parte de testing recurran a alguien para probar su proyecto, etc. 
En el segundo proyecto deberían trabajar en parejas para entrenar habilidades como trabajo en equipo, adaptabilidad, comunicación, negociación, etc.

**Comment by diegovelezg** [comment]
Tratando de abstraer un poco. Una cosa es el alcance y reglas del proyecto y otra las dinámicas o herramientas de aprendizaje.

** Permanente, (Aprendizaje colaborativo)**
- peer feedback
- discusión self learning o tópicos sociados
- Toolkits/guías del tipo "qué hago si estoy atascada"?
- etc.

**Reglas específicas del proyecto:**
- Individual, parejas, tríos, squad, etc.
- Indicaciones de pair programming, PRs, Merges, etc.

**Comment by diegovelezg** [comment]
Como el único que estaba (ya no) "en desacuerdo" era yo, creo que lo podemos cerrar con tranquilidad.
