### ISSUE TITLE
Bootcamp: Refactor data dashboard project for v2.x

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#573]

**Comment by lupomontero** [comment]
Ver: https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/02-data-dashboard

Falta:

- [ ] Agregar detalles de evaluación (parte técnica)
- [ ] Linkear _tópicos_ (JS y UX)
- [ ] Completar sección _hacker edition_ (parte técnica)
- [ ] Describir mecánica de colaboración entre parejas (pair programming, forks, issues, pull requests, merges, ...)
- [ ] Completar sección de _pistas/tips_

**Comment by FabianBravoA** [comment]
https://github.com/Laboratoria/curricula-js/pull/611

**Comment by chamodev** [comment]
https://github.com/Laboratoria/data-dashboard/pull/4

**Comment by lupomontero** [comment]
El único punto que queda _pendiente_ es "incorporar una descripción de la mecánica de colaboración entre parejas (pair programming, forks, issues, pull requests, merges, ...)". Esto está pendiente en un (#628) de @Gabx04, así que cierro este issue en favor del PR.
