### ISSUE TITLE
Project: Cipher: Guía de estilos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#576]
Agregar referencia a guía de estilos y linters (eslint y htmlhint) en descripción del reto.

Ver: https://github.com/Laboratoria/cipher/issues/8

cc/ @chamodev

**Comment by ivandevp** [comment]
@chamodev cuando trabajamos con los Googlers, armamos [una guía de estilos](https://github.com/Laboratoria/js-style-guide) para `ES5`, que igual hay muchas reglas que aplicarían para `ES6`. Tengo entendido que para el reto del cipher estamos usando la que viene por defecto con `eslint`, cierto @lupomontero?

**Comment by lupomontero** [comment]
> Tengo entendido que para el reto del cipher estamos usando la que viene por defecto con eslint, cierto @lupomontero?

Así es.

Acabo de [agregar un parrafito sobre guías de estilo y linters](https://github.com/Laboratoria/curricula-js/commit/e8ec1262de4b8196a547f5f7aa96d014a307dd85) a la descripción del reto. El último parrafito en la sección de [Consideraciones Generales](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/01-cipher#consideraciones-generales). También he agregado la configuración "recomendada" por defecto en la configutación de `eslint` (en el archivo `.eslintrc`).

cc/ @chamodev
