### ISSUE TITLE
Unix Shell, propuestas para material y alcances 

### ISSUE THREAD

**Issue by Jonhks** [Laboratoria/curricula-js#577]
Abro este issue para que podamos conversar y proponer cómo llevar el tema de Unix Shell. 

Podríamos empezar por:
* Explorar o aclarar qué queremos cubrir.
* Y qué recursos tenemos o conocemos.

Si alguien tiene material o alguna idea, le agradeceria lo comparta. 

@lupomontero @Laboratoria/developers

**Comment by merunga** [comment]
@Jonhks te refieres a [la apertura](https://github.com/Laboratoria/curricula-js/tree/master/02-basic-programming/01-shell%2Bgit/01-command-line) o a la [leccion de cli](https://github.com/Laboratoria/curricula-js/blob/76cd35b7c324fcafc2a7578838a6d5eb2d3df24c/05-deep-dive/02-env/00-opening/README.md)?

Creo q si la idea es reciclar la mayor cantidad de contenido y alineado al objetivo que vamos a ser *nix compatibles y que cada "topic" debe ser mínimo pero completo, creo q lo mas alineado que tenemos es la [leccion de shell](https://github.com/Laboratoria/curricula-js/tree/76cd35b7c324fcafc2a7578838a6d5eb2d3df24c/05-deep-dive/02-env/01-shell) del anterior 05-deep-dive.

**Comment by FabianBravoA** [comment]
Hay que tener en cuenta, y también recomendar, instalar algún terminal de linux en windows. Hasta ahora en el marketPlace las alumnas pueden instalar : 

- Ubuntu
- SuSE
- Fedora

Así pueden ejecutar todo tal cual como si tuvieran ubuntu totalmente instalado en sus computadoras.

**Comment by merunga** [comment]
Que fue de [lo que conversamos](http://community.laboratoria.la/t/linux-en-computadoras-de-alumnas/112/18)? Las laptops ya tienen dual boot?

**Comment by FabianBravoA** [comment]
Así es, pero dado el tiempo la mejor opción para quienes tienen windows es instalar la compatibilidad con linux a través de instalar una distribución a través del marketplace.
No es emular linux en windows, es correr linux tal cual dentro de windows.

**Comment by merunga** [comment]
Personalmente creo que ese camino deberiamos comentarlo, pero no recomendarlo. Creo que deberia ser el caso excepcional, por ejemplo si necesitan usar la compu de alguien mas, o trabajar en un cyber o biblioteca, o para UX dp del common core, pero no deberia ser el camino **recomendado**... ya que ante la primera frustración _switch back to windows_.

Creo que durante el common core la recomendación debería ser **Aprende a usar Linux**. No se cual es la opinión _oficial_, y me imagino que cada sede tiene autonomía en esto, pero creo que la experiencia es más enriquecedora si las sacamos durante un tiempo de windows...

De nuevo:

![image](https://user-images.githubusercontent.com/211721/39757552-d146cf4e-5292-11e8-9d49-f1fcf56911df.png)

@Laboratoria/developers si pudieran colaborar con la [información de su SO](http://community.laboratoria.la/t/linux-en-computadoras-de-alumnas/112/19). Gracias!

**Comment by FabianBravoA** [comment]
Nuevamente, instalar a través del marketplace de windows una distribución *instala linux*.
De hecho el objetivo de microsoft es que más desarrolladores vayan a su plataforma y se sientan cómodos.
Por lo que "aprender a usar linux" es perfectamente posible a través de windows. 

Para mi es una opción que si *hay que recomendar*.

**Comment by ivandevp** [comment]
Mi opinión sería que las laptops tengan _dual boot_ y que armemos una guía de cómo usar lo que ofrece el marketplace de Windows y que ellas escojan. Creo que deberíamos motivar a que sea una distro de Linux, pero como comenté en el Discourse, es probable que algunas quieran seguir practicando en sus PCs o laptops personales y no las van a formatear (no todas al menos). Así les damos opciones y la decisión final es de ellas.

**Comment by FabianBravoA** [comment]
Dado que existen ya 3 distribuciones en el marketPlace de windows, no veo
por qué hacer el dual boot. Creo que queda un poco redundante y complicado
hacerlo, especialmente para las alumnas que recién están dando sus primeros
pasos en la programación.

**Comment by nerdale** [comment]
Hola!
Creo que con la lección del [lms](https://lms.laboratoria.la/cohorts/test/courses/basic-programming/01-shell+git/00-opening) que dice @Jonhks está bien, si bien Michelle en su momento lo arregló para que no solo abarcara windows, creo que al punto 2. GIT le falta un poquito eso, pero en general bien.
Eso si, es necesario que en la clase se de mucho énfasis a entender como realmente funciona el flujo y no solo aprender una serie de comandos que si bien funcionan, no entienden que sucede por detrás.

Sobre los sistemas operativos, concuerdo con que muchas no van a querer formatear su computador por distintos motivos así que es una buena opción lo que recomienda @FabianBravoA para que al final las estudiantes puedan elegir sobre que trabajar, Fabián lo ha usado y funciona perfecto.

Como dato acá en Chile el equipo técnico utiliza Linux, Mac y solo 1 Windows por temas de compatibilidad con programas de UX.

**Comment by AnaSalazar** [comment]
Yo estoy a favor de esto:
@merunga 
> la idea es reciclar la mayor cantidad de contenido
vamos a ser *nix compatibles de aquí en adelante, pero no necesariamente windows compatible
y que cada "topic" debe ser mínimo pero completo
Entonces lo más alineado que tenemos es la lección de shell del anterior 05-deep-dive.

Y de lo que dice @Jonhks : 
> Quizás podríamos abarcar las 2 en una sola lección . El material que mencionas se me hace muy bueno.

También estoy totalmente de acuerdo con @FabianBravoA de no migrarlas a todas y solo hacer uso de las terminales para no generarles una carga más como menciona Jonh.

**Comment by lupomontero** [comment]
Gracias a todxs por sus comentarios! 💪 

Para este "release", queda ya mezclado el tópico con las siguientes lecturas:

* https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/shell/01-intro/01-intro
* https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/shell/02-filesystem/01-fs

Cierro este issue por ahora, y el tema de las instalaciones de GNU/Linux y/o dual boot lo continuamos conversando por el foro, ok?
