### ISSUE TITLE
i18n: parts' metadata 

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#579]
As the first PR about Portuguese translation was merged (#578), the metadata of each part has been translated too and when running our parser it doesn't get them because we're currently supporting Spanish and English. 

Should we add a validation for supporting Portuguese metadata keywords or these shouldn't be translated?

**Example:**

Current metadata:

```text
* Tipo: `leitura`
* Formato: `individual`
* Duração: `10 min`
```
Parser validation:

```bash
error: 00-welcome/00-opening => Could not parse part duration
error: 00-welcome/00-opening => Unkown part format "individual". Valid formats: "guided", "self-paced"
error: 00-welcome/00-opening => Unkown part type "leitura". Valid types: "read", "seminar", "workshop", "quiz", "practice", "other"
```

cc/ @cemsbr

**Comment by cemsbr** [comment]
Where is the parser code?

**Comment by lupomontero** [comment]
I just realised the repo was private. I have now made it public:

https://github.com/Laboratoria/course-parser

**Comment by ivandevp** [comment]
I'll close this issue since this has been solved
