### ISSUE TITLE
Finalizar Data Visualization README.md

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#59]
@MariPlaza:

Ya creé el branch para el curso de `Visualización de Datos`: https://github.com/Laboratoria/curricula-js/tree/18-data-visualization

También le he añadido un _DRAFT_ del README.md en base al google doc que hemos trabajado. Sin embargo, necesita afinarse, agregando el Syllabus final, los detalles del producto (el data dashboard que las estudiantes crearán), las referencias bibliográficas, etc.

El primer next step que tendríamos sería llegar a la versión final de este README.md. Para eso he creado este issue.

cc: @CaroLaboratoria

**Comment by lupomontero** [comment]
Podemos asumir que la primera iteración (work in progress) está _finalizada_? Dejamos este issue abierto o lo cerramos en favor de issues más específicos?

cc/ @chamodev @MariPlaza @CaroLaboratoria

**Comment by MariPlaza** [comment]
Podemos cerrarlo Ya tenemos la primera versión draft del curso lista.

Ahora falta feedback, diseño etc. Lo puedo cerrar en unas horas.

Saludos,

**Comment by chamodev** [comment]
Agree. Lo cierro porque ya están trabajando en pendientes a nivel más granular.
