### ISSUE TITLE
v2.x Strings

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curricula-js#599]
@lupomontero la propuesta de contenido para `Strings`.

Como siento q bombardear con links no viene funcionando, va una propuesta concretísima: 
Todo el contenido de https://javascript.info/string (exceptuando la parte de _Internals y Unicode_), en formato **literate** con **`console.log`** o **`console.assert`**
Un link a [interpolacion de MDN](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/template_strings) para profundizar la que quiera en ese tema.

creo q hasta los ejercicios propuestos estan buenos para usarlos.

* aqui el original en `md` en ingles
https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/05-data-types/03-string/article.md

**Comment by lupomontero** [comment]
Me parece muy chévere 👍 

La propuesta es traducirlo/adaptarlo usando _literate_ y "reciclar" los _ejercicios_ en formato de nuestro LMS?

**Comment by merunga** [comment]
exacto

**Comment by lupomontero** [comment]
ETA?

**Comment by merunga** [comment]
Sin los ejercicios -> PR viernes mediodia PET
Si @RuthSalvador y @Danielalab me ayudan con esa parte de los ejercicios :sweat_smile: , quizas esos puedan estar para comienzos de la proxima semana.

**Comment by lupomontero** [comment]
Cerrado en https://github.com/merunga/curricula-js/commit/d4d5fc28010ec355200450fb15878e4b812dd614
