### ISSUE TITLE
Desarrollar Lección 01-introduction del curso Intro a JS #43

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#60]
To Do:

- [x] @PapuRivarola hacer texto de [00-welcome](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/01-introduction/00-welcome-and-orientation.md)
- [x] @PapuRivarola hacer texto de [01-growth-mindset](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/01-introduction/01-growth-mindset.md)
- [x] @chamodev crear quiz
- [x] @chamodev crear auto-evaluación
- [x] @ivandevp revisar y aprobar [lectura 02 por qué aprender a programar](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/01-introduction/02-why-learn-to-code.md)
- [x] @ivandevp revisar y aprobar [lectura 03 tu primer website](https://github.com/Laboratoria/curricula-js/blob/intro-js/01-intro/01-introduction/03-your-first-website.md)
- [x] @MichelleSV crear videos de "JavaScript en el navegador"
- [x] @MichelleSV crear videos de " Crea tu primera web HTML"
- [x] @MichelleSV crear videos de " Agrega interacción a tu web con JS"
- [x] @ivandevp revisar y aprobar los 3 videos
- [x] @diegovelezg coordinar "test" con usuarios que no saben de código para validar que el material (lecturas, videos, cuestionario y reto) se entiende y cumple con el objetivo de aprendizaje

**Comment by chamodev** [comment]
Team,

He subido al branch los textos de @PapuRivarola sobre `Growth Mindset` y una versión actualizada del `welcome`. Además, he subido los 3 videos que ha preparado @MichelleSV. Me parece que están geniales! (felicidades @MichelleSV!!). Denle una revisada ustedes y @diegovelezg consolida el feedback. 

Quedan pendientes los items de @ivandevp y de @diegovelezg (a quien le he pasado el item de crear el quiz y la auto-evaluación).

Gracias!
R

**Comment by chamodev** [comment]
@diegovelezg:

Aquí la encuesta y el quiz:
- [Encuesta](https://goo.gl/forms/RrUrEVEDSvZKSxTu1)
- [Quiz](https://goo.gl/forms/eQgwALBRp8FUh5TB2)

**Comment by chamodev** [comment]
Otros cambios:

- [ ] video de GM con subtítulos @PapuRivarola 
- [ ] cambios de Jimena @PapuRivarola

**Comment by diegovelezg** [comment]
@chamodev no veo el auto assessment (está marcado como done en el checklist)

**Comment by chamodev** [comment]
@diegovelezg, es mi comentario anterior:

Aquí la encuesta y el quiz:
- [Encuesta](https://goo.gl/forms/RrUrEVEDSvZKSxTu1)
- [Quiz](https://goo.gl/forms/eQgwALBRp8FUh5TB2) 

También los pasé por slack.

**Comment by lupomontero** [comment]
@chamodev: este issue se puede considerar como "_resuleto_"? Si es así, puedes cerrarlo, porfa?

cc/ @diegovelezg

**Comment by chamodev** [comment]
Correcto @lupomontero. Cerrado
