### ISSUE TITLE
topics(css): transformar workshops, seminarios y clases presenciales a ejercicios sugeridos o guiados

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#600]
El _curso_ (tópico) de [CSS](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css) contiene varias _partes_ de tipo `workshop` y `seminar`. Estos son principalmente enunciados de ejercicios que se hacían de forma guiada con lxs _coaches_, en la clase. Dentro de `v2.x` estamos separando todo lo que es _agenda_ y _proyectos_ fuera de lo que son los tópicos, así que tenemos que _convertir_ estas _partes_ en _lecturas_ de "ejercicios sugeridos o libres", que después pueden usar igual como ejercicio guiado en la clase, pero a nivel de contenido debe estar _escrito_ con narrativa _self-paced_; el contenido no debe asumir que los ejercicios se van a resolver en clase, si no dejarlos abiertos para que se puedan _consumir_ de la manera que sea necesario. Las _partes_ en cuestión:

- [x] [01-css/03-guided-exercises](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/01-css/03-guided-exercises)
- [x] [01-css/07-guided-exercises](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/01-css/07-guided-exercises)
- [x] [01-css/10-guided-exercises](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/01-css/10-guided-exercises)
- [x] [01-css/13-closing](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/01-css/13-closing) (o convertir en lectura o sacar por ahora)
- [x] [02-responsive/05-guided-exercises](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/02-responsive/05-guided-exercises)
- [x] [02-responsive/18-closing](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/02-responsive/18-closing) (o convertir en lectura o sacar por ahora)
- [x] [03-frameworks/06-guided-exercises](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/03-frameworks/06-guided-exercises)
- [x] [03-frameworks/09-closing](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/03-frameworks/09-closing) (o convertir en lectura o sacar por ahora)

***

Por otro lado...

- [x] [01-css/00-opening](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/01-css/00-opening): habla de html y css, propongo quitar la parte de html y en todo caso mover los puntos que sean de html (guía de preguntas y conceptos clave) al [_tópico_ de HTML](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/html).

**Comment by nerdale** [comment]
Okas, gracias @lupomontero 
Lo revisaremos y te avisamos.

**Comment by brecabal** [comment]
Ya realizados los cambios con @nerdale  PR #601 

@lupomontero
