### ISSUE TITLE
Go live Level 5

### ISSUE THREAD

**Issue by CaroLaboratoria** [Laboratoria/curricula-js#603]
@lupomontero 
El Go Live del proyecto 5 tengo en mi calendario que tiene que ser el 3 de Agosto.
Puedes revisar la fecha por favor?

Gracias!
@diegovelezg

**Comment by lupomontero** [comment]
Hola @CaroLaboratoria, como conversamos ayer, el nivel 4 tiene una duración esperada de 2 meses (con un mínimo de dos proyectos en paralelo - Serverless y Library).
