### ISSUE TITLE
Feedback curso 01-intro

### ISSUE THREAD

**Issue by ivandevp** [Laboratoria/curricula-js#61]
En este issue pondré todos los detalles que pueden no estar claros o es necesario entrar en contexto, respecto al desarrollo de contenido del curso `01-intro` desarrollado por @chamodev

**Comment by ivandevp** [comment]
@chamodev En la lección 11 de `Ejercicios guiados` el segundo ejercicio, `areArraySame`, menciona de crear una función comparando los elementos de un arreglo, sin embargo, los conceptos revisados hasta ese punto involucran variables, tipos de datos, operadores, condicionales, loops y funciones. Crees conveniente tocar el tema de arreglos en este punto?

**Comment by chamodev** [comment]
@ivandevp 

Gracias por el feedback.

Listo. Moví el ejercicio `areArraySame` a los ejercicios guiados de Arrays y Objetos. En su lugar, incluí el ejercicio de `Cifrado César` (pendiente que Closes #33).
