### ISSUE TITLE
Feedback Dashboard de Importaciones - Exportaciones para curso de Visualización

### ISSUE THREAD

**Issue by MariPlaza** [Laboratoria/curricula-js#66]
Hola Caro y Alejandro.  Soy nueva en esta parte de Issues en Github, así que espero estarlo haciendo bien :)

Está es la propuesta del dashboard que aprenderán a hacer las muchachas en el curso de visualización: 
https://public.tableau.com/profile/publish/Laboratoria-CursodeVisualizacin-DatadeComerciodePasesLatinoamricanos/PerfilComercialporPas#!/publish-confirm

Obviamente los gráficos de pie de importaciones y exportaciones, están descuadrados y se va a arreglar antes de publicar la oferta a las jovenes, pero dado que esto ocurre por una descordinación extraña entre Tableau y la publicación hacia Public, decidí invertirle tiempo cuando vayamos a la versión final. 

Por ahora necesito de ustedes su apoyo en los siguientes puntos: 

@CaroLaboratoria: porfa coordina (como chateamos) con el experto de UI de Laboratoria, para saber su feedback de donde colocaría cada gráfico, los filtros etc. 

@arcuellar88 : Alejandro, primero que nada Bienvenido!, seguro será un placer trabajar de la mano dado que tenemos el mismo interés. Me comentó Rodulfo que tu podías dar información / ideas sobre fuentes de información alternativas que pudieramos usar para el curso. 

Por ahora use información de Comtrade sobre la región porque es pública y aunque no es tan simple, tan poco es tan desconectada de la vida del día a día de cada uno de nosotros. Sin embargo, quizás conozcas otras fuentes de datos abiertos que podamos usar y sean también interesantes. Lo importante es que:
- La data nos permita  realizar los mismos tipos de gráficos que vez acá: barras, líneas, pie, burbujas, mapas etc.  
- Idealmente introduzca nuevos conceptos a las estudiantes para que comiencen a desarrollar el área de negocios que se requiere en la ciencia de datos. 

Gracias anticipadas a ambos y conversamos esta semana.

**Comment by arcuellar88** [comment]
Hola @MariPlaza, 

muchas gracias por la bienvenida. 

Datos abiertos hay muchas opciones ( por ejemplo [link](http://dataportals.org/search)) 

Yo veo varias opciones: 

1) Dar muchas opciones y que los estudiantes decidan cual utilizar
2) Encontrar un tema común investigando un poco los intereses de los estudiantes (Qué proyectos han hecho antes?, en qué industria están trabajando? etc. 
3) Proponer un tema de interés general como la música ([link](https://webscope.sandbox.yahoo.com/catalog.php?datatype=r))
4) Datos de desarrollo económico y social como el del dashboard que propones. 
     Posibles temas: 
      educación, energía, comercio, etc. 

      Posibles fuentes: 
     [Banco Mundial ](http://data.worldbank.org/), [ Banco Interamericano de Desarrollo ](https://data.iadb.org/) (BID) o datos abiertos de países: [Peru](http://www.datosabiertos.gob.pe/) , [Colombia](https://www.datos.gov.co/), etc.

Un tema interesante que hice en el BID fue un dashboard de indicadores de género.  Yo trabajé principalmente en el procesamiento de los datos (ETL) y el código está [Github](https://github.com/arcuellar88/gender-indicator). El dashboard lo hicimos en Tableau pero hasta el momento no está publico. El dashboard tiene mapas, barras, lineas pie, etc y los datos vienen del Banco Mundial, del BID y de [NCD](https://github.com/fathominfo/noceilings-data).

**Comment by CaroLaboratoria** [comment]
Hola,

Por mi parte les cuento que @lalogf ya está revisando el dashboard. En la reunión de hoy @MariPlaza hablamos sobre las posibles mejoras.

Sobre el tema a trabajar en el curso, sería ideal trabajar en la opción 1 que propone @arcuellar88. Parte de los resultados de un Sprint Design que tuvimos hace un par de semanas dentro de Laboratoria, tiene relación con que la motivación de las alumnas aumentaría al darles la posibilidad de que ellas elijan el proyecto en el cual trabajar. Si logramos tener una cantidad de proyectos/data y que ellas tomen la decisión sería algo increíble a desarrollar en este curso. Les parece si lo conversamos el Viernes?

Saludos!

**Comment by lupomontero** [comment]
Hola @MariPlaza, @arcuellar88 y @CaroLaboratoria,

Antes que nada, gracias por la iniciativa ;-)

He seguido un poco la conversación, además de leer el `README.md` del curso, y me gustaría hacer un par de comentarios/sugerencias con respecto a las herramientas de visualización.

Tableau es una buena plataforma, pero tiene el inconveniente de que que es "propietaria". Puede servir de ejemplo para aprender a "pensar en data", tipos de visualizaciones, ... sin tener que entrar en detalles de implementación, pero en el contexto de la currícula de Full Stack JavaScript, quizás tenga sentido incluir herramientas nativas de JavaScript como [D3](https://d3js.org/) o [Vega](https://vega.github.io/vega/), que son librerías Open Source implementadas en JavaScript.

Qué piensan? Quizás se sale del _scope_ de este curso, pero quizás sea interesante plantear un curso complementario donde puedan "programar" las visualizaciones usando herramientas como D3 y/o Vega.

My 50 cents. Thoughts?

cc/ @chamodev

**Comment by arcuellar88** [comment]
Hola @lupomontero,

Estoy de acuerdo con el tema de Tableau. Ese era uno de los puntos que quería discutir  en la llamada que tenemos el viernes. 

D3 o Vega están más alineado con los otros cursos que ofrece Laboratoria. Yo no he trabajado mucho con esas herramientas. @MariPlaza tu que tanto las conoces? Si no tenemos los skills podemos buscar un curso de D3 que ya exista y traducirlo a español.

**Comment by CaroLaboratoria** [comment]
Hola,

Efectivamente ese es uno de los temas que vamos a terminar de conversar el Viernes.
Nos estamos inclinando porque el curso sea basado en Tableau y ofrezcamos un taller de D3 adicional. De esta manera mantenemos el curso abierto en un futuro para quién lo quiera tomar y le damos un plus a nuestras coders a través del taller.

Qué les parece algo así? @lupomontero @arcuellar88

**Comment by MariPlaza** [comment]
Hola @lupomontero Gracias por el comentario, lo más probable es que el enfoque final sea el que menciona @CaroLaboratoria.  

Este tema, lo he hablado mucho con @chamodev desde el comienzo y exploramos varias opciones. Incluida la de que yo montará el contenido teórico y las visualizaciones que se quieren hacer y luego se desarrollará el como se hace en D3. Ahora bien, en esas conversaciones también salió el punto de exponer a las estudiantes a todos los tipos de ambientes que pueden encontrar en el ambito laboral y más específicamente al tipo de herramientas que van a encontrar si se van por el área de datos y comienzan a interactuar con personas en roles de negocio como finanzas, mercadeo, ventas, etc. 

La versión de Tableau que se usaría es Tableau Public, que aunque sigue siendo propietaria es gratuita para todo el mundo dada la limitante de tener que grabar el resultado en servidores públicos expuestos a todo el mundo. Como el curso se basa en data abierta, pues esa limitante no existe acá. 

Este curso representa la primera aproximación hipersimplificada hacia otra rama de educación dentro de Laboratoria que se dirija más hacia la Ciencia de Datos para aprovechar las habilidades que ya se han desarrollado con la curricula actual de Laboratoria. 

Los Cientificos de Datos, cuando trabajan proyectos fuera del ambiente corporativo, usan principalmente 2 herramientas Open Source: R y/o Python.  Y estas herramientas tienden a tener librerias que te permiten usar todo lo disponible para JavaScript, por ejemplo R cuenta con las librerías d3r y vegalite para integrar lo que ellas aprendieron en JavaScript.  

Sin embargo, la Ciencia de Datos cuando es trabajada en el ambiente corporativo, tiende a irse por esquemas mixtos de tecnologías propietarias y open sources porque tienen que cumplir una serie de requerimientos adicionales como gobierno de Capital Intelectual, Privacidad y Control de acceso a la información, etc etc.  En esta parte, se da el escenario interesante que plataformas como [Cloudera Data Science Workbench](https://www.cloudera.com/products/data-science-and-engineering/data-science-workbench.html) o [Azure Learning Machine](https://studio.azureml.net/) tienen módulos más drag and drop pero siempre  permiten correr códigos de R y Python para integrarlos en el proyecto. 

Inclusive el mismo Tableau en su versión paga permite integración con R y Python. 

Concluyendo el punto, el enfoque de este curso son las visualizaciones de manera agnóstica a la tecnología. ¿Qué es un gráfico de barras, cuando y porque lo uso?, lo mismo para una serie de tiempo, etc. La escogencia de Tableau fue al principio para montar rápido el dashboard sobre el cual construir el curso y después ver en que tecnología se desarrollaba, pero por ahora tiende a ser la primera opción por el simple hecho que el drag and drop (excepto en el gráfico Sankey que se va a excluir de este curso) permite mantener el enfoque en la visualización y su significado y no en el código necesario para lograrla. Después que los conceptos estén claros, se pueden complementar con talleres para hacerlas basadas en muchas librerías como D3, GoogleViz entre muchas otras opciones. 

Se escuchan comentarios para que podamos tomar una decisión específica el viernes.

**Comment by lupomontero** [comment]
@CaroLaboratoria: creo que podría ser una buena solución. Cuándo dices taller te refieres a otro curso 4x4?

Quizás podríamos tener dos cursos independientes: éste y uno posterior dónde podamos introducir usos específicos y herramientas de JavaScript a través de un proyecto donde tengan que codear visualizaciones con D3 y/o Vega por ejemplo.

**Comment by lupomontero** [comment]
@MariPlaza: añadí mi comentario antes de ver que habías posteado tú también 😳 

Entiendo perfectamente el planteamiento y me parece totalmente válido. Sólo quería añadir el punto de vista del _big picture_ de la malla curricular (Full Stack JS) y el flujo de aprendizaje a lo largo de los diferentes cursos.

Conversen el viernes y ya me irán contando 💪 

Gracias!

**Comment by MariPlaza** [comment]
@lupomontero jajajaja de eso se trata la colaboración en línea. Aunque yo no voy tan rápido como tú ;). 

Cuando mencioné hace un tiempo que quería conversar con @chamodev antes de dar mi feedback para saber si era relevante, me refería justo al tema de la malla curricular, porque si lo veo desde la perspectiva de Datos únicamente (enfoque que NO es el Laboratoria ahora) los nombres me parecen muy orientado a lo técnico. Me abstuve de comentar el detalle porque entendí con la conversación con @chamodev, que en efecto el objetivo ahorita va hacia esas habilidades y para esa población objetivo los nombres de la malla curricular son completamente adecuados. 

Este curso de visualización es un experimento, para ver si tiene o no sentido hacer una rama más orientada a la Ciencia de Datos en Laboratoria, y en caso de que si tenga sentido, es probable que la malla curricular que se ha venido desarrollando, sea presentada como una caja de herramientas técnicas y luego se presenten estos cursos como una derivación (no tan técnica) de esa excelente base que ellas han venido y seguiran desarrollando. 

Lo interesante de la Ciencia de Datos y la tecnología es que se complementan perfecto, por ejemplo, a mi me encantaría saber el detalle que las alumnas han desarrollado de HTML y CCS para hacer más sencilla las técnicas de WebScrapping que más de una vez utilizó para recolectar datos. Pero de todas formas no hay que perder de vista que la Ciencia de Datos no es sólo tecnología, así como la tecnología no es sólo para Ciencia de Datos.  

Conversando seguro iremos encontrando el balance entre la curricula oficial de Laboratoria y esta rama experimental.  

Para cerrar y como no conozco que tanto conocen todas las personas sobre la Cienta de Datos, les comparto este breve [articulo que escribí](https://cienciadedatosenespanol.wordpress.com/2017/06/22/que-se-requiere-para-ser-un-cientific-de-datos-introduccion-al-blog/)

**Comment by arcuellar88** [comment]
Hola todos,

Este es el resumen de la llamada de hoy con @MariPlaza y @CaroLaboratoria:

1. En la primera semana del curso vamos a incluir:  
  - Explicaciones de qué son las dimensiones, metricas, agregaciones, etc. 
  - Pequeña introducción a los Metadatos 
 - Vamos a incluir una explicación de los pasos que hay que seguir para tener los datos en un dashboard sin entrar en detalles (ETL=extracción, transformación y carga) 
2. En la semana que presentamos los distintos tipos de gráficos 
  - Los videos se van enfocar en las ventajas y desventajas de cada gráfico, cómo se usan y cuando se usan. 
- Para la parté técnica de cómo hacerlos nos vamos a apoyar de lo tutoriales en linea que ofrece Tableau en español. 
     https://www.tableau.com/es-es/learn/training
     http://onlinehelp.tableau.com/current/pro/desktop/es-es/buildexamples_bar.html

3. Datasets
- Vamos a revisar la granularidad de los datasets. La idea es que el tipo de datos sea lo más parecido al que se utiliza en el ambiente laboral. Los datos que estábamos usando hasta el momento son de indicadores los cuales ya están agregados. Sugiero utilizar datos de retail (ventas).  @MariPlaza y @CaroLaboratoria van a tomar la decisión final la próxima semana. 

- Preparar los datos para la visualizaciones: En este curso no vamos a enseñar cómo preparar los datos (extraerlos, limpiarlos y ordenarlos). Los datasets que utilizaremos para las visualizaciones ya van a estar preparados. 

**Ideas:**

- Contactar a Tableau. Tal vez nos pueden dar licencias o ayudar de alguna forma
@CaroLaboratoria, los podrías contactar a nombre de laboratoria?
 https://www.tableau.com/academic/teaching/course-licenses

- Empresas. Como en el curso de UX sería interesante hacer un proyecto paralelo con datos de empresas que quieran en colaborar con el curso. 

**Mi aporte al curso** 
Como las visualizaciones no son mi fuerte yo voy a colaborar en: 
- Preparar los datasets (tanto para las explicaciones como para los proyectos)
- Revisar todos los módulos del curso . 
- Hacer la explicación de los metadatos

@MariPlaza Preferí subir este resumen acá y no en un .md para que todos pudieran verlo y comentar.

**Comment by MariPlaza** [comment]
Hola todos,

El viernes tuvimos una llamada @arcuellar88  Alonso Ortiz y @CaroLaboratoria. Ante todo gracias a todos, los comentarios fueron de mucho valor y ya se han ido incorporando al desarrolllo del curso.

A continuación el resumen:
- Se conversó sobre la data de ejemplo, y se acordó continuar con la de penetración de Internet e incluir la de manejo de ordenes como una de las fuentes de datos adicionales disponibles para el trabajo final de las alumnas.
- @arcuellar88 mencionó incluir la parte de explicación de ETL y metadatos. Estos conceptos están incluidos en la lección 2 del curso a través de videos introductorios. 
- @arcuellar88 mencionó que la comunidad online de Tableau puede colaborar en dar feedback y/o ser jurado de visualizaciones. Es super interesante de estudiar como incorporarlos al curso.
- @arcuellar88 va a ver las opciones para las datas adicionales para el trabajo final. 
- Alonso mencionó la importancia de explicar los conceptos claves sin el uso de la computadora. En consecuencia, se diseñaron juegos de tableros para explicar las agregaciones numéricas que permitiran a las estudiantes entender los conceptos antes de que comiencen a aplicarlos con la tecnologia. 
- Alonso mencionó conocer una persona de Tableau Foundation y coordinará con Carolina para ver cómo pueden apoyar más a largo plazo a Laboratoria. 
- Acordamos proceder con el desarrollo del contenido de la semana 1 e ir adaptando el Syllabus según vaya surgiendo durante el desarrollo del contenido del curso. 

Gracias a todos por sus comentarios y participación. Fue una reunión muy productiva. 

Siguientes pasos:
- @arcuellar88 Te preguntó: Quieres / puedes asumir el desarrollo de los puntos Lección 2 - 2 - Limpieza de Datos y Lección 2 - 3 - Metadatos y Diccionario. La idea sería desarrollar el script para un futuro video de una duración alrededor de 6 minutos, aunque si necesitas más tiempo para explicar los conceptos, se adapta este tiempo. 
- @CaroLaboratoria ya comencé a desarrollar el contenido de los otros elementos incluidos los juegos con la visión que mencionó Alonso. Quisiera que conversaramos 30 minutos al principio de la semana para ver como desarrollar la producción de los videos y los materiales sencillos que se requeriran en los juegos. 

Saludos y feliz y productiva semana.

**Comment by arcuellar88** [comment]
Hola @MariPlaza,

Listo yo hago el script para las sección de limpieza de datos y metadatos. Para cuando debo tener la primera versión?
Para cuando debo tener los datasets?

Saludos,

Alejandro R.

**Comment by MariPlaza** [comment]
Gracias @arcuellar88, por tu experiencia, eres la persona más idónea para desarrollarlos. Porfa en el primero de los 2 scripts incluye una breve presentación de ti mismo. 

Sobre las fechas, te pregunto, ¿te da chance de tener los scripts listos para este viernes al final del día?. Si no, cuando es realista para ti. 

Los datasets, si prefiero que tu nos indiques cuando te es realista, porque se que puede implicar bastante tiempo. 

La idea es tener el contenido del curso listo al finalizar Agosto. Por ahora vamos desarrollando 1 semana de contenido del curso por semana lo que nos situa a finales de Julio, principios de Agosto con el contenido desarrollado, pero después toca edición y correcciones, por eso es que estamos apuntando a finales de Agosto tener todo listo. Sólo hay un contenido que depende de los datasets (el 3.3) y se puede dejar para el final según como tu te puedas coordinar. 

Gracias nuevamente.

**Comment by arcuellar88** [comment]
Ok perfecto. No alcanzo para este viernes. 

Propongo estas fechas:
1) Scripts 18 de Julio
2) Data sets 25 Julio

**Comment by MariPlaza** [comment]
Perfecto ambas fechas. Gracias! Feliz desarrollo de contenido.

**Comment by MariPlaza** [comment]
Gracias a todas las personas por su apoyo. El curso ya está muy avanzado y prácticamente listo en una primera versión. Cierro este issue, y seguimos avanzando como ya lo hemos hecho. Gracias nuevamente, está quedando muy bien gracias al feedback de todos.
