### ISSUE TITLE
Propuesta para curso Node.js

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#71]
Se ha creado la ["plantilla" para la propuesta del curso "Building HTTP servers with Node.js"](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/node).

El siguiente paso para el desarrollo de este curso es identificar un "creador".

cc/ @chamodev @ivandevp @nandodrw @rodrwan

**Comment by krol3** [comment]
Me gustaria contribuir !

**Comment by lupomontero** [comment]
@krol3: gracias por el interés 🎉 y disculpa por la demora en responder 😰

Cuando tengamos más claro las necesidades del _contenido_ te aviso para ver cómo puedes echarnos una mano. Cuál es tu experiencia con Node?

**Comment by krol3** [comment]
Haciendo APIs em nodejs com express e proyectos serverless

**Comment by lupomontero** [comment]
Hola @krol3, otra vez disculpa por la demora en contestar :see_no_evil: 

Por el momento no creo que vayamos a _producir_ contenido como tal de Node.js / Express dentro del contexto de la currícula. En vez de eso ahora estamos planteando un _proyecto_ a través del cual puedan aprender _haciendo_.

Acá puedes ver el proyecto: https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/05-bq-node

Siempre estamos abiertos a sugerencias y comentarios :smile:
