### ISSUE TITLE
projects(bq-node): Feedback/validación de coaches

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#729]
Hola @Laboratoria/bootcamp-coaches,

Hace un par de días se subió a la rama `v2.x` la propuesta del proyecto _electivo_ de backend con Node.js.

Agradecería un montón si pueden dar feedback y dejar comentarios por acá. Como muchxs saben llevamos conversando sobre este proyecto ya un tiempo y se han tenido en cuenta sugerencias de varixs coaches de varias sedes (LIM, SCL, CDMX). Ahí les dejo el link al proyecto en este repo:

https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/05-bq-node

Como viene siendo habitual, también existe un repo creado para el _chapter de developers_ (o quizás el _chapter de coaches_) que pueden forkear y clonar para implementar sus soluciones:

https://github.com/Laboratoria/bq-node

Por otro lado, en mi fork del repo del _chapter_ también encontrarán la implementación modelo con el proyecto _resuelto_ (sin hacker edition):

https://github.com/lupomontero/bq-node/tree/develop

***

Por ahora hemos tenido algunos comentarios en chats _privados_, pero sería bueno recolectar los puntos de vista acá y ver qué podemos sacar o agregar para que pueda ser factible en todas las sedes, cada una con sus necesidades.

También sería de gran ayuda que hagan su fork, clonen y ejecuten el código del boiler en sus computadoras para probarlo... estoy seguro que pueden aparecer issues y cosas a mejorar. Lo más importante es que ejecuten los tests _end-to-end_: `yarn e2e` o `npm run e2e`.

Gracias! :muscle: :balloon:

**Comment by espinozasenior** [comment]
La propuesta de Backend me parece excelente, los incnvenientes que veo son en la implementación, con mi experiencia en el actual Bootcamp resumo:

1. No veo viable la implementación de éste tópico sin extender el período del bootcamp o sacrificar un projecto de la actual curicula.

2. Para facilitar el aterrizaje para éste proyecto creoconveniente exigir desde los inicios del bootcamp el uso de la base de datos **Firestore** de **Firebase** y así su familirización con la arquitectura de colecciones y documentos como los es MongoDB.

3. Creo conveniente incluir dentro del plazo y a inicios del desarrollo del proyecto una semana de ejercicios prácticos (no coding) previo a éste proyecto de **ejercicios de diseño de arquitectura de aplicaciones** para que las alumnas desarrollen ése sentido de resolver lógicas de negocios que no han desarrollado hasta ahora desde la perspectiva Frontend.

**Comment by lupomontero** [comment]
Gracias por el feedback @espinozasenior.

1. La idea era que este proyecto sea _electivo_ y creo que la idea es que lo puedan continuar/completar después de terminar el Bootcamp... aunque esto al final depende de cada sede. @developerVilchez, @Danielalab, @RuthSalvador, como lo ven ustedes en el contexto del calendario de Lima?

2. Si no me equivoco, en este Bootcamp ya se han topado con Firebase/Firestore en 2 o tres proyectos antes de llegar a los electivos... :thinking: Entiendo que no podemos eperar que se _profundice_ en el tema de BBDD, y NoSQL en particular, pero creo que en este caso la expetativa/necesidad del proyecto es relativamente menor. Qué piensan el resto?

3. Entiendo que la idea de incluir _una semana de ejercicios de diseño de arquitectura de aplicaciones_ queda fuera de scope para este Bootcamp, sobre todo teniendo en cuenta el punto 1, no? Para entender un poco mejor, podrías aclarar a qué te refieres con estos ejercicios? Podrías poner un ejemplo o proponer una dinámica concreta para que quizás lo puedan tener en cuenta en CDMX que tienen más tiempo o futuros bootcamps.

cc/ @lizzie136 @shirley-suarez @Jonhks @mikenieva @FabianBravoA @nerdale @MarciaMillanao

**Comment by espinozasenior** [comment]
Aclarado el ounto #1 y #2.
Con respecto al punto #3, expongo un caso: En el proyecto de Burguer Queen, hoy (16 de Octubre) hubo la primera sesión de Demos. En el cual se les preguntó a las alumnas "¿Cuál ha sido el mayor reto hasta ahora en el proyecto?", la mayoría respondió que la estructuración de la data; el cómo estructurar la lógica del negocio. Noté que la mayoría presentó un diseño amigable y estético. Hubo una alumna (Noely Flores) donde el día previo me senté alrededor de 45 min con ella ya que está usando Vue (el framework que me desenvuelvo) y comenzamos a discutir sobre la lógica de negocio de un restaurante real, los posibles estados que puede llegar a tener una orden, cuales son los que nunca faltan, porqué un mesero no puede poner la orden como "preparada", porqué enfocarnos para éste caso en la estrecha relación de 1-a-1 de orden y mesa, ventajas y desventajas entre atacar el problema co una lógica u otra, entre otras cosas. Y el día de hoy la verdad que me dejó sorprendido, quizás fue el demo más feo entre todos pero en resolución de problema fue el más completo.

Y eso es a lo que me refiero. Ejercicios que desarrollen ése 6to sentido de la lógica de negocio y resolución de problemas de programación. En mi caso por ejemplo, en la universidad tuve un antes y un después de que vi la materia de Base de Datos. El profesor nos colocaba enunciados de problemas reales (eg: Burguer Queen) y nosotros a papel y lápiz teníamos que armar la base de datos: entidades, tipos de relaciones y explicar (ante todos) porqué dicha estructura/arquitectura resolvía las necesidades (Queries) del "cliente".

**Comment by lupomontero** [comment]
Muchas gracias por el feedback @espinozasenior. Lo tendremos en cuenta para este Bootcamp que recién empieza...

Por ahora voy cerrando este issue. Porfa @Laboratoria/bootcamp-coaches abran nuevos issues para cualquier reporte de bug, sugerencia, comentario, idea, ...
