### ISSUE TITLE
topics(angular / vue)

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curricula-js#748]
Si bien tenemos contenido actualizado para React, creo q deberiamos ser menos opinionated y nivelar la cancha con recursos para `angular` y `vue`.

Existe de la version anterior de la curricula una leccion para angular, pero me parece q esta desactualizada tanto en la version del framewotk, como en el formato del LMS.

Los docs tanto de angular como de vue estan super cheveres y traducir parte de ellos y linkear sus examples, considero que podria ser una buena y rápida estrategia para solucionar esta situación.

**Comment by lupomontero** [comment]
Me parece buena idea. Quién se anima con esta iniciativa?

cc/ @Laboratoria/bootcamp-coaches @Laboratoria/developers

**Comment by JoshDev1205** [comment]
Hello

Justo pasaba por aquí :smile: y me gustaría saber si podría colaborar con este ISSUE ???

Para la parte de Vuejs en especifico :smile:

**Comment by lupomontero** [comment]
Hola @JoshDev1205, gracias por tu comentario :rocket: :star:  ...y disculpa por la demora en contestar :see_no_evil: 

Sería buenazo que pudieras echarnos una mano con temas relacionados a _Vue_. De hecho, a corto plazo no tenemos pensado generar contenido sobre frameworks de forma independiente, sino apoyarnos en los recursos oficiales, que ya empiezan a haber en español, y en todo caso nos podemos sumar a esos esfuerzos de forma más amplia.

Por otro lado, ahora nos estamos enfocando mucho en los _proyectos_ que hacen nuestras estudiantes y no tanto en el contenido (lecturas, videos, ...) que preparamos para ellas. De hecho, hay [un proyecto en particular donde sugerimos Vue como tecnología de implementación](https://github.com/Laboratoria/curricula-js/tree/master/projects/04-burger-queen), junto a React y Angular. Sería incríble si le puedes dar una leída y quizás sugerir alguna cosa (empezando por recursos en la última sección).

Cierro este issue por ahora, que ya está un poco viejito, pero porfa abran issues nuevos si quieren continuar la conversación o sugerir/comentar algo sobre el proyecto mencionado arriba.
