### ISSUE TITLE
project(data-lovers): implementación modelo

### ISSUE THREAD

**Issue by lizzie136** [Laboratoria/curricula-js#750]
- [x] Seleccionar indicadores
- [ ] Actualizar con los requerimientos de la nueva versión del README.md https://github.com/Laboratoria/curricula-js/pull/747
- [ ] Presentar en chapter de coaches

**Comment by lupomontero** [comment]
@shirley-startary @Jonhks @mikenieva: cuándo completamos la implementación modelo? Qué les parece mañana 4pm hora de Lima?

**Comment by shirley-startary** [comment]
Me encantaría, solo que tenemos ahora la pre-admisión, no sé si haya la posibilidad de que lo recorramos después de las 6:30 pm

**Comment by lupomontero** [comment]
Les parece si avanzo un poco durante el día (enviando PRs) y lo revisamos juntxs al final del día?

**Comment by Jonhks** [comment]
@lupomontero andamos en pre-admisión estos días :( Podría ser la siguiente semana? Ya nadamos un poco más relax!

**Comment by shirley-startary** [comment]
¿Podemos reunirnos hoy jueves a las 2:30 hora MX para continuar con esta implementación?

**Comment by lupomontero** [comment]
Agrego acá las cosas pendientes después de revisión de mi implementación modelo con @shirley-startary y @Jonhks:

- [ ] Filtrar por rangos de años 
- [ ] Limitar ancho de pantalla (en pantallas grandes)
- [ ] Botón de settings más grande y obvio
- [ ] Hacer más obvio que se puede interactuar con las gráficas (prender apagar paises por gráfica)

Espero poder completar estas tareas antes del próximo hangout del chapter de coaches para presentarlo ahí. Alguien sabe a quién le toca organizar el próximo hangout de coaches?

**Comment by lupomontero** [comment]
Gracias a @shirley-startary y @RuthSalvador tenemos dos implementaciones modelo en proceso de review :smile: 

* https://github.com/Laboratoria/data-lovers/pull/7
* https://github.com/Laboratoria/data-lovers/pull/8

Si no recuerdo mal también estaba la implemetación de @Jonhks.

... y aprovecho también a compartir mi implementación modelo (con un enfoque centrado en los tests):

* UI: https://lupomontero.github.io/data-lovers/
* Repo: https://github.com/lupomontero/data-lovers/tree/lupomontero

@lizzie136, te acuerdas que te ofreciste a documentar una lista con todas las implementaciones modelo? Podrías mandar propuesta de cómo manejar esto en el repo privado de `curricula-ejecucion`?

Por ahora, teniendo las implementaciones modelo que hay, creo que podemos ir cerrando este issue.
