### ISSUE TITLE
project(data-lovers): aclarar si deberíamos sugerir atributos de filtrado, ordenado y estadísticas

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#751]
Este issue se ha extraído del PR #747:

Ver: https://github.com/Laboratoria/curricula-js/pull/747#pullrequestreview-181877538

**Comment by lupomontero** [comment]
cc/ @Danielalab

**Comment by gaposx** [comment]
@Danielalab : Creo que podría darse un ejemplo, tal como se da en las estadísticas, pero no incluiría sugerencias basadas en la data del proyecto porque pueden influenciar y dar pie a que lo entiendan como un requerimiento.

**Comment by lupomontero** [comment]
@Danielalab: podemos considerar la pregunta como _resuelta_?

**Comment by Danielalab** [comment]
@lupomontero Si , ya esta resuelta , gracias 👍

**Comment by lupomontero** [comment]
Gracias @Danielalab. Cierro este issue entonces.

Para cualquier otra consulta o sugerencia no dudes en abrir un nuevo issue.

:muscle:
