### ISSUE TITLE
project(data-lovers): archivo de sketch no se puede visualizar en Windows

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#752]
Este issue se ha extraído del PR #747:

Ver: https://github.com/Laboratoria/curricula-js/pull/747#pullrequestreview-181881336

cc/ @Danielalab

**Comment by lalogf** [comment]
El archivo de sketch se puede abrir en https://www.figma.com/

**Comment by lupomontero** [comment]
@Danielalab, @gaposx, @lalogf: podemos considerar este _issue_ como resuelto?

**Comment by gaposx** [comment]
Ok de mi parte!

**Comment by lupomontero** [comment]
Gracias @Danielalab. Cierro este issue entonces.

Para cualquier otra consulta o sugerencia no dudes en abrir un nuevo issue.

:muscle:
