### ISSUE TITLE
Actualizar mapa de proyectos en README

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#757]
Ver: https://github.com/Laboratoria/curricula-js#mapa-de-aprendizaje

**Comment by lizzie136** [comment]
@lupomontero Hola, cómo podría actualizar eso? cuál es la nueva versión? Me dan luces 🙏 ?

**Comment by lupomontero** [comment]
Cierro este issue por inactividad... por si acaso los cambios de @CaroLaboratoria ya están en `master` :tada:
