### ISSUE TITLE
project(cipher): Actualizar proyecto con cambios que se usaron en última iteración en Lima

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#761]
Hace unas semanas se revisó este proyecto y se introdujeron algunos cambios que creo que no quedaron del todo reflejados en este repo. Alguien se ofrece como voluntarix para echar una mano con esto?

cc/ @diegovelezg @CaroLaboratoria @lalogf @rocioalberdi @gaposx @developerVilchez @Danielalab @RuthSalvador @Gabx04

**Comment by gaposx** [comment]
@lupomontero : Me apunto a revisar el proyecto actual con las versiones LIM y SCL y hacer el PR correspondiente.

**Comment by lizzie136** [comment]
Hola @gaposx @diegovelezg cuáles son los cambios? lo van a poder subir? para tenerlos para CDMX y GDL :)

**Comment by lupomontero** [comment]
Hola @gaposx, gracias por el ofrecimiento :tada: 

Te acabo de agregar como _assignee_ a este issue/tarea, ok?

Quedamos a la espera de PR :wink:

**Comment by lupomontero** [comment]
Cierro este issue en favor de revisar el PR https://github.com/Laboratoria/curricula-js/pull/771
