### ISSUE TITLE
project(visitors): Revisar y actualizar proyecto

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#762]
El objetivo de este proyecto es revisar y actualizar el proyecto [`03-visitors`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-visitors) para el bootcamp `2018-2` en LIM :peru: y SCL :chile: y `2019-1` en CDMX y GDL :mexico:.

:information_source: Esta revisión tendrá que tener en cuenta que este proyecto se va a hacer _antes_ que la Red Social ([`03-social-network`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-social-network)), y no después como se hizo en el último Bootcamp. Con lo cual, este proyecto se convierte en el último del _common core_.

Cuando se planteó este proyecto originalmente las estudiantes ya habían hecho la Red Social, y por tanto ya tenían familiaridad con asincronía, `fetch`, HTTP, y Firebase. En el Bootcamp actual llegarán habiendo pasado solamente por _Cipher_ y _Data Lovers_, con lo cual nos toca reconsiderar el _scope_ y _objetivos de aprendizaje_.

Con respecto a los objetivos de aprendizaje, hasta ahora el proyecto dice simplemente [algo como pondrán en práctica _todo lo aprendido hasta ahora_](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-visitors#objetivos-de-aprendizaje). Creo que en esta nueva iteración toca cambiar eso y hacer que asincronía, `fetch`, HTTP y concepto de serverless sean el foco.

Me gustaría pedir ayuda de coaches para hacer esta _revisión_ y completar una implementación modelo. Se aceptan voluntarixs :stuck_out_tongue: 

Se agradecen todo tipo de sugerencias, comentarios, dudas, ...

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @CaroLaboratoria @lalogf @rocioalberdi @alejandrarv @valesmithb

**Comment by CaroLaboratoria** [comment]
Hola, me gustaría hacer un comentario al respecto. Después del proyecto 2, las estudiantes se separarán en 3 instancias, Proyecto 3 FE, Proyecto 3 UX que será una iteración sobre el proyecto 2 (cierto @lalogf ) y para algunas será la posibilidad de "ponerse al día" de "nivelarse" o de ejercitar un poco más. Todo lo anterior dentro del Common Core todavía.
Es importante recalcar que esta instancia fue planteada como una posibilidad de conocer un poco más lo que les espera en el track y además como una instancia de profundización . 
El punto está en que si agregamos "contenido nuevo" al proyecto 3, las estudiantes que viene de "nivelación" debe de poder igual continuar con el track o sea el Proyecto 4 (Red Social).

@diegovelezg @lupomontero @lalogf @rocioalberdi

**Comment by lupomontero** [comment]
Gracias por la aclaración @CaroLaboratoria.

Entonces este proyecto quedaría como _opcional_ dentro del _common core_, no?

Qué factores y quién determina qué estudiante hace qué proyecto en este punto?

***

Por otro lado, en este momento estoy completando la [impementación modelo del proyecto `02-data-lovers`](https://github.com/Laboratoria/curricula-js/issues/750) con la ayuda del equipo de coaches en CDMX (@shirley-startary, @Jonhks y @mikenieva), y parece que el equipo de Lima (@merunga, @Danielalab, @developerVilchez, @RuthSalvador y @MaiaRojas) va a liderar la [revisión del proyecto `03-social-network`](https://github.com/Laboratoria/curricula-js/issues/763).

Qué les parece si el equipo de SCL se adueña de este proyecto (con mi apoyo)?

cc/ @FabianBravoA @nerdale @MarciaMillanao @bosqueinvierno @camargozzini

**Comment by CaroLaboratoria** [comment]
El flujo que estábamos pensando, es que en la entrevista final del proyecto 2, las coaches puedan recomendar a las estudiantes por qué camino seguir. Esta recomendación iría muy de la mano de las habilidades desarrolladas durante los dos primeros proyectos. Si la estudiante necesita un poco más de tiempo, se le recomienda pasar a "nivelación" (lo pongo entre comillas porque todavía no nos gusta el nombre). Si es que la estudiante va super bien, queremos que siga enfrentando nuevos desafíos que sería el proyecto 3.
@lalogf creo que sería útil que contarás en resumen cuál va a ser el proyecto 3 de UX.

**Comment by lupomontero** [comment]
En conversaciones con @CaroLaboratoria, @diegovelezg, @rocioalberdi y @lalogf estamos barajando dos posibilidades para la semana del Bootcamp que cubre este proyecto.

1. Proyecto `03-visitors` revisado, acotando _scope_ y agregando un _boilerplate_ que sirva de guía e incluya ya un setup básico para esmodules, firebase, ... Esto es lo planteado en el [comentario original de este _thread_](https://github.com/Laboratoria/curricula-js/issues/762#issue-390001580).
2. Alternativamente, hacer una _segunda parte_ del proyecto `02-data-lovers`, permitiendo a las estudiantes iterar sobre lo ya construido en vez de introducir un proyecto nuevo. En este caso entiendo que estaríamos agregando _requerimientos_ no contemplados en la [primera parte](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers).

Antes de poder tomar una decisión informada creo que sería bueno hacer una propuesta más concreta sobre la opción 2 y qué implicaría esto (qué nuevos requerimientos estaríamos agregando, cómo lo presentamos a las estudiantes, ...), así como la disponibilidad de _coaches_ para echar una mano con la implementación modelo y boilerplate de `03-visitors` en caso fuéramos adelante con esto.

**Comment by Danielalab** [comment]
Hola @lupomontero , con relación al proyecto *03-visitors* tengo la duda de si al acotar el scope aun se vería el tema de asincronía, fetch,http o si se quitaría, ya que tendríamos a estudiantes ''nivelandose'' que deben de poder igual continuar con el Proyecto 4 (Red Social)

**Comment by lupomontero** [comment]
Gracias por tu comentarios @Danielalab. Mi idea es que `03-visitors` sí incluya _asincronía_, `fetch`, _HTTP_, ... Es necesario para que pueda ver integración con un _backend_ (_serverless_ con _Firebase_ en este caso), pero presentarlo con un _boilerplate_ que sirva de guía.

Por otro lado, con respecto a las estudiantes que se que hagan "nivelación" o se queden iterando sobre `02-data-lovers`, creo que no sería problema que pasen después al proyecto de _Red Social_. Esa era la ruta original... Además, `03-visitors` es como un _extra_ para aquellas que están avanzando un poco más rápido.

Qué opinan?

cc/ @CaroLaboratoria @diegovelezg @rocioalberdi @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
Como parte de la contrapropuesta al proyecto `03-visitors`, qué sería _continuar_ con el `02-data-lovers`, que les parecen las siguientes ideas de otros requerimientos que podríamos agregarle:

* Completar _hacker edition_
* Crear interfaz para _otra_ fuente de datos
* Agregar testing a los componentes de interfaz (no solo a las funciones que procesan data)

Agregando requerimientos nuevos para aquellas que ya han completado `02-data-lovers` nos permitiría ganar un poco de tiempo y permitir que todas las estudiantes sigan avanzando (cada una a su ritmo).

**Comment by CaroLaboratoria** [comment]
Me inclinaría en que el proyecto  front sea individual, por las siguientes ideas:
1) Creo que después de hacerlo en duplas y enfrentarse solas al problema, puede ser que se hagan muchas preguntas que anteriormente no se hayan planteado, dado que la compañera ya lo tenía claro.
2) También es una buena instancia de realmente completar un proyecto y ponerlo en el futuro portafolio individual.
3) Permite una mejor "observación" por parte de las coaches justo antes de la división de tracks (lo que es un objetivo de hacer este proyecto).

Si es en duplas, 100% de acuerdo con Diego en que sea autoorganización, pero si se junta una nueva dupla no entiendo mucho como no van a heredar código ajeno de una de las dos? Tendrían que hacer todo de nuevo? @diegovelezg

**Comment by camargozzini** [comment]
Holaa, el equipo de coaches de Chile nos sumamos a todos los acuerdos. Y la iteración de UX tb la haremos individual para poder observarlas mejor, y ahora estamos coordinándonos para ver que es lo que les pediremos de entrega (estoy pensando que sería bueno acercamiento a usuario real a través de testeo, análisis de uso a través de herramientas como hotjar y rediseño de interfaz.. para que tengan una pincelada de diferentes partes del proceso UX).

**Comment by lupomontero** [comment]
Hola @camargozzini, gracias por tu comentario :tada: 

1. Tomo nota de la confirmación por parte de equipo de SCL
2. Iteración de UX individual :+1: 
3. Con respecto a los nuevos _requisitos_, creo que solo faltaría que que integremos la info de UX en [este PR](https://github.com/Laboratoria/curricula-js/pull/768).

cc/ @lalogf @gaposx @Gabx04

**Comment by lupomontero** [comment]
Cierro este issue ya que esto queda resuelto en https://github.com/Laboratoria/curricula-js/pull/768
