### ISSUE TITLE
project(social-network): Revisar y actualizar proyecto

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#763]
El objetivo de este proyecto es revisar y actualizar el proyecto [`03-social-network`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-social-network) para el bootcamp `2018-2` en LIM :peru: y SCL :chile: y `2019-1` en CDMX y GDL :mexico:.

:information_source: Esta revisión tendrá que tener en cuenta que este proyecto se va a hacer _después_ que el Registro de Visitantes ([`03-visitors`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-visitors)), y no antes como se hizo en el último Bootcamp. Con lo cual, este proyecto se convierte en el primero del _track de Front-end dev_.

Para este proyecto consideraría agragar un _boilerplate_ mínimo para que usen _ESModules_ (`import`/`export`) y así facilitar la modularización. Junto con esto creo que fundamental acompañar el proyecto con una serie de píldoras alrededor de arquitectura de interfaces, división de responsabilidades en el código y TDD.

Me gustaría pedir ayuda de coaches para hacer esta _revisión_ y completar una implementación modelo. Se aceptan voluntarixs :stuck_out_tongue: 

Se agradecen todo tipo de sugerencias, comentarios, dudas, ...

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @CaroLaboratoria @rocioalberdi @alejandrarv @valesmithb

Ver https://github.com/Laboratoria/curricula-js/issues/762

**Comment by merunga** [comment]
Hola @lupomontero !
Para el track de FE en Lima ya estamos trabajando en las pills para este proyecto. Creo que desde aquí nos podemos encargar.
@Danielalab @developerVilchez @RuthSalvador @MaiaRojas me ayudan :pray: ?

**Comment by merunga** [comment]
Ahora en relación a los updates, me parece genial que nos olvidemos del scope global en el track, ahora nos queda definir cual es la estrategia. Entonces lo primero sería definir qué haríamos con los *modules*.

Hoy todos los navegadores modernos ya [soportan modulos](https://caniuse.com/#feat=es6-module) es sus versiones de escritorio (no en las móbiles, excepto chrome). Si decidimos targetear sólo escritorio, entonces por ese lado estaríamos cubiertos. Aquí una [prueba de concepto](https://codesandbox.io/s/ykx9ry02mv) y [docs](https://developers.google.com/web/fundamentals/primers/modules#browser) al respecto

Luego en el mundo node, donde debemos testear nuestro código, la version [v11](https://nodejs.org/api/esm.html) con el flag `--experimental-modules`, permiten utilizar módulos sin necesidad de configurar babel, pero sólo para archivos `.mjs`... no se si es demasiado *experimental*.

Y la alternativa que nos permite mayor soporte, menor riesgo, pero un poco mas de complejidad, es configurar `babel` con [`@babel/plugin-transform-modules-commonjs`](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs).

Comentarios?

**Comment by lupomontero** [comment]
@merunga, con respecto al ofrecimiento a hacerse cargo junto con @Danielalab, @developerVilchez, @RuthSalvador y @MaiaRojas, sería buenazo! Espero confirmación por parte de ellas para asignar el _issue_ formalmente.

Por otro lado, con respecto al tema de _módulos_, creo que preferiría vivir con una configuración de Babel antes que depender del combo `node v11+` + `--experimental-modules` + archivos `.mjs`. Quizás es todavía demasiado experimental.

Qué opinan el resto?

/polls 'ESModules Nativos en Navegador y  `Node.js v11+` + `--experimental-modules` + archivos `.mjs`' 'ESModules con `Babel` + `@babel/plugin-transform-modules-commonjs`' 'ESModules con `Webpack` + `Babel`' 'Otro bundler' 'Sin módulos (UMD, global, ...)'

cc/ @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
@merunga, con respecto al ofrecimiento a hacerse cargo junto con @Danielalab, @developerVilchez, @RuthSalvador y @MaiaRojas, sería buenazo! Espero confirmación por parte de ellas para asignar el _issue_ formalmente.

Por otro lado, con respecto al tema de _módulos_, creo que preferiría vivir con una configuración de Babel antes que depender del combo `node v11+` + `--experimental-modules` + archivos `.mjs`. Quizás es todavía demasiado experimental.

Qué opinan el resto?

/polls 'ESModules Nativos en Navegador y  `Node.js v11+` + `--experimental-modules` + archivos `.mjs`' 'ESModules con `Babel` + `@babel/plugin-transform-modules-commonjs`' 'ESModules con `Webpack` + `Babel`' 'Otro bundler' 'Sin módulos (UMD, global, ...)'

cc/ @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
/polls 'ESModules Nativos en Navegador y  `Node.js v11+` + `--experimental-modules` + archivos `.mjs`' 'ESModules con `Babel` + `@babel/plugin-transform-modules-commonjs`' 'ESModules con `Webpack` + `Babel`' 'Otro bundler' 'Sin módulos (UMD, global, ...)'

**Comment by merunga** [comment]
@lupomontero no puedo ver bien el poll, pero mi voto:
`Babel` + `@babel/plugin-transform-modules-commonjs`

**Comment by lupomontero** [comment]
...hmm... parece que ya no funciona la app de `polls`... :see_no_evil:

**Comment by Danielalab** [comment]
Hola, en el boilerplate que se le daría a las estudiantes si utilizamos **Babel + @babel/plugin-transform-modules-commonjs** contendría toda la configuración de babel (el script, .babelrc, @babel/plugin-transform-modules-commonjs) o dejaríamos que ellas realicen la configuración?

**Comment by merunga** [comment]
@danielalab en cualquiera de los casos, ya vendria configurado en El boilerplate

**Comment by Danielalab** [comment]
Hola, estuve leyendo el Readme que les dimos a las estudiantes en el BC pasado y me surgieron un par de dudas de como sera la estructura del proyecto ya que ahora forma parte de track de Front-end: 
- En cuanto a los requerimientos de UX, seguirán siendo los mismos? ya que existen algunas habilidades/tópicos que no se han podido ver en common core.
- Se mantendrá la estructura de trabajo en tríos?
- El boilerplate que les daríamos a las estudiantes, a parte de la configuración de babel, tendría una estructura de archivos/carpetas, setup de test/eslint/htmlhint o sería libre?

**Comment by Danielalab** [comment]
@Laboratoria/bootcamp-coaches Hola queríamos saber si estaban de acuerdo en que el proyecto se siga realizando en tríos?

**Comment by diegovelezg** [comment]
Para discutir (mejoras simples):
- Toda la parte de filtrar posts públicos y privados, y lo de agregar amigos y está rarísima, sobretodo porque agregar amigos es hacker edition. @lalogf 
- Compartir en Facebook o Twitter aporta poquísimo valor pero no hace daño ¿no?
- La parte de Soft skills también necesita una revisada. @rocioalberdi

**Comment by lupomontero** [comment]
@diegovelezg:

>     * Compartir en Facebook o Twitter aporta poquísimo valor pero no hace daño ¿no?

No sé qué opinan lxs coaches, pero en mi opinión personal creo que puede agregar ruido ya que explorar integraciones con terceras partes (otras redes sociales) no es parte de los objetivos _principales_ de aprendizaje...

>     * La parte de Soft skills también necesita una revisada. @rocioalberdi

Alguna novedad con respecto a esto @rocioalberdi ?

***


Ver también: #797 y #846

**Comment by lupomontero** [comment]
Ya está integrado #846 (ver https://github.com/Laboratoria/curricula-js/commit/1e8f7ab96b84376a21db0eb5387f8e8a6cf12c5b)... así que cierro este issue :muscle: 

Gracias @merunga y @Danielalab
