### ISSUE TITLE
project(job-application): Revisar y actualizar proyecto

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#764]
El objetivo de este proyecto es revisar y actualizar el proyecto [`04-job-application`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/04-job-application) para el bootcamp `2018-2` en LIM :peru: y SCL :chile: y `2019-1` en CDMX y GDL :mexico:.

Se agradecen todo tipo de sugerencias, comentarios, dudas, ...

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @CaroLaboratoria @lalogf @rocioalberdi @alejandrarv @valesmithb

**Comment by CaroLaboratoria** [comment]
Creo que en general este proyecto cumplió su objetivo principal: preparación profesional de nuestras estudiantes. Planteo los siguientes temas a conversar/mejorar:
1) Cuándo lanzamos y hacemos este proyecto? El tema del multitasking no estaría permitiendo que las estudiantes realicen bien este proyecto, pero por otro lado, el mundo real implica que se hagan 2 cosas o más en paralelo. En mi opinión lo único que no haría en paralelo es el punto 5 o sea el de los desafíos.
2) Uno de los temas a mejorar es el de los desafíos del punto 5. Me gustaría saber qué paso en realidad, Se hicieron? Cuándo? @valesmithb @alejandrarv @pautrevino 
3) En general, hacer las entrevistas técnicas con coaches cruzado de los países fue una buena experiencia  para las estudiantes como para los Laboratorians. La pregunta es, es sostenible mantener esta instancia con Bootcamps en diferentes tiempos? (Nota: sería genial incluir a SAP en estas entrevistas).
4) Una mejora a realizar sería actualizar las preguntas técnicas con las que se estén realizando hoy en día. 
Feliz de empezar a conversar sobre este tema.

**Comment by diegovelezg** [comment]
> Creo que en general este proyecto cumplió su objetivo principal: preparación profesional de nuestras estudiantes. Planteo los siguientes temas a conversar/mejorar:
> 
> 1. Cuándo lanzamos y hacemos este proyecto? El tema del multitasking no estaría permitiendo que las estudiantes realicen bien este proyecto, pero por otro lado, el mundo real implica que se hagan 2 cosas o más en paralelo. En mi opinión lo único que no haría en paralelo es el punto 5 o sea el de los desafíos.

De acuerdo en que EVITEMOS que el punto 5 sea en paralelo a proyectos. El multitasking del mundo real ESTÁ MAL! 

> 2. Uno de los temas a mejorar es el de los desafíos del punto 5. Me gustaría saber qué paso en realidad, Se hicieron? Cuándo? @valesmithb @alejandrarv @pautrevino

En general, tenemos que trackear mejor cada ve que una estudiante hace una entrevista y no solamente el resultado final. hay algunas que pasaron después de más de un intento y no está trackeado.

> 3. En general, hacer las entrevistas técnicas con coaches cruzado de los países fue una buena experiencia  para las estudiantes como para los Laboratorians. La pregunta es, es sostenible mantener esta instancia con Bootcamps en diferentes tiempos? (Nota: sería genial incluir a SAP en estas entrevistas).

Creo que hay que plantearlo como objetivo con anticipación para que cada ciudad se pueda organizar. Este es un claro ejemplo de beneficio-reciprocidad-mutualismo.

> 4. Una mejora a realizar sería actualizar las preguntas técnicas con las que se estén realizando hoy en día.

Urge una revisada completa a los retos (FE y UX)

>    Feliz de empezar a conversar sobre este tema.

Agrego: Entender bien las "mock interviews" que hizo @alejandrarv en Lima y ver si tiene sentido extender a oras ciudades.

**Comment by alejandrarv** [comment]
Hola! 

Copio el mensaje de Caro y Diego para responder. Mis rptas están en negritas, ojalá que se entienda jajaj 

Uno de los temas a mejorar es el de los desafíos del punto 5. Me gustaría saber qué paso en realidad, Se hicieron? Cuándo? @valesmithb @alejandrarv @pautrevino **Acá no se llegaron a hacer por tiempo.** 
En general, tenemos que trackear mejor cada ve que una estudiante hace una entrevista y no solamente el resultado final. hay algunas que pasaron después de más de un intento y no está trackeado. **Acá sí lo tenemos trackeado**

En general, hacer las entrevistas técnicas con coaches cruzado de los países fue una buena experiencia para las estudiantes como para los Laboratorians. La pregunta es, es sostenible mantener esta instancia con Bootcamps en diferentes tiempos? (Nota: sería genial incluir a SAP en estas entrevistas).
Creo que hay que plantearlo como objetivo con anticipación para que cada ciudad se pueda organizar. Este es un claro ejemplo de beneficio-reciprocidad-mutualismo. **De acuerdo! Creo que sí lo podemos ir coordinando**

Una mejora a realizar sería actualizar las preguntas técnicas con las que se estén realizando hoy en día.
Urge una revisada completa a los retos (FE y UX) **+1 Para esto involucramos a Placement cierto?**

Agrego: Entender bien las "mock interviews" que hizo @alejandrarv en Lima y ver si tiene sentido extender a oras ciudades. **Háganlo! Fue una súper experiencia para ellas y no nos demandó mucho más tiempo. Lo que me preocupa ahora es la logística porque no tendremos a todo el equipo en tracks, pero con fe**

**Comment by CaroLaboratoria** [comment]
@andreamarianalm vamos viendo cómo podemos actualizar las preguntas técnicas.

**Comment by lupomontero** [comment]
Cerrando este issue por inactividad... para cualquier otra sugerencia o cambio abramos nuevos issues y/o PRs.
