### ISSUE TITLE
project(md-links): Revisar y actualizar proyecto 

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#765]
El objetivo de este proyecto es revisar y actualizar el proyecto [`04-md-links`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/04-md-links) para el bootcamp `2018-2` en LIM :peru: y SCL :chile: y `2019-1` en CDMX y GDL :mexico:.

Se agradecen todo tipo de sugerencias, comentarios, dudas, ...

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @CaroLaboratoria @rocioalberdi @alejandrarv @valesmithb

**Comment by diegovelezg** [comment]
@lalogf ¿crees que deberíamos considerar algo de UX aquí? ¿Alguna recomendación?

**Comment by lalogf** [comment]
No se me ocurre mucho más que la documentación de su módulo de `npm` y quizás el testear cómo un usuario lo instala y utiliza. No mucho más. Siento que es un reto mucho más técnico.

**Comment by lupomontero** [comment]
Creen que sea necesario agregar algo explícito al [`README.md`](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/04-md-links) del proyecto?

**Comment by lupomontero** [comment]
Cierro este issue ya que creo que no queda nada pendiente... si me equivoco porfa re-abran issue... :see_no_evil:
