### ISSUE TITLE
Propuesta: Usar `Biblioteca` en vez de `Librería`

### ISSUE THREAD

**Issue by juanjordan** [Laboratoria/curricula-js#772]
Hola 👋, he notado que por lo menos en el proyecto Cipher (https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/01-cipher#consideraciones-generales)
> La lógica del proyecto debe estar implementada completamente en JavaScript (ES6). En este proyecto NO está permitido usar librerías o frameworks, sólo vanilla JavaScript.

estamos usando `Librería` para referirnos a lo que en Inglés se conoce como `Library` mientras que la traducción directa de Librería sería `Bookstore`. Esto es conocido como un [false friend](https://en.wikipedia.org/wiki/False_friend).

Es curioso que en [Wikipedia en Español](https://es.wikipedia.org/wiki/Biblioteca_(inform%C3%A1tica)) recién el 27 de Julio del 2018 fue indicado que usar Librería para referirse a la traducción de Library es un vicio del lenguaje. 

Dado que estamos orientando a las estudiantes a llevarse los mejores conceptos que puedan al momento de entrar al mundo laboral, propondría tratar de deshacernos del uso de `Librería` como término y reemplazarlo por `Biblioteca` dentro de nuestros textos. _Personalmente uso el término en Inglés, así de esa manera creo que la mayoría puede entender a qué me refiero._

**Comment by lupomontero** [comment]
Ver https://github.com/Laboratoria/curricula-js/pull/773#issuecomment-456219931
