### ISSUE TITLE
Hackathon cierre Common Core: Revisar y Actualizar

### ISSUE THREAD

**Issue by CaroLaboratoria** [Laboratoria/curricula-js#774]
Como cierre del Common Core se realizará una Hackathon con el objetivo principal de que las estudiantes vivan la experiencia de tener este tipo de instancias antes de separarse a su track correspondiente.

Como propuesta inicial se plantea realizar la [Hackathon con temática de películas ](https://docs.google.com/document/d/1Q1kI0nvOeF7KZH8pJz9NYtC8Ft5kM0RQDPYNgZ_hC20/edit#heading=h.ddg8hvmum5kn) utilizada en el Bootcamp 2017-2.

Es necesario revisar si el nivel de esta instancia es acorde al momento planteado que es posterior al proyecto 3.

Se reciben sugerencias, opiniones al respecto

Gracias!

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @lupomontero @lalogf   @rocioalberdi

**Comment by nerdale** [comment]
Hola @CaroLaboratoria 
Los coaches de SCL estuvimos conversando y nos parece un buen proyecto para el cierre, en cuanto a la parte front end tiene manipulación de data y manejo del DOM, lo que si habría que especificar/agregar el uso de test y ver la posibilidad de entregarles un boilerplate, es como han venido trabajando hasta ahora y no nos hemos centrado en que entiendan ellas como configurar su propio proyecto, instalar dependencias etc. creemos que eso es más relevante para el comienzo del track FE.

:smile:

**Comment by nerdale** [comment]
En realidad creemos que hay dos caminos:

1. **Sin Boilerplate:** Hará que las estudiantes estén poniendo el foco en elementos accesorios del proyecto. 
Si es una hackaton de 3 días donde el énfasis está en soltar la mano, codear y trabajar en equipo, no se justifica realmente el configurar todo el proyecto, los archivos de test etc., que por otro lado, sería un skill interesante para las FE pero no sé si necesariamente para las UX, especialmente en este contexto de common core, pero la estructura del proyecto en si sería más básica en comparación a las que ya han trabajado en estos meses.

2. **Con Boilerplate:** Seguirá con lo que conocen, enfocándose en todos los ámbitos del proyecto.
En una hackatón de 3 días si bien trabajarían con una estructura ya conocida, tendrán muchas cosas más en que concentrarse, codear, test, linter js, linter html etc. pudiendo aparecer muchos focos en que concentrarse.

**Comment by CaroLaboratoria** [comment]
Gracias Ale. Mientras esperando más comentarios al respecto de los coaches, me gustaría hacer una propuesta base sobre el contexto (narración del reto). @lupomontero como este no es un proyecto propiamente tal, dónde lo ponemos lo propongo dentro de la estructura que ya tenemos aquí?

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @lupomontero @lalogf @rocioalberdi

**Comment by nerdale** [comment]
@diegovelezg ya comenzó a armar un [draft](https://github.com/Laboratoria/curricula-js/tree/69b9564ad7ba8c91385c419dec684cadb04f0446/projects/03-movies) para esto.

**Comment by lupomontero** [comment]
Ver #783

**Comment by lizzie136** [comment]
Agregué unos comentarios en el PR. Por otro lado, voy a poner mi comentario aquí para que no se desligue la conversación.  
>Desde mi punto de vista una de los principales retos del trabajo en equipo es decidir por donde comenzar. De mi parte no vería la necesidad de un boilerplate porque si un objetivo de aprendizaje es el tema de complejidad del trabajo en equipo en sí, darle un boilerplate ya comienza a dar bastantes leads de cómo sería el trabajo.

> - Creería que podemos sugerir un boilerplate, pero que depende de ellas la elección de herramientas, estructura de código, tests y demas.
Si pediría tests como parte del proyecto. Y un mínimo de cobertura. Quizás como hay bastante visual y aún no estoy segura que hayan visto mucho de mocking a este punto y no es un objetivo tampoco, pediría solo las funciones puras de manejo de datos.

**Comment by CaroLaboratoria** [comment]
Muchas gracias @lizzie136 ! Al final por lo menos la decisión para SCL que partió hoy, fue dejarlo sin boilerplate y enfocarnos en trabajar en todo el trabajo en equipo y en corto plazo. Cierto @nerdale ?

Quería comentar también sobre lo propuesto por @lupomontero . Al no ser un proyecto propiamente tal, genera ruido que esté dentro de la currícula oficial. Es por esto que creemos que es mejor mantenerlo al margen como dice Lupo y crear un repo privado. Así además nuestras estudiantes verán el desafío de la hackathon cuando sea el minuto y no antes.

**Comment by gaposx** [comment]
Me gusta la implementación de SCL al dejarlo sin boilerplate y con enfoque en trabajo en equipo y resultados al corto plazo. Tal como en otras hackathon, el objetivo es mostrar un MVP en pocas horas; el imponer una estructura y obligar a tests como parte del proyecto me suena un poco contraproducente.

**Comment by CaroLaboratoria** [comment]
@lupomontero cómo seguimos con este tema? te parece si creamos al repo privado y migramos las Hackathones y el proyecto "Silicon Valley"/"Job Placement"?

cc/ @Laboratoria/bootcamp-coaches @diegovelezg @lupomontero @lalogf @rocioalberdi

**Comment by lupomontero** [comment]
Gracias a todxs por los comentarios :rocket: :star: 

* Con respecto al proyecto `job-application`, veo que la versión del [`README.md` del repo privado de `curricula-ejecucion`](https://github.com/Laboratoria/curricula-ejecucion/blob/master/04-job-application/README.md) es más reciente que el que hay en [este repo](https://github.com/Laboratoria/curricula-js/blob/v2.x/projects/04-job-application/README.md). Podemos considerar que ya se ha movido y borrarlo acá?
* Por otro lado, acá dejo PR al repo privado para mover también el proyecto de registro de visitantes: https://github.com/Laboratoria/curricula-ejecucion/pull/44

Cierro este issue acá y continuamos las conversaciones con respecto a estos proyectos en particular en el otro repo :secret:
