### ISSUE TITLE
project(data-lovers): Agregar tarea "start" a package.json

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#776]
A la hora de hacer la implementación modelo esto ha sido una de las primeras cosas que hice... y no sé si simplemente deberíamos incluir algo como `serve` y un `npm-script` en el `package.json` algo como:

```json
"scripts": {
  ...
  "start": "serve ./src"
  ...
},
"dependencies": {
  ...
  "serve": "^10.1.1"
  ...
},
```

Qué les parece?

cc/ @Laboratoria/bootcamp-coaches

**Comment by juanjordan** [comment]
Lo que venía haciendo era correr `npm/http-server` en la carpeta `src`, dicho eso, me parece que cualquier alternativa es mejor a mostrar el sitio web desde `file:///` dado los varios quirks asociados a este (CORS policy, fetch, etc).

Con respecto a usar `serve`, lo último que supe fue que un major version bump quitó la capacidad de permitir Access-Control-Allow-Origin * desde el cli: https://github.com/zeit/serve/issues/389#issuecomment-393226615, para servir archivos estáticos, me parece, no importaría pero lo menciono para tenerlo en cuenta.

**Comment by lupomontero** [comment]
Este issue creo que también es aplicable al cipher y social network...

**Comment by merunga** [comment]
Ya vendría en el boilerplate?

**Comment by lupomontero** [comment]
@merunga: sí, la pregunta es básicamente si deberíamos siempre incluir una tarea `start` usando `npm-scripts` (así como hacemos con `test` y `pretest`).

**Comment by lupomontero** [comment]
Cómo lo ven? Los únicos dos proyectos donde aplicaría este cambio son `cipher` y `data-lovers`... creen que agregaría valor (mejoraría la experiencia de estudiantes)?

**Comment by juanjordan** [comment]
Estoy de acuerdo en proponer esa alternativa 👍

como punto en contra estaría que pueda generar una dependencia de ellas sobre la existencia de `npm-scripts` (como si fuese la única forma) pero pienso que si se hacen la pregunta "Por qué este proyecto no tiene un package.json con `npm-scripts`" la próxima vez que se topen con uno así es que se ha logrado el objetivo.

**Comment by lupomontero** [comment]
Gracias @juanjordan!

Traté de usar `http-server` como sugerías, pero me encontré con que la versión actual tiene una vulnerabilidad. En este caso no vamos a usar este servidor para escuchar requests en una red pública, así que no es grave, pero igual preferiría evitar que las estudiantes vean un :warning: warning al instalar dependencias.

![image](https://user-images.githubusercontent.com/110297/57556023-77b31300-733b-11e9-96aa-ccc310906ac5.png)

Me he tomado la libertad de agregar la tarea `start` a:

* `cipher`: https://github.com/Laboratoria/curricula-js/commit/107b3c84af0214bf740ef9fcc840cd38435e6d0f https://github.com/Laboratoria/curricula-js/commit/87b9b77cbea212ca05fe961e3fe1b416ddbe380c
* `data-lovers`: https://github.com/Laboratoria/curricula-js/commit/22743647d6e75817abe9b8b96967b336ea3a9f4b

Cierro este issue por ahora. Si alguien quiere sugerir algo porfa abran nuevos issues :wink:
