### ISSUE TITLE
project(social-network): Quitar niveles esperados?

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#785]
En los proyectos anteriores ([cipher](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher#evaluaci%C3%B3n) y [data-lovers](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers#evaluaci%C3%B3n)) se decidió quitar los niveles esperados del readme del proyecto. Deberíamos hacer lo mismo [en este proyecto](https://github.com/Laboratoria/curricula-js/tree/master/projects/03-social-network#evaluaci%C3%B3n)?

cc/ @diegovelezg @CaroLaboratoria @rocioalberdi

**Comment by CaroLaboratoria** [comment]
Hola, efectivamente hemos quitado los niveles linkeados a cada proyecto y declarado dos instancias con niveles asociados: Coomon Core y Final del Bootcamp.
Igual hay algunas sedes que han optado por mantener los niveles para cada proyecto.

**Comment by lupomontero** [comment]
Entonces dejamos los niveles en el `README.md` _compartido_ en este repo y que cada sede decida después si quitarlos en su versión? Si es así creo que tendría sentido que hagamos lo mismo en _todos_ los proyectos.

cc/ @CaroLaboratoria @diegovelezg @rocioalberdi @lalogf

**Comment by lupomontero** [comment]
Por ahora, hasta que no se completen las conversaciones pendientes sobre la rúbrica, hemos decidido dejar los niveles esperados en los readmes de los proyectos en este repo (como _guía de diseño_), pero al mismo tiempo recomendamos quitar los _numeritos_ a la hora de crear los repos específicos de cada grupo (_cohort_).
