### ISSUE TITLE
Duplicado en test de cipher.spec.js (Proyecto 1: Cipher)

### ISSUE THREAD

**Issue by ilyoss** [Laboratoria/curricula-js#792]
Me di cuenta que en el archivo de los test, en la parte del encode viene duplicada la prueba para los caracteres especiales, y falta la prueba de minúsculas.

Viene dos veces este codigo comentado:
// Hacker edition
//
// Si decides implementar soporte para caracteres no alfabéticos descomenta
// el test a continuación.
//
// it('debería retornar " !@" para " !@"', () => {
// assert.equal(cipher.encode(33, ' !@'),' !@');
// });

y uno de los repetidos debería quedar así:

// Hacker edition
//
// Si decides agregar soporte para minúsculas descomenta el test a
// continuación.
//
// it('debería retornar "hijklmnopqrstuvwxyzabcdefg" para "abcdefghijklmnopqrstuvwxyz" con offset 33', () => {
// assert.equal(
// cipher.encode(33, 'abcdefghijklmnopqrstuvwxyz'),
// 'hijklmnopqrstuvwxyzabcdefg'
// );
// });

**Comment by lupomontero** [comment]
Esto se corrigió en https://github.com/Laboratoria/curricula-js/pull/793.

Una vez más, gracias @ilyoss!!

**Comment by lupomontero** [comment]
@all-contributors please add @ilytrevino for reporting bug
