### ISSUE TITLE
project(data-lovers) propuesta de set de datos

### ISSUE THREAD

**Issue by lalogf** [Laboratoria/curricula-js#799]
Hola,

Encontré este set de datos de pacientes en USA. Quizás se interesante incluirlo como opción en este proyecto.

> The SMART sample patient records contain a mix of data derived from real de-identified patient records, as well as some synthetic data elements.

Este endpoint `https://r2.smarthealthit.org/Patient` devuelve toda la lista de pacientes de ejemplo.

Los puse [aquí](https://gist.github.com/lalogf/1b79c5cac4f34f52300ef48284704d09) para que les den una mirada. 

También por cada ID de un paciente se puede llamar al endpoint: `https://r2.smarthealthit.org/Observation?subject:Patient=` + `id` y obtener una lista de los resultados de este paciente, ya se de laboratorio o de cosas como presión sanguínea o indíce de masa muscular. 

[Aquí](https://gist.github.com/lalogf/7b9a45b3a9856502fd8f1e0ad69d1f9f) un ejemplo.

La documentación del API no es tan buena, pero pueden encontrarla [aquí](http://docs.smarthealthit.org/clients/javascript/) 

Me cuentan qué opinan.

**Comment by diegovelezg** [comment]
Independientemente de qué tan apropiada sea la estructura de los datos (@lupomontero ) sería genial tener un set más.

**Comment by shirley-startary** [comment]
Yo obtuve la data de la API de Rick and Morty, podría agregarla también!

**Comment by lupomontero** [comment]
@shirley-startary: te animarías a proponer un PR con estas dos nuevas fuentes de datos?

**Comment by shirley-startary** [comment]
Si, claro me aviento ( como dicen aquí en México)

**Comment by lupomontero** [comment]
Buenazo @shirley-startary! :rocket: 

Quedamos a la espera de PR (rama `v2.x`)... avisa si te surge cualquier duda :muscle:

**Comment by shirley-startary** [comment]
Si, gracias

**Comment by shirley-startary** [comment]
@lupomontero acabo de hacer el PR solo que travis me está bloqueando, se que es algo con node, me parece que por las versiones, me puedes apoyar en resolverlo, Saludos

**Comment by lupomontero** [comment]
@shirley-startary: el build en travis parece que está pasando ok :heavy_check_mark: 

Los :x: son porque hemos configurado el repo para que los _reviews_ sean obligatorios en esta rama. En un ratito lo reviso :wink:

![image](https://user-images.githubusercontent.com/110297/57559962-d8e1e300-7349-11e9-8a60-7abe8166ff98.png)

Cierro este issue y continuamos la conversación en el PR #826
