### ISSUE TITLE
project(Tic tac toe - React Native) habilidades (js estilo)

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/curricula-js#804]
@lupomontero esa indicación de "estilo", en la lista de habilidades que se evalúan, ¿se refiere a la categoría HTML/CSS de la rub?

![image](https://user-images.githubusercontent.com/28717078/54443853-45f94380-4720-11e9-9aa8-871cdd3f5252.png)

**Comment by lupomontero** [comment]
Hmmm... en este caso _Estilo_ está dentro de la sección de _JavaScript_, así que haría referencia a _Estilo (linter js)_...

De todas formas, acabo de chequear el `README.md` del proyecto `05-tic-tac-toe-rn` en la rama `v2.x` y el nivel esperado para esta habilidad en este proyecto ahora parece ser `3`... :thinking: 

Por otro lado, este proyecto en particular no tiene en cuenta las habilidades de `HTML` y `CSS` ya que se trata de una aplicación nativa, sin navegador, por lo tanto no hay HTML/CSS :wink: 

Me tomo la libertad de cerrar este issue, pero porfa reábrelo si lo consideras necesario.
