### ISSUE TITLE
Desarrollo contenido `03-control-flow`

### ISSUE THREAD

**Issue by chamodev** [Laboratoria/curricula-js#83]
- [x] crear lectura de `flow-diagrams` @aocsa 
- [x] crear lectura de `input-output` @aocsa 
- [x] crear retos en Replit @aocsa 
- [x] crear quiz 1 @chamo
- [x] crear quiz 2 @chamo
- [x] crear auto-evaluación `11-self-assessment` @chamo
- [x] crear video del uso de `continue` y `break` en un `for` @MichelleSV 
- [x] crear video de `funciones` con el ejemplo de JS for Kids pg 128 (funcion de imprimir caras) @MichelleSV 
- [x] pulir lectura de `02-functions.md` @chamo
- [x] pulir el texto de `03-structured-programming-paradigm.md` @chamo
- [x] crear video solucionario de `Tablero de Ajedrez` @MichelleSV 
- [x] crear video solucionario de `FizzBuzz` @MichelleSV
- [x] crear video del uso de `if...else` usando ejercicio de [JS for Kids](http://pepa.holla.cz/wp-content/uploads/2015/11/JavaScript-for-Kids.pdf) página 94 @nerdale
- [x] crear video del uso de `switch` con un ejemplo cualquiera @MichelleSV
- [x] crear video del uso de `for` usando el ejercicio de [JS for Kids](http://pepa.holla.cz/wp-content/uploads/2015/11/JavaScript-for-Kids.pdf) página 100 llamado `timesToSayHello` construyendo la tabla de bucles con el detalle de cada iteración @nerdale
- [x] crear solucionario de `Funciones matemáticas` @MichelleSV
- [x] crear solucionario de `Ordenando comida` @nerdale
- [x] crear solucionario de `Contando caracteres y espacios` @nerdale
- [x] crear solucionario de `Edades y etapas`@MichelleSV
- [x] pulir el texto de `00-opening` @chamo
- [x] pulir el texto de `12-closing` @chamo

@MichelleSV y @nerdale: como acordamos, aquí está la lista de todo lo que debemos desarrollar. Porfa, me avísan cuál estarán trabajando cada una. Gracias!

**Comment by nerdale** [comment]
Ok @chamodev esta es la organización que tenemos con @MichelleSV :

Tareas @nerdale:
![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video del uso de if...else
 ![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video del uso de for
 ![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video solucionario de Tablero de Ajedrez
 ![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video solucionario de Ordenando comida
 ![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video solucionario de Contando caracteres y espacios

Tareas @MichelleSV : 
![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video del uso de switch
![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video solucionario de FizzBuzz
![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video solucionario de Funciones matemáticas
![image](https://user-images.githubusercontent.com/20868992/28622661-50c0e584-71e3-11e7-823b-dd2d766fdcfe.png) crear video solucionario de Edades y etapas

**Comment by chamodev** [comment]
Excelente. Gracias! Actualicé la tarjeta original para llevar el control ahí mismo. Lo que les pediría es definir un entregable para el miércoles 2 de Agosto. Qué tendremos listo para ese momento?

**Comment by chamodev** [comment]
Team: he actualizado este issue y he agregado a @aocsa, quien va a desarrollar un par de cosas para este curso. Porfa revisen los pendientes. Thanks!

**Comment by chamodev** [comment]
Team: este contenido ya ha sido desarrollado y liberado al Ops team para review & feedback. Voy a cerrar este issue y abriremos otro con el feedback recibido. Gracias a todo el team por el esfuerzo!! Love ya!
