### ISSUE TITLE
So long v2.x branch, and thanks for all the fish...

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#835]
![So long and thanks for all the fish](https://media.giphy.com/media/laESBDZWUubAc/giphy-downsized.gif)

Esto es un _anuncio parroquial_ para hacerles saber que la rama `v2.x` de este repo va a desaparecer :skull: ... en este momento no hay ningún PR pendiente y creo que es un momento prudente de hacer este cambio, ... que sinceramente es algo que quiero hacer desde hace tiempo...

Desde ahora, la versión actual de la currícula (`v2.x`), pasará a desarrollarse en `master`, así que porfa dirijan sus PRs directamente a `master` en vez de tener que pasar primero por `v2.x`. 

Esto debería permitir dar más visibilidad a la versión reciente (en rama por defecto - `master`) y simplificar el proceso de colaboración (menos pasos),

cc/ @Laboratoria/bootcamp-coaches @Laboratoria/curricula-mantainers

**Comment by juanjordan** [comment]
Hola! [challenger approaching](https://amp.businessinsider.com/images/5c0a7851965aa0162203f983-750-422.jpg) here

Estamos tomando esta decisión en base a comentarios de los mismos usuarios (en este caso quien ya haya enviado o no – pero sí quería – un PR) a la curricula? Personalmente encontraba interesante el hecho de tener una rama `v2.x` por que se asemejaba a algo como [semver](https://semver.org/), en este caso `2` tiene sentido porque es _breaking change_ con respecto a la currícula pasada que no era basada en proyectos, pero también si afinábamos cosas (corregíamos bugs) teníamos que apuntar a `x` en `v2.x` lo cual era raro.

No quiero parar el avance si consideramos que apuntar a master hará que nos movamos más rápido pero sí quería preguntar si también pudimos considerar una forma más `semver` de ver la currícula.

**Comment by lupomontero** [comment]
Gracias por el comentario @juanjordan :+1: 

En principio creo que estoy de acuerdo... y queremos apuntar a un sistema de versiones _semver inspired_... al mismo tiempo, la rama `v2.x` estaba cumpliendo más como rama `develop` que como rama de mantenimiento de versión (ie: `v1.x`, `v2.x`)... :thinking: 

Propongo que veamos si este cambio de verdad dinamiza el proceso de colaboración y visibilidad del desarrollo. Más adelante podemos considerar crear una rama `develop` si fuera necesario y cuando toque pensar en `v3.x` si pensaría en volver a crear `v2.x` como _maintenance branch_... pero no a corto plazo...

Cómo lo ves?

**Comment by lupomontero** [comment]
@juanjordan: tomo nota de tu comentario para el medio plazo y cierro este issue por ahora, te parece?

**Comment by juanjordan** [comment]
Totalmente de acuerdo, que esta conversación quede de testigo! 🚂 👍
