### ISSUE TITLE
Desarrollar Lesson 6: HOCs y estado global curso React

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curricula-js#89]

**Comment by merunga** [comment]
@lupomontero aca necesitamos establecer que implementacion vanilla de redux usamos. Aquí unos ejemplos:

- [https://github.com/ramonvictor/tic-tac-toe-js](https://github.com/ramonvictor/tic-tac-toe-jsl)
- [https://github.com/k9ordon/gordux.js](https://github.com/k9ordon/gordux.js)
- [https://codepen.io/aknip/pen/vGeavR](https://codepen.io/aknip/pen/vGeavR)

**Comment by lupomontero** [comment]
Después de conversar sobre este tema tomamos la decisión de usar `redux` directamente, sin entrar en muchos detalles y dándoles un punto de partida con un set up preestablecido.

**Comment by merunga** [comment]
@lupomontero nos apresuramos. La [pregunta](https://github.com/Laboratoria/curricula-js/issues/89#issuecomment-318906111)  pero el issue sigue abierto

**Comment by lupomontero** [comment]
🙉
