### ISSUE TITLE
Desarrollo curso "JS Deep Dive"

### ISSUE THREAD

**Issue by CaroLaboratoria** [Laboratoria/curricula-js#96]
- [x] Pull Request de última versión ReadMe @ivandevp 
- [x] Crear texto de lección ECMAScript 2015 @brecabal

**Comment by lupomontero** [comment]
En este momento @ivandevp está a cargo de crear el _producto_ central alrededor del cual se va a terminar de definir el syllabus:

https://github.com/Laboratoria/curricula-js/issues/105

Una vez tengamos una idea más clara del _producto_ en sí creo que estaremos en posición de acotar el syllabus para la primera iteración del curso en EC.

Por otro lado, el PR de @brecabal con los cambios al `README.md` y primeras lecciones de `ES6` está pendiente de que se apruebe/mezcle mi PR a su fork:

https://github.com/Laboratoria/curricula-js/pull/78#pullrequestreview-53979176

Vamos equipo 💪 !

**Comment by brecabal** [comment]
Listo PR , quedo atenta a lo que se necesiten .

**Comment by ivandevp** [comment]
Se cierra este issue, ya que el curso quedó definido a nivel de contenido en base a producto.
