### ISSUE TITLE
Curso react - Agregar documentacion sobre js expressions en jsx

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curricula-js#99]

**Comment by giancorzo** [comment]
@merunga Hola Merunga puedes agregarle una descripción a tu issue para poder tener un poco de contexto?

**Comment by merunga** [comment]
@giancorzo hay q agregar info a la leccion de JSX de cómo se incrustan [expresiones de javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#Expressions) usando llaves (el avance sin traducir [aqui](https://github.com/Laboratoria/curricula-js/blob/11-react-patches/11-react/L02-jsx/02a-jsx-conditional-rendering.md)

**Comment by merunga** [comment]
cerrado en #140
